module.exports = {
  up(queryInterface) {
    let records = [{"loc":"BAT",
      "ct_cfr_section":"412.13.a",
      "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 and when the provisions of paragraph (b) of this section apply, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"BAT",
        "ct_cfr_section":"423.13",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this part must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best available technology economically achievable (BAT)."},
      {"loc":"NSPS",
        "ct_cfr_section":"423.15.a",
        "ct_notes":"1982 NSPS. Any new source as of November 19, 1982, subject to paragraph (a) of this section, must achieve the following new source performance standards, in addition to the limitations in \\u00A7423.13 of this part, established on November 3, 2015. In the case of conflict, the more stringent requirements apply:"},
      {"loc":"PSES",
        "ct_cfr_section":"423.16",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for existing sources (PSES) by July 1, 1984:"},
      {"loc":"PSNS",
        "ct_cfr_section":"423.17.a",
        "ct_notes":"1982 PSNS. Except as provided in 40 CFR 403.7, any new source as of October 14, 1980, subject to paragraph (a) of this section, which introduces pollutants into a publicly owned treatment works, must comply with 40 CFR part 403, the following pretreatment standards for new sources, and the PSES in \\u00A7423.16, established on November 3, 2015. In the case of conflict, the more stringent standards apply:"},
      {"loc":"NSPS",
        "ct_cfr_section":"412.15.a",
        "ct_notes":"Except as provided in paragraph (b) of this section, any new source subject to this subpart must achieve the following performance standards:"},
      {"loc":"BPT",
        "ct_cfr_section":"412.12.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and subject to the provisions of paragraph (b) of this section, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BPT",
        "ct_cfr_section":"412.22.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart shall achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the (BPT):"},
      {"loc":"BPT",
        "ct_cfr_section":"412.31",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BAT",
        "ct_cfr_section":"412.33",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"BPT",
        "ct_cfr_section":"412.43",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"412.44",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"412.45",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"412.46",
        "ct_notes":"Any new source subject to this subpart must achieve the following effluent limitations representing the application of NSPS:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.11.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best practicable control technology currently available:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.12.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best available technology economically achievable:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.13",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.14.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and \\u00A7403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the pretreatment standards for existing sources listed below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.15",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the pretreatment standards for new sources listed below:"},
      {"loc":"PSNS",
        "ct_cfr_section":"461.23.a",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below."},
      {"loc":"BPT",
        "ct_cfr_section":"461.25.a",
        "ct_notes":" Except as provided in \\u00A7403.7 any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the pretreatment standards for new sources listed below."},
      {"loc":"BPT",
        "ct_cfr_section":"461.31.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best practicable control technology currently available:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.32.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best available technology economically achievable:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.33.a",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.34.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the pretreatment standards for existing sources listed below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.35.a",
        "ct_notes":"Except as provided in \\u00A7403.7, any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for new sources:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.43.a",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.44.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for existing sources listed below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.45.a",
        "ct_notes":"Except as provided in \\u00A7403.7 any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for new sources listed below."},
      {"loc":"BPT",
        "ct_cfr_section":"461.53.a",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.55.a",
        "ct_notes":"Except as provided in \\u00A7403.7 any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for new sources listed below:"},
      {"loc":"NSPS",
        "ct_cfr_section":"461.63.a",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.64.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for existing sources listed below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.65.a",
        "ct_notes":"Except as provided in \\u00A7403.7 any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for new sources listed below:"},
      {"loc":"BPT",
        "ct_cfr_section":"461.11.b",
        "ct_notes":"jodi #1"},
      {"loc":"BPT",
        "ct_cfr_section":"461.11.c",
        "ct_notes":"jodi #2"},
      {"loc":"NSPS",
        "ct_cfr_section":"461.23",
        "ct_notes":"jodi"},
      {"loc":"BPT",
        "ct_cfr_section":"461.71.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best practicable control technology currently available:"},
      {"loc":"BAT",
        "ct_cfr_section":"461.72.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best available technology economically achievable:"},
      {"loc":"NSPS",
        "ct_cfr_section":"461.73.a",
        "ct_notes":"The discharge of wastewater pollutants from any new source subject to this subpart shall not exceed the standards set forth below:"},
      {"loc":"PSES",
        "ct_cfr_section":"461.74.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for existing sources:"},
      {"loc":"PSNS",
        "ct_cfr_section":"461.75.a",
        "ct_notes":"Except as provided in \\u00A7403.7 any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for new sources listed below:"},
      {"loc":"NSPS",
        "ct_cfr_section":"423.15.b",
        "ct_notes":"2015 NSPS. Any new source as of November 17, 2015, subject to paragraph (b) of this section, must achieve the following new source performance standards:"},
      {"loc":"PSNS",
        "ct_cfr_section":"423.17.b",
        "ct_notes":"2015 PSNS. Except as provided in 40 CFR 403.7, any new source as of June 7, 2013, subject to this paragraph (b), which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and the following pretreatment standards for new sources:"},
      {"loc":"BCT",
        "ct_cfr_section":"430.13",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart shall achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best conventional pollutant control technology (BCT): The limitations shall be the same as those specified for conventional pollutants (which are defined in 40 CFR 401.16) in \\u00A7430.12 of this subpart for the best practicable control technology currently available (BPT)."},
      {"loc":"PSES",
        "ct_cfr_section":"430.16",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must: comply with 40 CFR part 403; and achieve the following pretreatment standards for existing sources (PSES) if it uses chlorophenolic-containing biocides. Permittees not using chlorophenolic-containing biocides must certify to the permit-issuing authority that they are not using these biocides. PSES must be attained on or before July 1, 1984:"},
      {"loc":"PSNS",
        "ct_cfr_section":"430.17",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must: comply with 40 CFR part 403; and achieve the following pretreatment standards for new sources (PSNS) if it uses chlorophenolic-containing biocides. Permittees not using chlorophenolic-containing biocides must certify to the permit-issuing authority that they are not using these biocides:"},
      {"loc":"NSPS",
        "ct_cfr_section":"412.25.a",
        "ct_notes":"Except as provided in paragraph (b) of this section, any new source subject to this subpart must achieve the following performance standards:"},
      {"loc":"PSNS",
        "ct_cfr_section":"412.26.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and in paragraph (b) of this section, any new source subject to this subpart must achieve the following performance standards:"},
      {"loc":"NSPS",
        "ct_cfr_section":"412.35",
        "ct_notes":"Any new point source subject to this subpart must achieve the following effluent limitations representing the application of NSPS:"},
      {"loc":"BAT",
        "ct_cfr_section":"430.14",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart where chlorophenolic-containing biocides are used must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best available technology economically achievable (BAT). Non-continuous dischargers shall not be subject to the maximum day mass limitations in kg/kkg (lb/1000 lb) but shall be subject to concentration limitations. Concentration limitations are only applicable to non-continuous dischargers. Permittees not using chlorophenolic-containing biocides must certify to the permit-issuing authority that they are not using these biocides:"},
      {"loc":"NSPS",
        "ct_cfr_section":"430.15",
        "ct_notes":"Any new source subject to this subpart must achieve the following new source performance standards (NSPS), except that non-continuous dischargers shall not be subject to the maximum day and average of 30 consecutive days effluent limitations for BOD5 and TSS, but shall be subject to annual average effluent limitations. Also, for non-continuous dischargers, concentration limitations (mg/l) shall apply, where provided. Concentration limitations will only apply to non-continuous dischargers. Only facilities where chlorophenolic-containing biocides are used shall be subject to pentachlorophenol and trichlorophenol limitations. Permittees not using chlorophenolic-containing biocides must certify to the permit-issuing authority that they are not using these biocides:"},
      {"loc":"BCT",
        "ct_cfr_section":"430.23",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best conventional pollutant control technology (BCT). The limitations shall be the same as those specified in \\u00A7430.22 of this subpart for the best practicable control technology currently available (BPT)."},
      {"loc":"BAT",
        "ct_cfr_section":"430.24",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by the application of the best available technology economically achievable (BAT)."},
      {"loc":"BAT",
        "ct_cfr_section":"430.24.e",
        "ct_notes":"Pursuant to 40 CFR 122.44(i) and 122.45(h), a discharger must demonstrate compliance with the effluent limitations in paragraph (a)(1) or (b)(3) of this section, as applicable, by monitoring for all pollutants (except for AOX and COD) at the point where the wastewater containing those pollutants leaves the bleach plant. The permitting authority may impose effluent limitations and/or monitoring requirements on internal wastestreams for any other pollutants covered in this section as appropriate under 40 CFR 122.44(i) and 122.45(h). In addition, a discharger subject to a limitation on total pulping area condensate, evaporator condensate, and bleach plant wastewater flow under paragraph (b)(4)(i) of this section, for Tier II and Tier III, must demonstrate compliance with that limitation by establishing and maintaining flow measurement equipment to monitor these flows at the point or points where they leave the pulping area, evaporator area, and bleach plant."},
      {"loc":"NSPS",
        "ct_cfr_section":"430.25.e",
        "ct_notes":"Pursuant to 40 CFR 122.44(i) and 122.45(h), a discharger must demonstrate compliance with the limitations in paragraph (b)(1) or (c)(1) of this section, as applicable, by monitoring for all pollutants (except for AOX, COD, BOD5, TSS, and pH) at the point where the wastewater containing those pollutants leaves the bleach plant. The permitting authority may impose effluent limitations and/or monitoring requirements on internal wastestreams for any other pollutants covered in this section as appropriate under 40 CFR 122.44(i) and 122.45(h). In addition, a discharger subject to a limitation on total pulping area condensate, evaporator condensate, and bleach plant wastewater flow under paragraph (c)(2) of this section must demonstrate compliance with that limitation by establishing and maintaining flow measurement equipment monitoring these flows at the point or points where they leave the pulping area, evaporator area, and the bleach plant."},
      {"loc":"NSPS",
        "ct_cfr_section":"430.25",
        "ct_notes":"New sources subject to this subpart must achieve the following new source performance standards (NSPS), as applicable."},
      {"loc":"PSES",
        "ct_cfr_section":"430.26",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and must achieve the following pretreatment standards for existing sources (PSES)."},
      {"loc":"PSES",
        "ct_cfr_section":"430.26.c",
        "ct_notes":" An indirect discharger must demonstrate compliance with the pretreatment standards in paragraph (a)(1) of this section by monitoring at the point where the wastewater containing those pollutants leaves the bleach plant."},
      {"loc":"PSNS",
        "ct_cfr_section":"430.27",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and must achieve the following pretreatment standards for new sources (PSNS)."},
      {"loc":"PSNS",
        "ct_cfr_section":"430.27.c",
        "ct_notes":"An indirect discharger must demonstrate compliance with the pretreatment standards in paragraph (a)(1) of this section by monitoring at the point where the wastewater containing those pollutants leaves the bleach plant."},
      {"loc":"BCT",
        "ct_cfr_section":"412.32",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:\r\n\r\n(a) For CAFO production areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.31(a).\r\n\r\n(b) For CAFO land application areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.31(b)."},
      {"loc":"BAT",
        "ct_cfr_section":"430.33",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:\r\n\r\n(a) For CAFO production areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.31(a).\r\n\r\n(b) For CAFO land application areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.31(b)."},
      {"loc":"BCT",
        "ct_cfr_section":"430.44",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:\r\n\r\n(a) For CAFO production areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.43(a).\r\n\r\n(b) For CAFO land application areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.43(b)."},
      {"loc":"BAT",
        "ct_cfr_section":"430.45",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:\r\n\r\n(a) For CAFO production areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.43(a).\r\n\r\n(b) For CAFO land application areas: the CAFO shall attain the same limitations and requirements as \\u00A7412.43(b)."},
      {"loc":"BPT",
        "ct_cfr_section":"423.12.b",
        "ct_notes":"Any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction by the application of the best practicable control technology currently available (BPT):"},
      {"loc":"BPT",
        "ct_cfr_section":"414.20",
        "ct_notes":"The provisions of this subpart are applicable to process wastewater discharges resulting from the manufacture of rayon fiber by the viscose process only."},
      {"loc":"BPT",
        "ct_cfr_section":"414.21",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"PSES",
        "ct_cfr_section":"414.25",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.26",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7411.111."},
      {"loc":"PSES",
        "ct_cfr_section":"414.35",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.36",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"BPT",
        "ct_cfr_section":"414.41",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"PSES",
        "ct_cfr_section":"414.45",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.46",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"BPT",
        "ct_cfr_section":"414.51",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"BPT",
        "ct_cfr_section":"414.61",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"PSES",
        "ct_cfr_section":"414.65",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.66",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"BPT",
        "ct_cfr_section":"414.71",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"PSES",
        "ct_cfr_section":"414.75",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.76",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"BPT",
        "ct_cfr_section":"414.81",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"PSES",
        "ct_cfr_section":"414.85",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.86",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"BPT",
        "ct_cfr_section":"414.31",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, and in 40 CFR 414.11(i) for point sources with production in two or more subcategories, any existing point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"BAT/NSPS",
        "ct_cfr_section":"414.91.a",
        "ct_notes":"Any point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"PSES",
        "ct_cfr_section":"414.55",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"PSNS",
        "ct_cfr_section":"414.56",
        "ct_notes":"Except as provided in 40 CFR 403.7 any new source subject to this subpart which introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve discharges in accordance with \\u00A7414.111."},
      {"loc":"BAT/NSPS",
        "ct_cfr_section":"414.101.a",
        "ct_notes":"Any point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentartions in the following table."},
      {"loc":"PSES/PSNS",
        "ct_cfr_section":"414.111.a",
        "ct_notes":"Any point source subject to this subpart must achieve discharges not exceeding the quantity (mass) determined by multiplying the process wastewater flow subject to this subpart times the concentration listed in the following table."},
      {"loc":"BPT",
        "ct_cfr_section":"438.12",
        "ct_notes":"Except as provided at 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT."},
      {"loc":"BCT",
        "ct_cfr_section":"438.13",
        "ct_notes":"Except as provided at 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitation representing the application of BCT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"438.15",
        "ct_notes":"The performance standards apply with respect to each new point source that commences discharge after June 12, 2003."},
      {"loc":"BPT",
        "ct_cfr_section":"433.13.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the degree of effluent reduction attainable by applying the best practicable control technology currently available (BPT):"},
      {"loc":"BPT",
        "ct_cfr_section":"433.13.c",
        "ct_notes":"No user subject to the provisions of this subpart shall augment the use of process wastewater or otherwise dilute the wastewater as a partial or total substitute for adequate treatment to achieve compliance with this limitation."},
      {"loc":"BAT",
        "ct_cfr_section":"433.14.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitation representing the degree of effluent reduction attainable by applying the best available technology economically achievable (BAT):"},
      {"loc":"BAT",
        "ct_cfr_section":"433.14.c",
        "ct_notes":"No user subject to the provisions of this subpart shall augment the use of process wastewater or otherwise dilute the wastewater as a partial or total substitute for adequate treatment to achieve compliance with this limitation."},
      {"loc":"PSES",
        "ct_cfr_section":"433.15.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for existing sources (PSES):"},
      {"loc":"NSPS",
        "ct_cfr_section":"433.16.a",
        "ct_notes":"Any new source subject to this subpart must achieve the following performance standards:"},
      {"loc":"NSPS",
        "ct_cfr_section":"433.16.c",
        "ct_notes":"No user subject to the provisions of this subpart shall augment the use of process wastewater or otherwise dilute the wastewater as a partial or total substitute for adequate treatment to achieve compliance with this limitation."},
      {"loc":"PSNS",
        "ct_cfr_section":"433.17.a",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart that introduces pollutants into a publicly owned treatment works must comply with 40 CFR part 403 and achieve the following pretreatment standards for new sources (PSNS):"},
      {"loc":"PSNS",
        "ct_cfr_section":"433.17.c",
        "ct_notes":"No user subject to the provisions for this subpart shall augment the use of process wastewater or otherwise dilute the wastewater as a partial or total substitute for adequate treatment to achieve compliance with this limitation."},
      {"loc":"PSNS",
        "ct_cfr_section":"433.17.d",
        "ct_notes":"An existing source submitting a certification in lieu of monitoring pursuant to 433.12 (a) and (b) of this regulation must implement the toxic organic management plan approved by the control authority."},
      {"loc":"PSES",
        "ct_cfr_section":"433.15.c",
        "ct_notes":"No user introducing wastewater pollutants into a publicly owned treatment works under the provisions of this subpart shall augment the use of process wastewater as a partial or total substitute for adequate treatment to achieve compliance with this standards."},
      {"loc":"PSES",
        "ct_cfr_section":"433.15.d",
        "ct_notes":"An existing source submitting a certification in lieu of monitoring pursuant to 433.12 (a) and (b) of this regulation must implement the toxic organic management plan approved by the control authority."},
      {"loc":"PSES",
        "ct_cfr_section":"433.15.f",
        "ct_notes":"Compliance with the provisions of paragraph (c), (d), and (e) of this section shall be achieved as soon as possible, but not later than June 30, 1984, however metal finishing facilities which are also covered by part 420 (iron and steel) need not comply before July 10, 1985. Compliance with the provisions of paragraphs (a) and (b) of this section shall be achieved as soon as possible, but not later than February 15, 1986."},
      {"loc":"BPT",
        "ct_cfr_section":"437.11.a",
        "ct_notes":"(a) Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.10(b), any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"437.12",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.10(b), any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"437.13.a",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.10(b), any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"437.14.a",
        "ct_notes":"Except as provided in \\u00A7437.10(b), any new source subject to this subpart must achieve the following performance standards:"},
      {"loc":"PSES",
        "ct_cfr_section":"437.15.a",
        "ct_notes":"Except as provided in 40 CFR 403.7, 403.13 or \\u00A7437.10(b), and no later than December 22, 2003, any existing source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"PSNS",
        "ct_cfr_section":"437.16.a",
        "ct_notes":"Except as provided in 40 CFR 403.7 or \\u00A7437.10(b), any new source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"BPT",
        "ct_cfr_section":"437.21",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.20(b), any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"437.22",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.20(b), any existing point source subject to this subpart must achieve the following effluent limitations attainable by the application of BCT"},
      {"loc":"BAT",
        "ct_cfr_section":"437.23",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.20(b), any existing point source subject to this subpart must achieve the following effluent limitations by the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"437.24",
        "ct_notes":"Except as provided in \\u00A7437.20(b), any new source subject to this subpart must achieve the following performance standards:"},
      {"loc":"PSES",
        "ct_cfr_section":"437.25",
        "ct_notes":"Except as provided in 40 CFR 403.7, 403.13 or \\u00A7437.20(b), and no later than December 22, 2003, any existing source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"PSNS",
        "ct_cfr_section":"437.26",
        "ct_notes":"Except as provided in 40 CFR 403.7 or \\u00A7437.20(b), any new source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"BPT",
        "ct_cfr_section":"437.31",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.30(b), any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"437.32",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.30(b), any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"437.33",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.30(b), any existing point source subject to this subpart must achieve limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"437.34",
        "ct_notes":"Except as provided in \\u00A7437.30(b), any new source subject to this subpart must achieve the following new source performance standards:"},
      {"loc":"PSES",
        "ct_cfr_section":"437.35",
        "ct_notes":"Except as provided in 40 CFR 403.7, 403.13 or \\u00A7437.30(b), and no later than December 22, 2003, any existing source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"PSNS",
        "ct_cfr_section":"437.36",
        "ct_notes":"Except as provided in 40 CFR 403.7 or \\u00A7437.30(b), any new source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"BPT",
        "ct_cfr_section":"437.42.a",
        "ct_notes":"(a) Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.40(b), any existing facility subject to this subpart which combines treated or untreated wastes from subparts A, B, or C of this part may be subject to Multiple Wastestream Subcategory effluent limitations representing the application of BPT set forth in paragraphs (b), (c), (d), or (e) of this section if the discharger agrees to the following conditions in its NPDES permit: (1) The discharger will meet the applicable Multiple Wastestream Subcategory limitations set forth in (b), (c), (d) or (e); (2) The discharger will notify its NPDES permit writer at the time of renewal or modification of its permit, of its desire to be subject to the Multiple Waste Subcategory by submitting to the NPDES permit writer an initial certification statement as described in \\u00A7437.41(a); (3) The discharger will submit to its NPDES permitting authority a periodic certification statement as described in \\u00A7437.41(b) once a year; and (4) The discharger will maintain at the office of the facility and make available for inspection the on-site compliance paperwork as described in \\u00A7437.41(c)."},
      {"loc":"BPT",
        "ct_cfr_section":"437.42.b",
        "ct_notes":"(b) Combined waste receipts from subparts A, B, and C of this part. (1) As provided in \\u00A7437.42(a), any existing point source subject to this paragraph must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BPT",
        "ct_cfr_section":"437.42.c",
        "ct_notes":"(c) Combined waste receipts from subparts A and B of this part. (1) As provided in \\u00A7437.42(a), any existing point source subject to this paragraph must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BPT",
        "ct_cfr_section":"437.42.d",
        "ct_notes":"(d) Combined waste receipts from subparts A and C of this part. (1) As provided in \\u00A7437.42(a), any existing point source subject to this paragraph must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BPT",
        "ct_cfr_section":"437.42.e",
        "ct_notes":"(e) Combined waste receipts from subparts B and C of this part. As provided in \\u00A7437.42(a), any existing point source subject to this paragraph must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"437.43.a",
        "ct_notes":"(a) Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.40(b), any existing facility subject to this subpart which combines treated or untreated wastes from subparts A, B, or C of this part may be subject to Multiple Wastestream Subcategory effluent limitations representing the application of BCT set forth in paragraphs (b), (c), (d), or (e) of this section if the discharger agrees to the following conditions in its NPDES permit: (1) The discharger will meet the applicable Multiple Wastestream Subcategory limitations set forth in paragraphs (b), (c), (d) or (e) of this section; (2) The discharger will notify its NPDES permit writer at the time of renewal or modification of its permit, of its desire to be subject to the Multiple Waste Subcategory by submitting to the NPDES permit writer an initial certification statement as described in \\u00A7437.41(a);\r\n(3) The discharger will submit to its NPDES permitting authority a periodic certification statement as described in \\u00A7437.41(b) once a year; and (4) The discharger will maintain at the office of the facility and make available for inspection the on-site compliance paperwork as described in \\u00A7437.41(c)."},
      {"loc":"BAT",
        "ct_cfr_section":"437.44.a",
        "ct_notes":"(a) Except as provided in 40 CFR 125.30 through 125.32 or \\u00A7437.40(b), any existing facility subject to this subpart which combines treated or untreated wastes from subparts A, B, or C of this part may be subject to Multiple Wastestream Subcategory effluent limitations representing the application of BAT set forth in paragraphs (b), (c), (d), or (e) of this section if the discharger agrees to the following conditions in its NPDES permit: (1) The discharger will meet the applicable Multiple Wastestream Subcategory limitations set forth in paragraphs (b), (c), (d) or (e) of this section; (2) The discharger will notify its NPDES permit writer at the time of renewal or modification of its permit, of its desire to be subject to the Multiple Waste Subcategory by submitting to the NPDES permit writer an initial certification statement as described in \\u00A7437.41(a);\r\n(3) The discharger will submit to its NPDES permitting authority a periodic certification statement as described in \\u00A7437.41(b) once a year; and (4) The discharger will maintain at the office of the facility and make available for inspection the on-site compliance paperwork as described in \\u00A7437.41(c)."},
      {"loc":"NSPS",
        "ct_cfr_section":"437.45.a",
        "ct_notes":"(a) Except as provided in \\u00A7437.40(b), any new source subject to this subpart which combines treated or untreated wastes from subparts A, B, or C of this part may be subject to Multiple Wastestream Subcategory effluent limitations representing the application of NSPS set forth in paragraphs (b), (c), (d), or (e) of this section if the discharger agrees to the following conditions in its NPDES permit: (1) The discharger will meet the applicable Multiple Wastestream Subcategory limitations set forth in paragraphs (b), (c), (d) or (e) of this section; (2) The discharger will notify its NPDES permit writer at the time of submitting its application for permit, of its desire to be subject to the Multiple Waste Subcategory by submitting to the NPDES permit writer an initial certification statement as described in \\u00A7437.41(a); (3) The discharger will submit to its NPDES permitting authority a periodic certification statement as described in \\u00A7437.41(b) once a year; and (4) The discharger will maintain at the office of the facility and make available for inspection the on-site compliance paperwork as described in \\u00A7437.41(c)."},
      {"loc":"PSES",
        "ct_cfr_section":"437.46.a",
        "ct_notes":"(a) Except as provided in 40 CFR 403.7, \\u00A7403.13 or \\u00A7437.40(b), any new source subject to this subpart which combines treated or untreated wastes from subparts A, B, or C of this part may be subject to Multiple Wastestream Subcategory pretreatment standards representing the application of PSES set forth in paragraphs (b), (c), (d), or (e) of this section if the discharger agrees to the following conditions in its permit: (1) The discharger will meet the applicable Multiple Wastestream Subcategory standards set forth in paragraphs (b), (c), (d) or (e) of this section; (2) The discharger will notify its local control authority of its desire to be subject to the Multiple Waste Subcategory by submitting to the local control authority an initial certification statement as described in \\u00A7437.41(a); (3) The discharger will submit to its local control authority a periodic certification statement as described in \\u00A7437.41(b) once a year; and (4) The discharger will maintain at the office of the facility and make available for inspection the on-site compliance paperwork as described in \\u00A7437.41(c)."},
      {"loc":"PSNS",
        "ct_cfr_section":"437.47.a",
        "ct_notes":"(a) Except as provided in 40 CFR 403.7 or \\u00A7437.40(b), any new source subject to this subpart which combines treated or untreated wastes from subparts A, B, or C of this part may be subject to Multiple Wastestream Subcategory pretreatment standards representing the application of PSNS set forth in paragraphs (b), (c), (d), or (e) of this section if the discharger agrees to the following conditions in its permit: (1) The discharger will meet the applicable Multiple Wastestream Subcategory standards set forth in paragraphs (b), (c), (d) or (e) of this section; (2) The discharger will notify its local control authority at the time of submitting its application for an individual control mechanism or pretreatment agreement of its desire to be subject to Multiple Waste Subcategory by submitting to the local control authority an initial certification statement as described in \\u00A7437.41(a); (3) The discharger will submit to its local control authority a periodic certification statements as described in \\u00A7437.41(b) once a year; and (4) The discharger will maintain at the office of the facility and make available for inspection the on-site compliance paperwork as described in \\u00A7437.41(c)."},
      {"loc":"BPT",
        "ct_cfr_section":"439.12",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representating the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"439.13",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"439.14",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"439.15",
        "ct_notes":"(a) Any new source subject to this subpart must achieve the following standards. (c) Any new source subject to the provisions of this section that commenced discharging after November 21, 1988, and prior to November 20, 1998, must continue to achieve the standards specified for this section in the 1988 edition of 40 CFR part 439, until the expiration of the applicable time period specified in 40 CFR 122.29(d)(1), after which the source must achieve the standards specified in \\u00A7439.13 and \\u00A7439.14."},
      {"loc":"PSES",
        "ct_cfr_section":"439.16",
        "ct_notes":"(a) Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart must continue achieving the standards for cyanide specified in paragraph (c) of this section and must achieve the following standards by September 21, 2001:"},
      {"loc":"PSNS",
        "ct_cfr_section":"439.17",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart must achieve the same standards as specified in \\u00A7439.16."},
      {"loc":"BPT",
        "ct_cfr_section":"439.22",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"439.23",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"439.24",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"439.25",
        "ct_notes":"(a) Any new source subject to this subpart must achieve the following standards. (b) Any new source subject to the provisions of this section that commenced discharging after November 21, 1988, and prior to November 20, 1998, must continue to achieve the standards specified for this section in the 1988 edition of 40 CFR part 439, until the expiration of the applicable time period specified in 40 CFR 122.29(d)(1), after which the source must achieve the standards specified in \\u00A7439.23 and \\u00A7439.24."},
      {"loc":"NSPS",
        "ct_cfr_section":"439.25",
        "ct_notes":"(b) Any new source subject to the provisions of this section that commenced discharging after November 21, 1988, and prior to November 20, 1998, must continue to achieve the standards specified for this section in the 1988 edition of 40 CFR part 439, until the expiration of the applicable time period specified in 40 CFR 122.29(d)(1), after which the source must achieve the standards specified in \\u00A7\\u00A7439.23 and 439.24."},
      {"loc":"PSES",
        "ct_cfr_section":"439.26",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart must achieve the following standards by September 21, 2001:"},
      {"loc":"PSNS",
        "ct_cfr_section":"439.27",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"BPT",
        "ct_cfr_section":"439.32",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"},
      {"loc":"BCT",
        "ct_cfr_section":"439.33",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"439.34",
        "ct_notes":"(a) Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"439.35",
        "ct_notes":"(a) Any new source subject to this subpart must achieve the same standards as specified in \\u00A7439.15(a). (c)Any new source subject to the provisions of this section that commenced discharging after November 21, 1988, and prior to November 20, 1998, must continue to achieve the standards specified for this section in the 1988 edition of 40 CFR part 439, until the expiration of the applicable time period specified in 40 CFR 122.29(d)(1), after which the source must achieve the standards specified in \\u00A7439.33 and \\u00A7439.44."},
      {"loc":"PSES",
        "ct_cfr_section":"439.36",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart must continue achieving the standards for cyanide specified in paragraph (b) of this section and must achieve the standards specified in \\u00A7439.16(a) by September 21, 2001."},
      {"loc":"PSNS",
        "ct_cfr_section":"439.37",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart must achieve the same standards as specified in \\u00A7439.36."},
      {"loc":"BCT",
        "ct_cfr_section":"439.43",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BCT:"},
      {"loc":"BAT",
        "ct_cfr_section":"439.44",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BAT:"},
      {"loc":"NSPS",
        "ct_cfr_section":"439.45",
        "ct_notes":"(a) Any new source subject to this subpart must achieve the same standards as specified in \\u00A7439.25(a). (b) Any new source subject to the provisions of this section that commenced discharging after November 21, 1988, and prior to November 20, 1998, must continue to achieve the standards specified for this section in the 1988 edition of 40 CFR part 439, until the expiration of the applicable time period specified in 40 CFR 122.29(d)(1), after which the source must achieve the standards specified in \\u00A7439.43 and \\u00A7439.44."},
      {"loc":"PSES",
        "ct_cfr_section":"439.46",
        "ct_notes":"Except as provided in 40 CFR 403.7 and 403.13, any existing source subject to this subpart must achieve the following standards by September 21, 2001:"},
      {"loc":"PSNS",
        "ct_cfr_section":"439.47",
        "ct_notes":"Except as provided in 40 CFR 403.7, any new source subject to this subpart must achieve the following pretreatment standards:"},
      {"loc":"BPT",
        "ct_cfr_section":"439.52",
        "ct_notes":"Except as provided in 40 CFR 125.30 through 125.32, any existing point source subject to this subpart must achieve the following effluent limitations representing the application of BPT:"}];

    return queryInterface.bulkInsert({schema: "elg_search", tableName: 'ControlTechnologyNotes'}, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({schema: "elg_search", tableName: 'ControlTechnologyNotes'}, null, {}),
}
