module.exports = {
  up(queryInterface) {
    let records = [{"unit_code":1,
      "unit":"kg/kkg",
      "unit_desc":"\tKg/kkg (or pounds per 1,000 lb) of product",
      "unit_basis":"Quantity"},
      {"unit_code":2,
        "unit":"mg/L",
        "unit_desc":"Milligrams per liter",
        "unit_basis":"Concentration"},
      {"unit_code":3,
        "unit":"mg/L/kgal/ton",
        "unit_desc":"Milligrams per liter per kgal wastewater per ton of product",
        "unit_basis":"Concentration"},
      {"unit_code":4,
        "unit":"S.U.",
        "unit_desc":"Standard pH Units",
        "unit_basis":"Concentration"},
      {"unit_code":5,
        "unit":"mg/L/kgal/ton",
        "unit_desc":"Milligrams per liter per kgal wastewater per ton at all times",
        "unit_basis":"Concentration"},
      {"unit_code":6,
        "unit":"pg/L",
        "unit_desc":"Picograms per liter",
        "unit_basis":"Concentration"},
      {"unit_code":7,
        "unit":"g/kkg",
        "unit_desc":"Grams per 1,000 kg (g/kkg)",
        "unit_basis":"Quantity"},
      {"unit_code":8,
        "unit":"ug/L",
        "unit_desc":"Micrograms per liter",
        "unit_basis":"Concentration"},
      {"unit_code":9,
        "unit":"ng/L",
        "unit_desc":"Nanograms per liter",
        "unit_basis":"Concentration"},
      {"unit_code":1001,
        "unit":"mg/kg",
        "unit_desc":"Milligrams per kilogram",
        "unit_basis":"Quantity"},
      {"unit_code":1002,
        "unit":"mg/kg of product",
        "unit_desc":"millograms per kilogram of product",
        "unit_basis":"Quantity"},
      {"unit_code":1003,
        "unit":"mg/kg of cadmium",
        "unit_desc":"millograms per kilogram of cadmium",
        "unit_basis":"Quantity"},
      {"unit_code":1004,
        "unit":"mg/kg of nickel applied",
        "unit_desc":"millograms per kilogram of nickel applied",
        "unit_basis":"Quantity"},
      {"unit_code":1005,
        "unit":"mg/kg of cells produced",
        "unit_desc":"millograms per kilogram of cells produced",
        "unit_basis":"Quantity"},
      {"unit_code":1006,
        "unit":"mg/kg of cadmium powder produced",
        "unit_desc":"millograms per kilogram of cadmium powder produced",
        "unit_basis":"Quantity"},
      {"unit_code":1007,
        "unit":"mg/kg of silver powder produced",
        "unit_desc":"millograms per kilogram of silver powder produced",
        "unit_basis":"Quantity"},
      {"unit_code":1008,
        "unit":"mg/kg of cadmium used",
        "unit_desc":"millograms per kilogram of cadmium used",
        "unit_basis":"Quantity"},
      {"unit_code":1009,
        "unit":"mg/kg of nickel used",
        "unit_desc":"millograms per kilogram of nickel used",
        "unit_basis":"Quantity"},
      {"unit_code":1010,
        "unit":"lb/1000 Ducks",
        "unit_desc":"pounds per 1000 ducks",
        "unit_basis":"Quantity"},
      {"unit_code":1011,
        "unit":"kg/1000 ducks",
        "unit_desc":"kilograms per 1000 ducks",
        "unit_basis":"Quantity"},
      {"unit_code":1012,
        "unit":"count per 100 mL",
        "unit_desc":"count per 100 mL",
        "unit_basis":"Concentration"},
      {"unit_code":1013,
        "unit":"MPN/100 mL",
        "unit_desc":"MPN per 100 mL",
        "unit_basis":"Concentration"},
      {"unit_code":1014,
        "unit":"Reserved",
        "unit_desc":"Reserved",
        "unit_basis":null},
      {"unit_code":1015,
        "unit":"mg/kg of lead used",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1016,
        "unit":"mg/kg of lead in trucked batteries",
        "unit_desc":"milligrams per kilogram of lead in trucked batteries",
        "unit_basis":null},
      {"unit_code":1017,
        "unit":"mg/kg of lead",
        "unit_desc":"milligrams per kilogram of lead",
        "unit_basis":null},
      {"unit_code":1018,
        "unit":"mg/kg of iron disulfide",
        "unit_desc":"milligrams per kilogram of iron disulfide",
        "unit_basis":null},
      {"unit_code":1019,
        "unit":"mg/kg of silver processed",
        "unit_desc":"milligrams per kilogram of silver processed",
        "unit_basis":null},
      {"unit_code":1020,
        "unit":"mg/kg of zinc",
        "unit_desc":"milligrams per kilogram of zinc",
        "unit_basis":null},
      {"unit_code":1021,
        "unit":"mg/kg of zinc deposited",
        "unit_desc":"milligrams per kilogram of zinc deposited",
        "unit_basis":null},
      {"unit_code":1022,
        "unit":"mg/kg of silver applied",
        "unit_desc":"milligrams per kilogram of silver applied",
        "unit_basis":null},
      {"unit_code":1023,
        "unit":"mg/kg of silver peroxide processed",
        "unit_desc":"milligrams per kilogram of silver peroxide processed",
        "unit_basis":null},
      {"unit_code":1024,
        "unit":"mg/kg of silver powder processed",
        "unit_desc":"milligrams per kilogram of silver powder processed",
        "unit_basis":null},
      {"unit_code":1025,
        "unit":"mg/kg of silver peroxide produced",
        "unit_desc":"milligrams per kilogram of silver peroxide produced",
        "unit_basis":null},
      {"unit_code":1026,
        "unit":"N/A",
        "unit_desc":"Not applicable",
        "unit_basis":null},
      {"unit_code":1027,
        "unit":"kg/day",
        "unit_desc":"kilograms per day",
        "unit_basis":"Quantity"},
      {"unit_code":1028,
        "unit":"mg/off-kg of aluminum rolled with neat oils",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1029,
        "unit":"kg/1000 cubic m of product",
        "unit_desc":"kilograms per 1,000 cubic meters of product",
        "unit_basis":null},
      {"unit_code":1030,
        "unit":"kg/cubic m of production",
        "unit_desc":"kilograms per cubic meter of production",
        "unit_basis":null},
      {"unit_code":1031,
        "unit":"mL/L",
        "unit_desc":"millileter per liter",
        "unit_basis":null},
      {"unit_code":1032,
        "unit":"g/kg LWK",
        "unit_desc":"gram per kilogram of live weight killed",
        "unit_basis":null},
      {"unit_code":1033,
        "unit":"g/kg ELWK",
        "unit_desc":"gram per kilogram of equivalent live weight killed",
        "unit_basis":null},
      {"unit_code":1034,
        "unit":"g/kg",
        "unit_desc":"gram per kilogram of product/finished product",
        "unit_basis":null},
      {"unit_code":1035,
        "unit":"g/kg raw material",
        "unit_desc":"gram per kilogram of raw material",
        "unit_basis":null},
      {"unit_code":1036,
        "unit":"mg/sq-m operation",
        "unit_desc":"milligram per square meter of operation",
        "unit_basis":null},
      {"unit_code":1037,
        "unit":"g/sq-m",
        "unit_desc":"grams per square meter of product",
        "unit_basis":null},
      {"unit_code":1038,
        "unit":"g/kkg furnace pull",
        "unit_desc":"grams per 1,000 kilograms of furnace pull",
        "unit_basis":null},
      {"unit_code":1039,
        "unit":"g/kkg product frosted",
        "unit_desc":"grams per 1,000 kilograms of product frosted",
        "unit_basis":null},
      {"unit_code":1040,
        "unit":"cm",
        "unit_desc":"centimeters",
        "unit_basis":null},
      {"unit_code":1041,
        "unit":"mg/kkg",
        "unit_desc":"milligrams per 1,000 kilograms",
        "unit_basis":null},
      {"unit_code":1042,
        "unit":"kg/Mwh",
        "unit_desc":"kilograms per mega watt hour",
        "unit_basis":null},
      {"unit_code":1043,
        "unit":"kg/kkg processed",
        "unit_desc":"kilograms per 1,000 kilograms processed",
        "unit_basis":null},
      {"unit_code":1044,
        "unit":"mg/kkg of lead bullion produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1045,
        "unit":"mg/kg of casting production",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1046,
        "unit":"mg/kg of product recovered from electrolytic slimes processing",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1047,
        "unit":"mg/kg of cathode copper production",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1048,
        "unit":"mg/kg of copper cast",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1049,
        "unit":"mg/kg of aluminum cast",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1050,
        "unit":"mg/kg of aluminum delacquered",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1051,
        "unit":"mg/kg of aluminum demagged",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1052,
        "unit":"mg/kg of dross washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1053,
        "unit":"mg/kg of aluminum scrap screened and milled",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1054,
        "unit":"mg/kg of aluminum scrap dried",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1055,
        "unit":"Kg/kg magnesium removed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1056,
        "unit":"mg/kg of aluminum product from rod casting",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1057,
        "unit":"mg/kg of aluminum product from stationary casting or shot casting",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1058,
        "unit":"mg/kg of aluminum product from direct chill casting",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1059,
        "unit":"mg/kg of aluminum produced from electrolytic reduction",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1060,
        "unit":"mg/kg of cryolite recovered",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1061,
        "unit":"mg/kg of anodes baked",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1062,
        "unit":"mg/kg of paste produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1063,
        "unit":"mg/kg of anodes cast",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1064,
        "unit":"mg/kg of 100 pct sulfuric acid capacity",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1065,
        "unit":"mg/kg of tungstic acid (as W) produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1066,
        "unit":"mg/kg of sodium tungstate (as W) produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1067,
        "unit":"mg/kg of ammonium tungstate (as W) produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1068,
        "unit":"mg/kg of calcium tungstate (as W) produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1069,
        "unit":"mg/kg of ammonium paratungstate (as W) produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1070,
        "unit":"mg/kg of tungstic oxide (as W) produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1071,
        "unit":"mg/kg of tungsten metal produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1072,
        "unit":"mg/kg of concentrate digested",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1073,
        "unit":"mg/kg of tantalum salt dried",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1074,
        "unit":"mg/kg of columbium-tantalum oxide dried",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1075,
        "unit":"mg/kg of tantalum salt reduced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1076,
        "unit":"mg/kg of tantalum powder washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1077,
        "unit":"mg/kg of columbium or tantalum cast or consolidated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1078,
        "unit":"mg/troy ounce of silver from film stripping",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1079,
        "unit":"mg/troy ounce of silver from precipitation and filtration of film stripping solutions",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1080,
        "unit":"mg/troy ounce of silver precipitated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1081,
        "unit":"mg/troy ounce of silver from precipitation and filtration of photographic solutions",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1082,
        "unit":"mg/troy ounce of silver from electrolytic refining",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1083,
        "unit":"mg/troy ounce of silver roasted, smelted, or dried",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1084,
        "unit":"mg/troy ounce of silver produced from leaching",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1085,
        "unit":"mg/troy ounce of silver produced from leaching or silver precipitated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1086,
        "unit":"mg/troy ounce of silver production",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1087,
        "unit":"mg/kg of lead scrap produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1088,
        "unit":"mg/kg of lead processed through desulfurization",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1089,
        "unit":"mg/kg of lead cast",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1090,
        "unit":"mg/kg of antimony contained in sodium antimonate product",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1091,
        "unit":"mg/kg of antimony metal produced by electrowinning",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1092,
        "unit":"mg/kg of beryllium carbonate produced from bertrandite ore as beryllium",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1093,
        "unit":"mg/kg of beryllium carbonate produced from beryl ore as beryllium",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1094,
        "unit":"mg/kg of beryllium carbonate produced as beryllium",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1095,
        "unit":"mg/kg of beryllium hydroxide produced as beryllium",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1096,
        "unit":"mg/kg of beryllium oxide produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1097,
        "unit":"mg/kg of beryllium hydroxide produced from scrap and residues as beryllium",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1098,
        "unit":"mg/kg of beryllium pebbles produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1099,
        "unit":"mg/kg of beryllium scrap chips treated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1100,
        "unit":"mg/kg of beryl ore processed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1101,
        "unit":"mg/kg of bertrandite ore processed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1102,
        "unit":"mg/kg of germanium chlorinated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1103,
        "unit":"mg/kg of germanium hydrolyzed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1104,
        "unit":"mg/kg of germanium washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1105,
        "unit":"mg/kg of gallium hydrolyzed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1106,
        "unit":"mg/kg of gallium produced by solvent extraction",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1107,
        "unit":"mg/kg of indium metal produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1108,
        "unit":"mg/kg of cathode indium produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1109,
        "unit":"mg/kg of mercury produced from batteries",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1110,
        "unit":"mg/kg of mercury washed and rinsed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1111,
        "unit":"mg/kg of mercury processed through furnace",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1112,
        "unit":"mg/kg of molybdenum sulfide leached",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1113,
        "unit":"mg/kg of molybdenum sulfide roasted",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1114,
        "unit":"mg/kg of molybdenum contained in molybdic oxide leached",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1115,
        "unit":"mg/kg of molybdenum metal powder produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1116,
        "unit":"mg/kg of technical grade molybdenum plus vanadium plus pure grade molybdenum produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1117,
        "unit":"mg/kg of vanadium produced by decomposition",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1118,
        "unit":"mg/kg of molybdenum produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1119,
        "unit":"mg/kg of copper, nickel, and cobalt in the crushed raw material",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1120,
        "unit":"mg/kg of nickel powder washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1121,
        "unit":"mg/kg of nickel produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1122,
        "unit":"mg/kg of cobalt produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1123,
        "unit":"mg/kg of slag input to reclaim process",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1124,
        "unit":"mg/kg of acid reclaim nickel produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1125,
        "unit":"mg/troy ounce of gold and silver smelted",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1126,
        "unit":"mg/troy ounce of silver reduced in solution",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1127,
        "unit":"mg/troy ounce of gold refined electrolytically",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1128,
        "unit":"mg/troy ounce of silver in electrolyte produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1129,
        "unit":"mg/kg of mercury condensed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1130,
        "unit":"mg/troy ounce of precious metals, including silver, incinerated or smelted",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1131,
        "unit":"mg/troy ounce of precious metal in the granulated raw material",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1132,
        "unit":"mg/liter of spent plating solution used as a raw material",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1133,
        "unit":"mg/troy ounce of gold produced by cyanide stripping",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1134,
        "unit":"mg/troy ounce of precious metals, including silver, produced in refinery",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1135,
        "unit":"mg/troy ounce of gold produced by solvent extraction",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1136,
        "unit":"mg/troy ounce of gold produced by electrolysis",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1137,
        "unit":"mg/troy ounce of gold precipitated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1138,
        "unit":"mg/troy ounce of platinum precipitated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1139,
        "unit":"mg/troy ounce of palladium precipitated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1140,
        "unit":"mg/troy ounce of other platinum group metals precipitated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1141,
        "unit":"mg/troy ounce of gold contained in PGC product",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1142,
        "unit":"mg/kg of mischmetal produced from wet rare earth chlorides",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1143,
        "unit":"mg/kg of total mischmetal produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1144,
        "unit":"mg/kg of tantalum powder produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1145,
        "unit":"mg/kg of tantalum powder produced from leaching",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1146,
        "unit":"mg/kg of equivalent pure tantalum powder produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1147,
        "unit":"mg/kg of crude tapped tin metal produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1148,
        "unit":"mg/kg of dealuminized scrap produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1149,
        "unit":"mg/kg of neutralized, dewatered tin mud produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1150,
        "unit":"mg/kg of tin hydroxide washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1151,
        "unit":"mg/kg of cathode tin produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1152,
        "unit":"mg/kg of MSW scrap used as raw material",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1153,
        "unit":"mg/kg of tin metal recovered from scrap",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1154,
        "unit":"mg/kg of tin metal recovered from plating solutions and sludges",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1155,
        "unit":"mg/kg of tin metal produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1156,
        "unit":"mg/kg of TiCl4 produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1157,
        "unit":"mg/kg of of TiCl4 handled",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1158,
        "unit":"mg/kg of titanium pickled",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1159,
        "unit":"mg/kg of scrap milled",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1160,
        "unit":"mg/kg of scrap washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1161,
        "unit":"mg/kg of titanium cast",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1162,
        "unit":"mg/kg of tungsten scrap washed",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1163,
        "unit":"mg/kg of tungsten produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1164,
        "unit":"mg/kg of synthetic scheelite produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1165,
        "unit":"mg/kg of tungsten carbide scrap leached",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1166,
        "unit":"mg/kg of tungsten carbide produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1167,
        "unit":"mg/kg of cobalt produced from cobalt sludge",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1168,
        "unit":"mg/kg of uranium processed in the refinery",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1169,
        "unit":"mg/kg of uranium trioxide produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1170,
        "unit":"mg/kg of uranium tetrafluoride produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1171,
        "unit":"mg/kg of uranium produced by magnesium reduction",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1172,
        "unit":"mg/kg of zirconium dioxide and hafnium dioxide produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1173,
        "unit":"mg/kg of zirconium and hafnium produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1174,
        "unit":"mg/kg of pure zirconium produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1175,
        "unit":"mg/kg of zirconium contained in alloys produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1176,
        "unit":"mg/kg of zinc processed through leaching",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1177,
        "unit":"mg/kg of cathode zinc produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1178,
        "unit":"mg/kg of concentrate leached",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1179,
        "unit":"mg/kg of zinc reduced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1180,
        "unit":"mg/kg of zinc cast",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1181,
        "unit":"mg/kkg of sinter production",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1182,
        "unit":"mg/kkg of blast furnace lead bullion produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1183,
        "unit":"mg/kkg of slag, speiss, or matte granulated",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1184,
        "unit":"mg/kkg of dross reverberatory furnace production",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1185,
        "unit":"mg/kkg of hard lead produced",
        "unit_desc":null,
        "unit_basis":null},
      {"unit_code":1186,
        "unit":"mg/off-kg of copper",
        "unit_desc":"milligrams per of kilogram of copper",
        "unit_basis":null},
      {"unit_code":1187,
        "unit":"\tmg/kg of lead produced from smelting",
        "unit_desc":"milligrams per kilogram of lead produced from smelting",
        "unit_basis":null},
      {"unit_code":1188,
        "unit":"\tmg/kg of lead produced from refining",
        "unit_desc":"milligrams per kilogram of lead produced from refining",
        "unit_basis":null},
      {"unit_code":1189,
        "unit":"degrees C",
        "unit_desc":"degrees Celsius",
        "unit_basis":null},
      {"unit_code":1190,
        "unit":"mg/kg of molybdenum and vanadium produced",
        "unit_desc":"milligrams per kilogram of molybdenum and vanadium produced",
        "unit_basis":null},
      {"unit_code":1191,
        "unit":"mg/troy ounce of precious metals produced",
        "unit_desc":"milligrams per troy ounce of precious metals produced",
        "unit_basis":null},
      {"unit_code":1192,
        "unit":"% removal",
        "unit_desc":"percent removal",
        "unit_basis":null},
      {"unit_code":1193,
        "unit":"mg/kg of titanium produced",
        "unit_desc":"milligrams per kilogram of titanium produced",
        "unit_basis":null},
      {"unit_code":1194,
        "unit":"pCi/L",
        "unit_desc":"Picocuries per liter",
        "unit_basis":null}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "LimitationUnit" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "LimitationUnit"
  }, null, {})
};
