module.exports = {
  up(queryInterface) {
    let records = [{"limit_duration_code":1,
      "limit_duration_description":"Maximum for any 1 day",
      "stat_base_type":"Maximum"},
      {"limit_duration_code":2,
        "limit_duration_description":"Average of daily values for 30 consecutive days",
        "stat_base_type":"Average"},
      {"limit_duration_code":3,
        "limit_duration_description":"Annual average",
        "stat_base_type":"Average"},
      {"limit_duration_code":4,
        "limit_duration_description":"Monthly average",
        "stat_base_type":"Average"},
      {"limit_duration_code":5,
        "limit_duration_description":"Maximum",
        "stat_base_type":"Maximum"},
      {"limit_duration_code":6,
        "limit_duration_description":"Average",
        "stat_base_type":"Average"},
      {"limit_duration_code":1001,
        "limit_duration_description":"Maximum for monthly average",
        "stat_base_type":"Maximum"},
      {"limit_duration_code":1002,
        "limit_duration_description":"Maximum daily",
        "stat_base_type":"Maximum"},
      {"limit_duration_code":1003,
        "limit_duration_description":"Maximum monthly average",
        "stat_base_type":"Maximum"},
      {"limit_duration_code":1004,
        "limit_duration_description":"Reserved",
        "stat_base_type":null},
      {"limit_duration_code":1005,
        "limit_duration_description":"Maximum for any time",
        "stat_base_type":"Maximum"},
      {"limit_duration_code":1006,
        "limit_duration_description":"N/A",
        "stat_base_type":null},
      {"limit_duration_code":1007,
        "limit_duration_description":"TSS NSPS for any time",
        "stat_base_type":null},
      {"limit_duration_code":1008,
        "limit_duration_description":"NSPS for any time",
        "stat_base_type":null},
      {"limit_duration_code":1009,
        "limit_duration_description":"At all times",
        "stat_base_type":null},
      {"limit_duration_code":1010,
        "limit_duration_description":"Average of daily values for 4 consecutive monitoring days",
        "stat_base_type":"Average"},
      {"limit_duration_code":1011,
        "limit_duration_description":"Instantaneous maximum",
        "stat_base_type":"Maximum"},
      {"limit_duration_code":1012,
        "limit_duration_description":"Weekly average",
        "stat_base_type":"Average"},
      {"limit_duration_code":1013,
        "limit_duration_description":"Minimum for any 1 day",
        "stat_base_type":"Minimum"},
      {"limit_duration_code":1014,
        "limit_duration_description":"Minimum 96-hour LC50",
        "stat_base_type":"Minimum"}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "LimitationDuration" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "LimitationDuration"
  }, null, {})
};
