module.exports = {
  up(queryInterface) {
    /*
    -	407: Canned and Preserved Fruits and Vegetables
    -	412: Concentrated Animal Feeding Operations
    -	413: Electroplating
    -	417: Soap and Detergent Mfr
    -	423: Steam Electric Generating
    -	427: Asbestos Mfr
    -	432: Meat and Poultry Products
    -	433: Metal Finishing
    -	437: Centralized Waste Treatment
    -	438: Metal Products and Machinery
    -	439: Pharmaceutical
    -	444: Waste Combustors
    -	461: Battery Manufacturing
    -	469: Electrical and Electronic Components
     */
    let showThese = [407, 417]; //staging and production
    if (process.env.NODE_ENV === 'local' || process.env.NODE_ENV === 'development') {
      showThese = [407, 412, 413, 417, 423, 427, 432, 433, 437, 438, 439, 444, 461, 469]; //dev and local
    }

    let records = [{"psc_code":405,
      "cfr_part":"405",
      "psc_name":"Dairy products processing",
      "cfr_notes":null,
      "narrative_history":null,
      "source_id":null,
      "initial_promulgation_date":1974},
      {"psc_code":406,
        "cfr_part":"406",
        "psc_name":"Grain mills",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":407,
        "cfr_part":"407",
        "psc_name":"Canned and preserved fruits and vegetables processing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":408,
        "cfr_part":"408",
        "psc_name":"Canned and preserved seafood processing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":409,
        "cfr_part":"409",
        "psc_name":"Sugar processing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":410,
        "cfr_part":"410",
        "psc_name":"Textile mills",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":411,
        "cfr_part":"411",
        "psc_name":"Cement manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":412,
        "cfr_part":"412",
        "psc_name":"CAFOs",
        "cfr_notes":"Includes BMPs and additional measures for some subcategories.",
        "narrative_history":null,
        "source_id":27,
        "initial_promulgation_date":1974},
      {"psc_code":413,
        "cfr_part":"413",
        "psc_name":"Electroplating",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":414,
        "cfr_part":"414",
        "psc_name":"Organic chemicals, plastics and synthetic fibers",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1987},
      {"psc_code":415,
        "cfr_part":"415",
        "psc_name":"Inorganic chemicals manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1982},
      {"psc_code":417,
        "cfr_part":"417",
        "psc_name":"Soap and detergent manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":418,
        "cfr_part":"418",
        "psc_name":"Fertilizer manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":419,
        "cfr_part":"419",
        "psc_name":"Petroleum refining",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":420,
        "cfr_part":"420",
        "psc_name":"Iron and steel manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":421,
        "cfr_part":"421",
        "psc_name":"Nonferrous metals manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":422,
        "cfr_part":"422",
        "psc_name":"Phosphate manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":423,
        "cfr_part":"423",
        "psc_name":"Steam Electric Power Generating",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":1,
        "initial_promulgation_date":1974},
      {"psc_code":424,
        "cfr_part":"424",
        "psc_name":"Ferroalloy manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":425,
        "cfr_part":"425",
        "psc_name":"Leather tanning and finishing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1982},
      {"psc_code":426,
        "cfr_part":"426",
        "psc_name":"Glass manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":427,
        "cfr_part":"427",
        "psc_name":"Asbestos manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":428,
        "cfr_part":"428",
        "psc_name":"Rubber Manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":429,
        "cfr_part":"429",
        "psc_name":"Timber products processing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":430,
        "cfr_part":"430",
        "psc_name":"Pulp, Paper, and Paperboard",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":2,
        "initial_promulgation_date":1974},
      {"psc_code":432,
        "cfr_part":"432",
        "psc_name":"Meat and Poultry Products",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1974},
      {"psc_code":433,
        "cfr_part":"433",
        "psc_name":"Metal Finishing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1983},
      {"psc_code":434,
        "cfr_part":"434",
        "psc_name":"Coal mining",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":435,
        "cfr_part":"435",
        "psc_name":"Oil & Gas Extraction",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":436,
        "cfr_part":"436",
        "psc_name":"Mineral Mining and Processing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":437,
        "cfr_part":"437",
        "psc_name":"Centralized Waste Treatment",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2000},
      {"psc_code":438,
        "cfr_part":"438",
        "psc_name":"Metal Products and Machinery",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2003},
      {"psc_code":439,
        "cfr_part":"439",
        "psc_name":"Pharmaceutical manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":440,
        "cfr_part":"440",
        "psc_name":"Ore mining and dressing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":441,
        "cfr_part":"441",
        "psc_name":"Dental office",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":0,
        "initial_promulgation_date":2017},
      {"psc_code":442,
        "cfr_part":"442",
        "psc_name":"Transportation Equipment Cleaning",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2000},
      {"psc_code":443,
        "cfr_part":"443",
        "psc_name":"Paving and roofing materials (tars and asphalt)",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":444,
        "cfr_part":"444",
        "psc_name":"Waste combustors",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2000},
      {"psc_code":445,
        "cfr_part":"445",
        "psc_name":"Landfills",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2000},
      {"psc_code":446,
        "cfr_part":"446",
        "psc_name":"Paint formulating",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":447,
        "cfr_part":"447",
        "psc_name":"Ink formulating",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1975},
      {"psc_code":449,
        "cfr_part":"449",
        "psc_name":"Airport Deicing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2012},
      {"psc_code":450,
        "cfr_part":"450",
        "psc_name":"Construction and Development",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2009},
      {"psc_code":451,
        "cfr_part":"451",
        "psc_name":"Concentrated Aquatic Animal Production",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":2004},
      {"psc_code":454,
        "cfr_part":"454",
        "psc_name":"Gum and wood chemicals manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":455,
        "cfr_part":"455",
        "psc_name":"Pesticide chemicals",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1978},
      {"psc_code":457,
        "cfr_part":"457",
        "psc_name":"Explosives manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":458,
        "cfr_part":"458",
        "psc_name":"Carbon black manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":459,
        "cfr_part":"459",
        "psc_name":"Photographic",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":460,
        "cfr_part":"460",
        "psc_name":"Hospital",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1976},
      {"psc_code":461,
        "cfr_part":"461",
        "psc_name":"Battery manufacturing",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":26,
        "initial_promulgation_date":1984},
      {"psc_code":463,
        "cfr_part":"463",
        "psc_name":"Plastics molding and forming",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1984},
      {"psc_code":464,
        "cfr_part":"464",
        "psc_name":"Metal molding and casting (foundries)",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1985},
      {"psc_code":465,
        "cfr_part":"465",
        "psc_name":"Coil coating",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1982},
      {"psc_code":466,
        "cfr_part":"466",
        "psc_name":"Porcelain Enameling",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1982},
      {"psc_code":467,
        "cfr_part":"467",
        "psc_name":"Aluminum forming",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1983},
      {"psc_code":468,
        "cfr_part":"468",
        "psc_name":"Copper forming",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1983},
      {"psc_code":469,
        "cfr_part":"469",
        "psc_name":"Electrical and electronic components",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1983},
      {"psc_code":471,
        "cfr_part":"471",
        "psc_name":"Nonferrous metals forming and metal powders",
        "cfr_notes":null,
        "narrative_history":null,
        "source_id":null,
        "initial_promulgation_date":1985}];

    records.forEach(function(record) {
      record.IncludeInSearchTool = showThese.includes(record.psc_code);
    });

    return queryInterface.bulkInsert({schema: "elg_search", tableName: 'PointSourceCategory'}, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({schema: "elg_search", tableName: 'PointSourceCategory'}, null, {}),
};
