module.exports = {
  up(queryInterface) {
    let records = [{"source_id":1,"source_title":"PART 423-STEAM ELECTRIC POWER GENERATING POINT SOURCE CATEGORY (eCFR)"},
      {"source_id":2,"source_title":"PART 430-THE PULP, PAPER, AND PAPERBOARD POINT SOURCE CATEGORY"},
      {"source_id":5,"source_title":"Guidelines Establishing Test Procedures for the Analysis of Pollutants Under the Clean Water Act; Analysis and Sampling Procedures"},
      {"source_id":7,"source_title":"Effluent Limitations Guidelines, Pretreatment Standards and New Source Performance Standards Under Clean Water Act, Steam Electric Power Generating Point Source Category"},
      {"source_id":8,"source_title":"Amendment to BPT Variance Clause (Clarification)"},
      {"source_id":9,"source_title":"Amendment to BPT Variance Clause"},
      {"source_id":10,"source_title":"Part 423 - Steam Electric Power Generating Point Source Category Pretreatment Standards for Existing Sources"},
      {"source_id":11,"source_title":"Steam Electric Power Generating Point Source Category"},
      {"source_id":12,"source_title":"PART 423-STEAM ELECTRIC POWER GENERATING POINT SOURCE CATEGORY"},
      {"source_id":13,"source_title":"EFFLUENT LIMITATIONS GUIDELINES AND STANDARDS FOR THE STEAM ELECTRIC POWER GENERATING POINT SOURCE CATEGORY"},
      {"source_id":14,"source_title":"Effluent Limitations Guidelines and Standards for the Steam Electric Power Generating Point Source Category"},
      {"source_id":15,"source_title":"National Emission Standards for Hazardous Air Pollutants for Source Category: Pulp and Paper Production; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards: Pulp, Paper, and Paperboard Category"},
      {"source_id":16,"source_title":"National Emission Standards for Hazardous Air Pollutants for Source Category: Pulp and Paper Production; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards: Pulp, Paper, and Paperboard Category; Correction"},
      {"source_id":17,"source_title":"Approval and Promulgation of Air Quality Implementation Plans; Texas; Revised Format for Materials Being Incorporated by Reference"},
      {"source_id":18,"source_title":"Computation of Time"},
      {"source_id":19,"source_title":"Effluent Limitations Guidelines and Standards for the Bleached Papergrade Kraft and Soda Subcategory of the Pulp, Paper, and Paperboard Point Source Category"},
      {"source_id":20,"source_title":"Guidelines Establishing Test Procedures for the Analysis of Pollutants Under the Clean Water Act; National Primary Drinking Water Regulations; and National Secondary Drinking Water Regulations; Analysis and Sampling Procedures"},
      {"source_id":21,"source_title":"Guidelines Establishing Test Procedures for the Analysis of Pollutants Under the Clean Water Act; Analysis and Sampling Procedures"},
      {"source_id":22,"source_title":"Amendments to the Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards for the Bleached Papergrade Kraft and Soda Subcategory of the Pulp, Paper, and Paperboard Point Source Category"},
      {"source_id":23,"source_title":null},
      {"source_id":24,"source_title":"Supplemental Technical Development Document for Effluent Limitations Guidelines and Standards for the Pulp, Paper, and Paperboard Category; Subpart B (Bleached Papergrade Kraft\r\nand Soda) and Subpart E (Papergrade Sulfite)"},
      {"source_id":25,"source_title":"Technical Development Document for the Effluent Limitations Guidelines and Standards for the Steam Electric Power Generating Point Source Category (2015)"},
      {"source_id":26,"source_title":"PART 461-BATTERY MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":27,"source_title":"PART 412-CONCENTRATED ANIMAL FEEDING OPERATIONS (CAFO) POINT SOURCE CATEGORY"},
      {"source_id":28,"source_title":"National Pollutant Discharge Elimination System Permit Regulation and Effluent Limitation Guidelines and Standards for Concentrated Animal Feeding Operations (CAFOs)"},
      {"source_id":29,"source_title":"Revised National Pollutant Discharge Elimination System Permit Regulation and Effluent Limitations Guidelines for Concentrated Animal Feeding Operations in Response to the Waterkeeper"},
      {"source_id":30,"source_title":null},
      {"source_id":31,"source_title":null},
      {"source_id":32,"source_title":"Battery Manufacturing Point Source Category; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":33,"source_title":"Battery Manufacturing Point Source Category, Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":34,"source_title":"Water Pollution, Battery Manufacturing Point-Source Category Effluent Limitations Guidelines, Pretreatment Standards and New Source Performance Standards"},
      {"source_id":35,"source_title":"Battery Manufacturing Point Source Category, Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":36,"source_title":"Development Document for Final Effluent Limitations Guidelines, New Source Performance Standards, and Pretreatment Standards for the Steam Electric Point Source Category (1982)"},
      {"source_id":37,"source_title":"Development Document for Effluent Limitations Guidelines, New Source Performance Standards and Pretreatment Standards for the Organic Chemicals, Plastics and Synthetic Fibers Point Source Category; Volume I"},
      {"source_id":38,"source_title":"Development Document for Effluent Limitations Guidelines, New Source Performance Standards and Pretreatment Standards for the Organic Chemicals, Plastics and Synthetic Fibers Point Source Category; Volume II"},
      {"source_id":39,"source_title":"Supplement to the Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Organic Chemicals, Plastics and Synthetic Fibers Point Source Category"},
      {"source_id":40,"source_title":"Organic Chemicals and Plastics and Synthetic Fibers Category Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":41,"source_title":"Organic Chemicals, Plastics and Synthetic Fibers Category Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":42,"source_title":"Organic Chemicals, Plastics and Synthetic Fibers Category; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":43,"source_title":"Organic Chemicals, Plastics and Synthetic Fibers Category Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":44,"source_title":"Organic Chemicals, Plastics and Synthetic Fibers Category; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":49,"source_title":"Steam Electric Power Generating Point Source Category; Effluent Limitations Guidelines, Pretreatment Standards and New Source Performance Standards"},
      {"source_id":50,"source_title":"Reporting and Recordkeeping Requirements; OMB Approval; Technical Amendments"},
      {"source_id":52,"source_title":"Effluent Limitations Guidelines and \nStandards for the Steam Electric \nPower Generating Point Source\nCategory"},
      {"source_id":53,"source_title":"Postponement of Certain Compliance\nDates for the Effluent Limitations\nGuidelines and Standards for the\nSteam Electric Power Generating Point\nSource Category"},
      {"source_id":54,"source_title":"National Pollutant Discharge Elimination System Permit Regulation and Effluent Limitation Guidelines and Standards for Concentrated Animal Feeding Operations (CAFOs)"},
      {"source_id":55,"source_title":"Revised Compliance Dates for National Pollutant Discharge Elimination System Permit Regulation and Effluent Limitation Guidelines for Concentrated Animal Feeding Operations"},
      {"source_id":56,"source_title":"Revised Compliance Dates Under the National Pollutant Discharge Elimination System Permit Regulations and Effluent Limitations Guidelines and Standards for Concentrated Animal Feeding Operations"},
      {"source_id":57,"source_title":"Revised National Pollutant Discharge Elimination System Permit Regulation and Effluent Limitations Guidelines for Concentrated Animal Feeding Operations in Response to the Waterkeeper Decision"},
      {"source_id":58,"source_title":"Development Document for Effluent Limitations Guidelines, New Source Performance Standards and Pretreatment Standards for the Concentrated Animal Feeding Operations Point Source Category (1974)"},
      {"source_id":59,"source_title":"Development Document for the Final Revisions to the National Pollutant Discharge Elimination System Regulation and the Effluent Guidelines for Concentrated Animal Feeding Operations (2002)"},
      {"source_id":60,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Steam Electric Power Generating Point Source Category (1974)"},
      {"source_id":61,"source_title":"Development Document for the Final Effluent Limitations Guidelines and Standards for the Metal Products and Machinery Point Source Category (2003)"},
      {"source_id":62,"source_title":"PART 438-METAL PRODUCTS AND MACHINERY POINT SOURCE CATEGORY"},
      {"source_id":63,"source_title":"Effluent Limitations Guidelines and New Source Performance Standards for the Metal Products and Machinery Point Source Category"},
      {"source_id":64,"source_title":"Development Document for Final Effluent Limitations Guidelines and Standards for the Pharmaceutical Manufacturing Point Source Category"},
      {"source_id":65,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Centrazlied Waste Treatment Industry - Final"},
      {"source_id":66,"source_title":"(Phase 1) Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Electrical and Electronic Components Point Source Category"},
      {"source_id":67,"source_title":"(Phase 2) Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Electrical and Electronic Components Point Source Category"},
      {"source_id":68,"source_title":"Development Document for Effluent Limitations Guidelines New Source Performance Standards for the Metal Finishing Point Source Category"},
      {"source_id":69,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Pulp, Paper, and Paperboard and the Builders' Paper and Board Mills Point Source Categories"},
      {"source_id":70,"source_title":"Permit Guidance Document Pulp, Paper and Paperboard Manufacturing Point Source Category"},
      {"source_id":71,"source_title":"Pulp, Paper, and Paperboard Builders' Paper and Board Mills Point Source Categories; Best Conventional Pollutant Control Effluent Limitations Guidelines\r\nGuidelines"},
      {"source_id":72,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Leather Tanning and Finishing Point Source Category"},
      {"source_id":73,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Aluminum Forming Point Source Category Volume II"},
      {"source_id":74,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Plywood, Hardboard, and Wood Preserving Segment of the Timber Products Processing Point Source Category (1974)"},
      {"source_id":75,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Timber Products Point Source Category (1981)"},
      {"source_id":76,"source_title":"Development Document for Effluent Limitations Guidelines and Standards of Performance - Asbestos Manufacturing"},
      {"source_id":77,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Soap and Detergent Manufacturing Point Source Category"},
      {"source_id":78,"source_title":"Technical Development Document for the Final Effluent Limitations Guidelines and Standards for the Meat and Poultry Products Point Source Category (2004)"},
      {"source_id":79,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Other Non-Fertilizer Phosphate Chemicals Segment of the Phosphate Manufacturing Point Source Category"},
      {"source_id":80,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Red Meat Processing Segment of the Meat Product and Rendering Point Source Category (1974)"},
      {"source_id":81,"source_title":"Development Document for Proposed Effluent Limitations Guidelines and New Source Performance Standards for the Processor Segment of the Meat Products Point Source Category (1974)"},
      {"source_id":82,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Renderer Segment of the Meat Products and Rendering Processing Point Source Category (1975)"},
      {"source_id":83,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Fabricated and Reclaimed Rubber Segment of the Rubber Processing Point Source Category"},
      {"source_id":84,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Tire and Synthetic Segment of the Rubber Processing Point Source Category"},
      {"source_id":85,"source_title":"PART 428-RUBBER MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":86,"source_title":"Development Document for Interim Final and Proposed Effluent Limitations Guidelines and New Source Performance Standards for the Fruits, Vegetables and Specialties Segment of the Canned and Preserved Fruits and Vegetables Point Source Category"},
      {"source_id":87,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Apple, Citrus and Potato Processing Segment of the Canned and Preserved Fruits and Vegetables Point Source Category"},
      {"source_id":88,"source_title":"\tGuidance Manual for Electroplating and Metal Finishing Pretreatment Standards"},
      {"source_id":89,"source_title":"Development Document for Existing Source Pretreatment Standards for the Electroplating Point Source Category"},
      {"source_id":90,"source_title":"PART 432-MEAT AND POULTRY PRODUCTS POINT SOURCE CATEGORY"},
      {"source_id":91,"source_title":"PART 407-CANNED AND PRESERVED FRUITS AND VEGETABLES PROCESSING POINT SOURCE CATEGORY"},
      {"source_id":92,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the CATFISH, CRAB, SHRIMP, AND TUNA Segment of the Canned and Preserved Seafood Processing Point Source Category"},
      {"source_id":93,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Fish Meal, Salmon, Bottom Fish, Clam, Oyster, Sardine, Scallop, Herring, and Abalone Segment of the Canned and Preserved Fish and Seafood Processing Industry Point Source Category"},
      {"source_id":94,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Mineral Mining and Processing Industry Point Source Category"},
      {"source_id":95,"source_title":"PART 436-MINERAL MINING AND PROCESSING POINT SOURCE CATEGORY"},
      {"source_id":96,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Copper Forming Point Source Category"},
      {"source_id":97,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Textile, Friction Materials and Sealing Devices Segment of the Asbestos Manufacturing Point Source Category"},
      {"source_id":98,"source_title":"\tDevelopment Document for Effluent Limitations Guidelines and Standards of Performance for New Sources BEET SUGAR PROCESSING Subcategory of the Sugar Processing Point Source Category"},
      {"source_id":99,"source_title":"\tDevelopment Document for Effluent Limitations Guidelines and New Source Performance Standards for the Cane Sugar Refining Segment of the Sugar Processing Point Source Category"},
      {"source_id":100,"source_title":"\tDevelopment Document for Interim Final Effluent Limitations Guidelines and Proposed New Source Performance Standards for the Raw Cane Sugar Processing Segment of the Sugar Processing Point Source Category"},
      {"source_id":101,"source_title":"Technical and Economic Development Document for the Final Effluent Limitations Guidelines and Standards for the Dental Category"},
      {"source_id":102,"source_title":"PART 441-DENTAL OFFICE POINT SOURCE CATEGORY"},
      {"source_id":103,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Inorganic Chemicals Manufacturing Point Source Category"},
      {"source_id":104,"source_title":"Development Document for Effluent Limitations Guidelines New Source Performance Standards and Pretreatment Standards for Inorganic Chemicals Manufacturing Point Source Category (Phase II)"},
      {"source_id":105,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Inorganic Chemicals Manufacturing Point Source Category"},
      {"source_id":106,"source_title":"PART 415-INORGANIC CHEMICALS MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":107,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume I General"},
      {"source_id":108,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume II Bauxite Refining Primary Aluminum Smelting Secondary Aluminum Smelting"},
      {"source_id":109,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume III Primary Copper Smelting Primary Electrolytic Copper Refining Secondary Copper Metallurgical Acid Plants"},
      {"source_id":110,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume IV Primary Zinc Primary Lead Secondary Lead Primary Antimony"},
      {"source_id":111,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume V Primary Precious Metals and Mercury Secondary Precious Metals Secondary Silver Secondary Mercury"},
      {"source_id":112,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume VI Primary Tungsten Secondary Tungsten and Cobalt Primary Molybdenum and Rhenium Secondary Molybdenum and Vanadium"},
      {"source_id":113,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume VII Primary Beryllium Primary Nickel and Cobalt Secondary Nickel Secondary Tin"},
      {"source_id":114,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume VIII Primary Columbium - Tantalum Secondary Tantalum Secondary Uranium"},
      {"source_id":115,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume IX Primary and Secondary Titanium Primary Zirconium and Hafnium"},
      {"source_id":116,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Nonferrous Metals Manufacturing Point Source Category Volume X Primary and Secondary Germanium and Gallium Primary Rare Earth Metals Secondary Indium Index"},
      {"source_id":117,"source_title":"Development Document for Proposed Effluent Limitations Guidelines and New Source Performance Standards for the Secondary Aluminum Smelting Subcategory of the Aluminum Segment of the Nonferrous Metals Manufacturing Point Source Category"},
      {"source_id":118,"source_title":"PART 410-TEXTILE MILLS POINT SOURCE CATEGORY"},
      {"source_id":119,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Textile Mills Point Source Category"},
      {"source_id":120,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Textile Mills Point Source Category"},
      {"source_id":121,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Coal Mining Point Source Category"},
      {"source_id":122,"source_title":"Coal Remining - Best Management Practices Guidance Manual"},
      {"source_id":123,"source_title":"Development Document for Final Effluent Limitations Guidelines and Standards for the Western Alkaline Coal Mining Subcategory"},
      {"source_id":124,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Cement Manufacturing Point Source Category"},
      {"source_id":125,"source_title":"Part 411 - Cement Manufacturing Point Source Category Subart C - Materials Storage Piles Runoff Subcategory"},
      {"source_id":126,"source_title":"Part 411 - Cement Manufacturing Point Source Category"},
      {"source_id":127,"source_title":"PART 411-CEMENT MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":128,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Grain Processing Segment of the Grain Mills Point Source Category"},
      {"source_id":129,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Animal Feed, Breakfast Cereal, and Wheat Starch Segment of the Grain Mills Point Source Category"},
      {"source_id":130,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Dairy Products Processing Point Source Category"},
      {"source_id":131,"source_title":"PART 442-TRANSPORTATION EQUIPMENT CLEANING POINT SOURCE CATEGORY"},
      {"source_id":132,"source_title":"Final Development Document For Effluent Limitations Guidelines and Standards for the Transportation Equipment Cleaning Category"},
      {"source_id":133,"source_title":"Development Document for Final Effluent Limitations Guidelines and Standards for the Landfills Point Source Category"},
      {"source_id":134,"source_title":"PART 445-LANDFILLS POINT SOURCE CATEGORY"},
      {"source_id":135,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Formulated Fertilizer Segment of the Fertilizer Manufacturing Point Source Category"},
      {"source_id":136,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Basic Fertilizer Chemicals Segment of the Fertilizer Manufacturing Point Source Category"},
      {"source_id":137,"source_title":"40 CFR Parts 405, 406, 407, 408, 409, 411, 412, 418, 422, 424, 426, and 432: Best Conventional Pollutant Control Technology; Effluent Limitations Guidelines"},
      {"source_id":138,"source_title":"Development Document for  Final Effluent Limitations Guidelines and Standards for Battery Manufacturing Volume I"},
      {"source_id":139,"source_title":"Development Document for  Final Effluent Limitations Guidelines and Standards for Battery Manufacturing Volume II"},
      {"source_id":140,"source_title":"\tDevelopment Document for Effluent Limitations Guidelines and New Source Performance Standards Insulation Fiberglass Manufacturing Segment of the Glass Manufacturing Point Source Category"},
      {"source_id":141,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Flat Glass Segment of the Glass Manufacturing Point Source Category"},
      {"source_id":142,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Pressed and Blown Glass Segment of the Glass Manufacturing Point Source Category"},
      {"source_id":143,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Oil Base Solvent Wash Subcategories of the Paint Formulating and the Ink Formulating Point Source Category"},
      {"source_id":144,"source_title":"Development Document for Final Effluent Limitations Guidelines and Standards for Commercial Hazardous Waste Combustors"},
      {"source_id":145,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Paving and Roofing Materials (Tars and Asphalt) Point Source Category"},
      {"source_id":146,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Oil Base Solvent Wash Subcategories of the Paint Formulating and the Ink Formulating Point Source Category"},
      {"source_id":147,"source_title":"Development Document for Interim Final Effluent Limitations Guidelines and Proposed New Source Performance Standards for the Photographic Processing Subcategory of the Photographic Point Source Category"},
      {"source_id":148,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Porcelain Enameling Point Source Category"},
      {"source_id":149,"source_title":"Guidance Document for the Control of Water Pollution in the Photographic Processing Industry"},
      {"source_id":150,"source_title":"Development Document for Interim Final Effluent Limitations, Guidelines and Proposed New Source Performance Standards for the Carbon Black Manufacturing Point Source Category"},
      {"source_id":151,"source_title":"Development Document for Interim Final Effluent Limitations Guidelines and Proposed New Source Performance Standards for the Explosives Manufacturing Point Source Category"},
      {"source_id":152,"source_title":"PART 457-EXPLOSIVES MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":153,"source_title":"Development Document for Interim Final Effluent Limitations, Guidelines and Proposed New Source Performance Standards for the Hospital Point Source Category"},
      {"source_id":154,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Plastics Molding and Forming Point Source Category"},
      {"source_id":155,"source_title":"Technical Development Document for the Final Effluent Limitations Guidelines and New Source Performance Standards for the Airport Deicing Category"},
      {"source_id":156,"source_title":"Technical Development Document for the Final Effluent Limitations Guidelines and New Source Performance Standards for the Concentrated Aquatic Animal Production Point Source Category (Revised August 2004)"},
      {"source_id":157,"source_title":"PART 450-CONSTRUCTION AND DEVELOPMENT POINT SOURCE CATEGORY"},
      {"source_id":158,"source_title":"Development Document for Effluent Limitations Guidelines and New Source Performance Standards for the Petroleum Refining Point Source Category"},
      {"source_id":159,"source_title":"Petroleum Refining Point Source Category; Effluent Limitations Guidelines"},
      {"source_id":160,"source_title":"Development Document for Effluent Limitations Guidelines and Standards for the Petroleum Refining Point Source Category"},
      {"source_id":161,"source_title":"Interim Final Supplement for Pretreatment to the Development Document for the Petroleum Refining Industry Existing Point Source Category"},
      {"source_id":162,"source_title":"PART 469-ELECTRICAL AND ELECTRONIC COMPONENTS POINT SOURCE CATEGORY"},
      {"source_id":163,"source_title":"Electrical and Electronic Components Point Source Category Pretreatment Standards, and New Source Performance Standards; (Phase II)"},
      {"source_id":164,"source_title":"Electrical and Electronic Components Point Source Category Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":165,"source_title":"Electrical and Electronic Components Point Source Category; Effluent Limitations Guidelines"},
      {"source_id":166,"source_title":"Electrical and Electronic Components Point Source Category Pretreatment Standards, and New Source Performance Standards; (Phase II)"},
      {"source_id":167,"source_title":"Electrical and Electronic Components Point Source Categories and Electroplating and Metal Finishing Point Source Categories; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards; OMB Approval of Information Requirements"},
      {"source_id":168,"source_title":"Electrical and Electronic Components\nPoint Source Category Effluent\nLimitations Guidelines Phase I"},
      {"source_id":169,"source_title":"Information Requirements; OMB \nApproval; Technical Amendments"},
      {"source_id":170,"source_title":"PART 417-SOAP AND DETERGENT MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":171,"source_title":"SUBCHAPTER N-EFFLUENT GUIDELINES AND STANDARDS: PART 417-SOAP AND DETERGENT MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":172,"source_title":"Part 417 - Soap and Detergent Manufacturing Point Source Category Glycerine Concentration Subcategory Correction"},
      {"source_id":173,"source_title":"Part 417 - Soap and Detergent Manufacturing Category Miscellaneous Amendments; Corrections"},
      {"source_id":174,"source_title":"Part 417 - Soap and Detergent Manufacturing Category Pretreatment Standards for New Sources"},
      {"source_id":175,"source_title":"PART 417-SOAP AND DETERGENT MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":176,"source_title":"Part 417 - [AMENDED]"},
      {"source_id":177,"source_title":"Effluent Limitations Guidelines and New Source Performance Standards for the Meat and Poultry Products Point Source Category"},
      {"source_id":178,"source_title":"PART 427-ASBESTOS MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":179,"source_title":"Title 40-Protection of the Environment CHAPTER I-ENVIRONMENTAL PROTECTION AGENCY SUBCHAPTER N-EFFLUENT GUIDELINES AND STANDARDS PART 427-ASBESTOS MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":180,"source_title":"SUBCHAPTER N-EFFLUENT GUIDELINES AND STANDARDS PART 427-ASBESTOS MANUFACTURING POINT SOURCE CATEGORY Corrections"},
      {"source_id":181,"source_title":"Title 40-Protection of the Environment CHAPTER I-ENVIRONMENTAL PROTECTION AGENCY -SUBCHAPTER N-EFFLUENT GUIDELINES AND, STANDARDS IFJL 315-5] PART 427-ASBESTOS MANUFACTURING POINT SOURCE CATEGORY"},
      {"source_id":182,"source_title":"Title 40-Protection of the Environment CHAPTER I-ENVIRONMENTAL PROTECTION AGENCY SUBCHAPTER N-EFFLUENT GUIDELNES AND STANDARDS [FaL 331-81 PRETREATMENT .STANDARDS"},
      {"source_id":183,"source_title":"Best Conventional Pollutant Control Technology; Reasonableness of Existing Effluent Limitation Guidelines."},
      {"source_id":184,"source_title":"National Pollutant Discharge Elimination System and Pretreatment Programs; State and Local Assistance Programs; Effluent Limitations Guidelines and Standards; Public Water Supply and Underground Injection Control Programs: Removal of Legally Obsolete or Redundant Rules"},
      {"source_id":185,"source_title":"PART 413-ELECTROPLATING POINT SOURCE CATEGORY"},
      {"source_id":186,"source_title":"Electroplating Point Source Category; Effluent Limitations Guidelines"},
      {"source_id":187,"source_title":"Electroplating and Metal Finishing Point Source Categories; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":188,"source_title":"40 CFR Parts 413, 425, 433, 465, 466, 468, and 469 [WH-FRL 2432-6] Electroplating Leather Tanning and Finishing, Metal Finishing, Coil Coating, Porcelain Enameling, Copper Forming and Electrical and Electronic Components-Pretreatment Standards for Existing Sources Compliance Deadline"},
      {"source_id":189,"source_title":"40 CFR Parts 413 and 433 Electroplating and Metal Finishing Point Source Categories; Effluent Limitations Guidelines Pretreatment Standards, and New Source Performance Standards; Clarification and Correction"},
      {"source_id":190,"source_title":"40 CFR Parts 413,433 and 469 Electrical and Electronic Components Point Source Categories and Electroplating and Metal Finishing Point Source Categories; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards; OMB Approval of Information Requirements"},
      {"source_id":191,"source_title":"Electroplating and Metal Finishing Point Source Categories; Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards"},
      {"source_id":192,"source_title":"PART 444-WASTE COMBUSTORS POINT SOURCE CATEGORY"},
      {"source_id":193,"source_title":"Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards for the Commercial Hazardous Waste Combustor Subcategory of the Waste Combustors Point Source Category"},
      {"source_id":194,"source_title":"Effluent Limitations Guidelines, Pretreatment Standards, and New Source Performance Standards for the Commercial Hazardous Waste Combustor Subcategory of the Waste Combustors Point Source Category; Correction"},
      {"source_id":195,"source_title":"Cranberries Grown in the States of\nMassachusetts, et al.; Order Amending\nMarketing Agreement and Order No.\n929"},
      {"source_id":196,"source_title":"Corrections"},
      {"source_id":197,"source_title":"SUBCHAPTER N- EFFLUENT GUIDELINES AND STANDARDS PART 407- CANNED AND PRESERVED FRUITS AND VEGETABLES PROCESSING POINT SOURCE CATEGORY"},
      {"source_id":198,"source_title":"PART 407- CANNED AND PRESERVED FRUITS AND VEGETABLES PROCESSING POINT SOURCE CATEGORY"},
      {"source_id":199,"source_title":"PART 407- CANNED AND PRESERVED FRUITS AND VEGETABLES POINT SOURCE CATEGORY"},
      {"source_id":200,"source_title":"PART 407- CANNED AND PRESERVED FRUITS AND VEGETABLE PROCESSING POINT SOURCE CATEGORY Revocation of Fecal Coliform Effluent Limitations"},
      {"source_id":201,"source_title":"Canned and Preserved Fruits Point Source Subcategory; Amendment of Promulgated Effluent Limitations Regulation"},
      {"source_id":202,"source_title":"PART 407- CANNED AND PRESERVED FRUITS AND VEGETABLES PROCESSING POINT SOURCE CATEGORY"},
      {"source_id":203,"source_title":"PART 407-[AMENDED]"}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "ReferenceSource" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "ReferenceSource"
  }, null, {})
};
