module.exports = {
  up(queryInterface) {
    let records = [{"sic":"3732",
      "sic_desc":"Boat Building and Repairing"},
      {"sic":"3743",
        "sic_desc":"Railroad Equipment"},
      {"sic":"3751",
        "sic_desc":"Motorcycles, Bicycles, and Parts"},
      {"sic":"3761",
        "sic_desc":"Guided Missiles & Space Vehicles"},
      {"sic":"3764",
        "sic_desc":"Space Propulsion Units & Parts"},
      {"sic":"3769",
        "sic_desc":"Space Vehicle Equipment, NEC"},
      {"sic":"3792",
        "sic_desc":"Travel Trailers and Campers"},
      {"sic":"3795",
        "sic_desc":"Tanks and Tank Components"},
      {"sic":"3799",
        "sic_desc":"Transportation Equipment, NEC"},
      {"sic":"3812",
        "sic_desc":"Search & Navigation Equipment"},
      {"sic":"3821",
        "sic_desc":"Laboratory Apparatus and Furniture"},
      {"sic":"3822",
        "sic_desc":"Environmental Controls"},
      {"sic":"3823",
        "sic_desc":"Process Control Instruments"},
      {"sic":"3824",
        "sic_desc":"Fluid Meters & Counting Device"},
      {"sic":"3825",
        "sic_desc":"Instruments to Measure Electricity"},
      {"sic":"3826",
        "sic_desc":"Analytical Instruments"},
      {"sic":"3827",
        "sic_desc":"Optical Instruments and Lenses"},
      {"sic":"3829",
        "sic_desc":"Measuring & Controlling Device"},
      {"sic":"3841",
        "sic_desc":"Surgical & Medical Instruments"},
      {"sic":"3842",
        "sic_desc":"Surgical Appliances & Supplies"},
      {"sic":"3843",
        "sic_desc":"Dental Equipment and Supplies"},
      {"sic":"3844",
        "sic_desc":"X-Ray Apparatus and Tubes"},
      {"sic":"3845",
        "sic_desc":"Electromedical Equipment"},
      {"sic":"3851",
        "sic_desc":"Ophthalmic Goods"},
      {"sic":"3861",
        "sic_desc":"Photographic Equipment and Supplies"},
      {"sic":"3873",
        "sic_desc":"Watches, Clocks & Watchcases"},
      {"sic":"3911",
        "sic_desc":"Jewelry, Precious Metal"},
      {"sic":"3914",
        "sic_desc":"Silverware and Plated Ware"},
      {"sic":"3915",
        "sic_desc":"Jewelers' Materials & Lapidary"},
      {"sic":"3931",
        "sic_desc":"Musical Instruments"},
      {"sic":"3942",
        "sic_desc":"Dolls"},
      {"sic":"3944",
        "sic_desc":"Games, Toys & Children's Vehicles"},
      {"sic":"3949",
        "sic_desc":"Sporting & Athletic Goods, NEC"},
      {"sic":"3951",
        "sic_desc":"Pens & Mechanical Pencils"},
      {"sic":"3952",
        "sic_desc":"Lead Pencils and Art Goods"},
      {"sic":"3953",
        "sic_desc":"Marking Devices"},
      {"sic":"3955",
        "sic_desc":"Carbon Paper and Inked Ribbons"},
      {"sic":"3961",
        "sic_desc":"Costume Jewelry"},
      {"sic":"3965",
        "sic_desc":"Fasteners, Buttons, Needles"},
      {"sic":"3991",
        "sic_desc":"Brooms and Brushes"},
      {"sic":"3993",
        "sic_desc":"Signs and Advertising Displays"},
      {"sic":"3995",
        "sic_desc":"Burial Caskets"},
      {"sic":"3996",
        "sic_desc":"Hard Surface Floor Coverings"},
      {"sic":"3999",
        "sic_desc":"Manufacturing Industries, NEC"},
      {"sic":"4011",
        "sic_desc":"Railroads, Line Haul Operating"},
      {"sic":"4013",
        "sic_desc":"Railroad Switching and Terminal Establishments"},
      {"sic":"4111",
        "sic_desc":"Local and Suburban Transit"},
      {"sic":"4119",
        "sic_desc":"Local Passenger Transportation"},
      {"sic":"4121",
        "sic_desc":"Taxicabs"},
      {"sic":"4131",
        "sic_desc":"Intercity & Rural Bus Transpor"},
      {"sic":"4141",
        "sic_desc":"Local Bus Charter Service"},
      {"sic":"4142",
        "sic_desc":"Bus Charter Service, Exc Local"},
      {"sic":"4151",
        "sic_desc":"School Buses"},
      {"sic":"4173",
        "sic_desc":"Bus Terminal & Service Facilities"},
      {"sic":"4212",
        "sic_desc":"Local Trucking Without Storage"},
      {"sic":"4213",
        "sic_desc":"Trucking, Except Local"},
      {"sic":"4214",
        "sic_desc":"Local Trucking with Storage"},
      {"sic":"4215",
        "sic_desc":"Courier Services, Except Air"},
      {"sic":"4221",
        "sic_desc":"Farm Prod Warehousing & Storage"},
      {"sic":"4222",
        "sic_desc":"Refrigerated Warehousing & Storage"},
      {"sic":"4225",
        "sic_desc":"General Warehousing & Storage"},
      {"sic":"4226",
        "sic_desc":"Special Warehousing & Storage"},
      {"sic":"4231",
        "sic_desc":"Trucking Terminal Facilities"},
      {"sic":"4311",
        "sic_desc":"United States Postal Service"},
      {"sic":"4412",
        "sic_desc":"Deep Sea Foreign Transp Of Freight"},
      {"sic":"4424",
        "sic_desc":"Deep Sea Domes Transp Of Freight"},
      {"sic":"4432",
        "sic_desc":"Freight Transp On the Gr Lakes"},
      {"sic":"4449",
        "sic_desc":"Water Transp of Freight, NEC"},
      {"sic":"4481",
        "sic_desc":"Deep Sea Pas Transp, Exc Ferry"},
      {"sic":"4482",
        "sic_desc":"Ferries"},
      {"sic":"4489",
        "sic_desc":"Water Passenger Transportation"},
      {"sic":"4491",
        "sic_desc":"Marine Cargo Handling"},
      {"sic":"4492",
        "sic_desc":"Towing and Tugboat Service"},
      {"sic":"4493",
        "sic_desc":"Marinas"},
      {"sic":"4499",
        "sic_desc":"Water Transportation Services"},
      {"sic":"4512",
        "sic_desc":"Air Transportation, Scheduled"},
      {"sic":"4513",
        "sic_desc":"Air Courier Services"},
      {"sic":"4522",
        "sic_desc":"Air Transp, Nonscheduled"},
      {"sic":"4581",
        "sic_desc":"Airports, Flying Fields & Services"},
      {"sic":"4612",
        "sic_desc":"Crude Petroleum Pipelines"},
      {"sic":"4613",
        "sic_desc":"Refined Petroleum Pipeline"},
      {"sic":"4619",
        "sic_desc":"Pipelines, NEC"},
      {"sic":"4724",
        "sic_desc":"Travel Agencies"},
      {"sic":"4725",
        "sic_desc":"Tour Operators"},
      {"sic":"4729",
        "sic_desc":"Passenger Transp Arrangement"},
      {"sic":"4731",
        "sic_desc":"Freight Transp Arrangement"},
      {"sic":"4741",
        "sic_desc":"Rental of Railroad Cars"},
      {"sic":"4783",
        "sic_desc":"Packing and Crating"},
      {"sic":"4785",
        "sic_desc":"Inspection & Fixed Facilitie"},
      {"sic":"4789",
        "sic_desc":"Transportation Services, NEC"},
      {"sic":"4812",
        "sic_desc":"Radiotelephone Communications"},
      {"sic":"4813",
        "sic_desc":"Telephone Com, Except Radio"},
      {"sic":"4822",
        "sic_desc":"Telegraph & Other Communications"},
      {"sic":"4832",
        "sic_desc":"Radio Broadcasting, NEC"},
      {"sic":"4833",
        "sic_desc":"Television Broadcasting"},
      {"sic":"4841",
        "sic_desc":"Cable & Other Pay Tv Services"},
      {"sic":"4899",
        "sic_desc":"Communication Services, NEC"},
      {"sic":"4911",
        "sic_desc":"Electrical Services"},
      {"sic":"4922",
        "sic_desc":"Natural Gas Transmission"},
      {"sic":"4923",
        "sic_desc":"Nat Gas Transmission & Distribution"},
      {"sic":"4924",
        "sic_desc":"Natural Gas Distribution"},
      {"sic":"4925",
        "sic_desc":"Mixed, Manufactured, Or Liquefied Petroleum Gas Production"},
      {"sic":"4931",
        "sic_desc":"Electric and Other Services Combined"},
      {"sic":"4932",
        "sic_desc":"Gas & Other Services Combined"},
      {"sic":"4939",
        "sic_desc":"Combination Utilities, NEC"},
      {"sic":"4941",
        "sic_desc":"Water Supply"},
      {"sic":"4952",
        "sic_desc":"Sewerage Systems"},
      {"sic":"4953",
        "sic_desc":"Refuse Systems"},
      {"sic":"4959",
        "sic_desc":"Sanitary Services, NEC"},
      {"sic":"4961",
        "sic_desc":"Steam & Air-Conditioning Supplies"},
      {"sic":"4971",
        "sic_desc":"Irrigation Systems"},
      {"sic":"5012",
        "sic_desc":"Automobiles and Other Vehicles"},
      {"sic":"5013",
        "sic_desc":"Motor Vehicle Parts & New Supplies"},
      {"sic":"5014",
        "sic_desc":"Tires and Tubes"},
      {"sic":"5015",
        "sic_desc":"Motor Vehicle Parts, Used"},
      {"sic":"5021",
        "sic_desc":"Furniture"},
      {"sic":"5023",
        "sic_desc":"Homefurnishings"},
      {"sic":"5031",
        "sic_desc":"Lumber, Plywood, Millwork, & Panl"},
      {"sic":"5032",
        "sic_desc":"Brick, Stone, and Related Construction Materials"},
      {"sic":"5033",
        "sic_desc":"Roofing, Siding, and Insulation"},
      {"sic":"5039",
        "sic_desc":"Construction Materials, NEC"},
      {"sic":"5043",
        "sic_desc":"Photographic Equip & Supplies"},
      {"sic":"5044",
        "sic_desc":"Office Equipment"},
      {"sic":"5045",
        "sic_desc":"Computers, Peripherals, & Soft"},
      {"sic":"5046",
        "sic_desc":"Commercial Equipment, NEC"},
      {"sic":"5047",
        "sic_desc":"Medical and Office Equipment"},
      {"sic":"5048",
        "sic_desc":"Ophthalmic Goods"},
      {"sic":"5049",
        "sic_desc":"Professional Equipment, NEC"},
      {"sic":"5051",
        "sic_desc":"Metal Service Centers & Office"},
      {"sic":"5052",
        "sic_desc":"Coal & Other Minerals & Ores"},
      {"sic":"5063",
        "sic_desc":"Electrical Apparatus and Equip"},
      {"sic":"5064",
        "sic_desc":"Elec Appliances/Tv & Radio Set"},
      {"sic":"5065",
        "sic_desc":"Electronic Parts and Equipment"},
      {"sic":"5072",
        "sic_desc":"Hardware"},
      {"sic":"5074",
        "sic_desc":"Plumb & Heat Equip & Supplies"},
      {"sic":"5075",
        "sic_desc":"Air Heat & Air-Cond. Equip/Supplies"},
      {"sic":"5078",
        "sic_desc":"Refrigeration Equip & Supplies"},
      {"sic":"5082",
        "sic_desc":"Const & Mining Machine & Equip"},
      {"sic":"5083",
        "sic_desc":"Farm & Garden Machine & Equip"},
      {"sic":"5084",
        "sic_desc":"Industrial Machinery and Equip"},
      {"sic":"5085",
        "sic_desc":"Industrial Supplies"},
      {"sic":"5087",
        "sic_desc":"Service Establish Equip & Supp"},
      {"sic":"5088",
        "sic_desc":"Trans Equip & Supp, Exc Motor"},
      {"sic":"5091",
        "sic_desc":"Sporting & Recreational Goods"},
      {"sic":"5092",
        "sic_desc":"Toys & Hobby Goods & Supplies"},
      {"sic":"5093",
        "sic_desc":"Scrap & Waste Materials"},
      {"sic":"5094",
        "sic_desc":"Jewelry, Watches, Precious Stones"},
      {"sic":"5099",
        "sic_desc":"Durable Goods, NEC"},
      {"sic":"5111",
        "sic_desc":"Printing and Writing Paper"},
      {"sic":"5112",
        "sic_desc":"Stationery and Office Supplies"},
      {"sic":"5113",
        "sic_desc":"Indust & Personal Paper Service"},
      {"sic":"5122",
        "sic_desc":"Drugs, Drug Prpprie & Sundries"},
      {"sic":"5131",
        "sic_desc":"Piece Goods and Notions"},
      {"sic":"5136",
        "sic_desc":"Male's Clothing & Furnishings"},
      {"sic":"5137",
        "sic_desc":"Women's, Child & Infant Clothing"},
      {"sic":"5139",
        "sic_desc":"Footwear"},
      {"sic":"5141",
        "sic_desc":"Groceries, General Line"},
      {"sic":"5142",
        "sic_desc":"Packaged Frozen Foods"},
      {"sic":"5143",
        "sic_desc":"Dairy Prod, Exc Dried & Canned"},
      {"sic":"5144",
        "sic_desc":"Poultry and Poultry Products"},
      {"sic":"5145",
        "sic_desc":"Confectionery"},
      {"sic":"5146",
        "sic_desc":"Fish and Seafoods"},
      {"sic":"5147",
        "sic_desc":"Meats and Meat Products"},
      {"sic":"5148",
        "sic_desc":"Fresh Fruits and Vegetables"},
      {"sic":"5149",
        "sic_desc":"Groceries & Related Products"},
      {"sic":"5153",
        "sic_desc":"Grain and Field Beans"},
      {"sic":"5154",
        "sic_desc":"Livestock"},
      {"sic":"5159",
        "sic_desc":"Farm-Product Raw Materials"},
      {"sic":"5162",
        "sic_desc":"Plastic Mater & Basic Shapes"},
      {"sic":"5169",
        "sic_desc":"Chemicals and Allied Products"},
      {"sic":"5171",
        "sic_desc":"Petroleum Bulk Stations and Terminals"},
      {"sic":"3465",
        "sic_desc":"Automotive Stampings"},
      {"sic":"3466",
        "sic_desc":"Crowns and Closures"},
      {"sic":"3469",
        "sic_desc":"Metal Stampings, NEC"},
      {"sic":"3471",
        "sic_desc":"Plating and Polishing"},
      {"sic":"3479",
        "sic_desc":"Coating, Engraving, and Allied Services, Not Elsewhere Classified"},
      {"sic":"3482",
        "sic_desc":"Small Arms Ammunition"},
      {"sic":"3483",
        "sic_desc":"Ammunition, Except For Small Arms"},
      {"sic":"3484",
        "sic_desc":"Small Arms"},
      {"sic":"3489",
        "sic_desc":"Ordnance and Accessories, NEC"},
      {"sic":"3491",
        "sic_desc":"Industrial Valves"},
      {"sic":"3492",
        "sic_desc":"Fluid Power Valves & Hose Fitting"},
      {"sic":"3493",
        "sic_desc":"Steel Springs, Except Wire"},
      {"sic":"3494",
        "sic_desc":"Valves and Pipe Fittings, NEC"},
      {"sic":"3495",
        "sic_desc":"Wire Springs"},
      {"sic":"3496",
        "sic_desc":"Misc. Fabricated Wire ProductsMiscellaneous Fabricated Wire Products"},
      {"sic":"3497",
        "sic_desc":"Metal Foil and Leaf"},
      {"sic":"3498",
        "sic_desc":"Fabricated Pipe and Fittings"},
      {"sic":"3499",
        "sic_desc":"Fabricated Metal Products NEC"},
      {"sic":"3511",
        "sic_desc":"Turbines & Turbine Generator"},
      {"sic":"3519",
        "sic_desc":"Internal Combustion Engines, NEC"},
      {"sic":"3523",
        "sic_desc":"Farm Machinery and Equipment"},
      {"sic":"3524",
        "sic_desc":"Lawn and Garden Equipment"},
      {"sic":"3531",
        "sic_desc":"Construction Machinery"},
      {"sic":"3532",
        "sic_desc":"Mining Machinery"},
      {"sic":"3533",
        "sic_desc":"Oil Field Machinery"},
      {"sic":"3534",
        "sic_desc":"Elevators and Moving Stairways"},
      {"sic":"3535",
        "sic_desc":"Conveyors & Conveying Equipment"},
      {"sic":"3536",
        "sic_desc":"Overhead Traveling Cranes, Hoists, and Monorail Systems"},
      {"sic":"3537",
        "sic_desc":"Industrial Trucks and Tractors"},
      {"sic":"3541",
        "sic_desc":"Machine Tools, Metal Cutting"},
      {"sic":"3542",
        "sic_desc":"Machine Tools, Metal Forming"},
      {"sic":"3543",
        "sic_desc":"Industrial Patterns"},
      {"sic":"3544",
        "sic_desc":"Special Dies and Tools, Die Sets, Jigs, Fixtures and Molds"},
      {"sic":"3545",
        "sic_desc":"Machine Tool Accessories"},
      {"sic":"3546",
        "sic_desc":"Power Driven Hand Tools"},
      {"sic":"3547",
        "sic_desc":"Rolling Mill Machinery"},
      {"sic":"3548",
        "sic_desc":"Welding Apparatus"},
      {"sic":"3549",
        "sic_desc":"Metalworking Machinery, NEC"},
      {"sic":"3552",
        "sic_desc":"Textile Machinery"},
      {"sic":"3553",
        "sic_desc":"Woodworking Machinery"},
      {"sic":"3554",
        "sic_desc":"Paper Industries Machinery"},
      {"sic":"3555",
        "sic_desc":"Printing Trades Machinery"},
      {"sic":"3556",
        "sic_desc":"Food Products Machinery"},
      {"sic":"3559",
        "sic_desc":"Special Industry Machinery, NEC"},
      {"sic":"3561",
        "sic_desc":"Pumps and Pumping Equipment"},
      {"sic":"3562",
        "sic_desc":"Ball and Roller Bearings"},
      {"sic":"3563",
        "sic_desc":"Air and Gas Compressors"},
      {"sic":"3564",
        "sic_desc":"Blower and Fans"},
      {"sic":"3565",
        "sic_desc":"Packaging Machinery"},
      {"sic":"3566",
        "sic_desc":"Speed Changers, Drives & Gears"},
      {"sic":"3567",
        "sic_desc":"Industrial Furnaces and Ovens"},
      {"sic":"3568",
        "sic_desc":"Power Transmission Equipment"},
      {"sic":"3569",
        "sic_desc":"General Industrial Machinery"},
      {"sic":"3571",
        "sic_desc":"Electronic Computers"},
      {"sic":"3572",
        "sic_desc":"Computer Storage Devices"},
      {"sic":"3575",
        "sic_desc":"Computer Terminals"},
      {"sic":"3577",
        "sic_desc":"Computer Peripheral Equipment, Not Elsewhere Classified"},
      {"sic":"3578",
        "sic_desc":"Calculating and Accounting Machines, Except Electronic Computers"},
      {"sic":"3579",
        "sic_desc":"Office Machines"},
      {"sic":"2281",
        "sic_desc":"Yarn Spinning Mills"},
      {"sic":"2282",
        "sic_desc":"Yarn Texturizing, Throwing, Twisting, and Winding Mills"},
      {"sic":"2284",
        "sic_desc":"Thread Mills"},
      {"sic":"2295",
        "sic_desc":"Coated Fabrics, Not Rubberized"},
      {"sic":"2296",
        "sic_desc":"Tire Cord and Fabric"},
      {"sic":"2297",
        "sic_desc":"Nonwoven Fabrics"},
      {"sic":"2298",
        "sic_desc":"Cordage and Twine"},
      {"sic":"2299",
        "sic_desc":"Textile Goods, NEC"},
      {"sic":"2311",
        "sic_desc":"Men's & Boy's Suits, Coats"},
      {"sic":"2321",
        "sic_desc":"Men's, & Boy's Shirts"},
      {"sic":"2322",
        "sic_desc":"Men's and Boys' Underwear and Nightwear"},
      {"sic":"2323",
        "sic_desc":"Men's, Youth's & Boys Neckwear"},
      {"sic":"2325",
        "sic_desc":"Men & Boy Sep Trousers & Slack"},
      {"sic":"2326",
        "sic_desc":"Men's & Boy's Work Clothing"},
      {"sic":"2329",
        "sic_desc":"Men's, Youth's & Boy's Clothing"},
      {"sic":"2331",
        "sic_desc":"Women, Mis, Jr' Blses, Waists"},
      {"sic":"2335",
        "sic_desc":"Women's, Misses' & Jrs' Dress"},
      {"sic":"2337",
        "sic_desc":"Women, Mis', Jrs' Suits, Shirt"},
      {"sic":"2339",
        "sic_desc":"Women's, Miss' & Jr' Outerwear"},
      {"sic":"2341",
        "sic_desc":"Womens, Mis', Chld's, Inf Underwe"},
      {"sic":"2342",
        "sic_desc":"Brassiers, Girdles & Allied Gar"},
      {"sic":"2353",
        "sic_desc":"Hats, Caps and Millinery"},
      {"sic":"2361",
        "sic_desc":"Girls, Childs & Infs Outerwear"},
      {"sic":"2369",
        "sic_desc":"Girls, Childs & Infs Outerwear"},
      {"sic":"2371",
        "sic_desc":"Fur Goods"},
      {"sic":"2381",
        "sic_desc":"Dress & Wk Glove Exc Knit/Leat"},
      {"sic":"2384",
        "sic_desc":"Robes & Dressing Gowns"},
      {"sic":"2385",
        "sic_desc":"Raincoats & Raingear"},
      {"sic":"2386",
        "sic_desc":"Leather & Sheep-Lined Clothing"},
      {"sic":"2387",
        "sic_desc":"Apparel Belts"},
      {"sic":"2389",
        "sic_desc":"Apparel & Accessories, NEC"},
      {"sic":"2391",
        "sic_desc":"Curtains & Draperies"},
      {"sic":"2392",
        "sic_desc":"House furnishings, Exc Curtains"},
      {"sic":"2393",
        "sic_desc":"Textile Bags"},
      {"sic":"2394",
        "sic_desc":"Canvas & Related Products"},
      {"sic":"2395",
        "sic_desc":"Pleating, Decor/Novelty Stitch"},
      {"sic":"2396",
        "sic_desc":"Automotive Trimmings, Apparel"},
      {"sic":"2397",
        "sic_desc":"Schiffli Machine Embroideries"},
      {"sic":"2399",
        "sic_desc":"Fabricated Textile Products NEC"},
      {"sic":"2411",
        "sic_desc":"Logging Camps/Logging Contract"},
      {"sic":"2421",
        "sic_desc":"Sawmills and Planing Mills, General"},
      {"sic":"2426",
        "sic_desc":"Hardwood Dimen & Flooring Mill"},
      {"sic":"2429",
        "sic_desc":"Special Product Sawmills NEC"},
      {"sic":"2431",
        "sic_desc":"Millwork"},
      {"sic":"2434",
        "sic_desc":"Wood Kitchen Cabinets"},
      {"sic":"2435",
        "sic_desc":"Hardwood Veneer and Plywood"},
      {"sic":"2436",
        "sic_desc":"Softwood Veneer and Plywood"},
      {"sic":"2439",
        "sic_desc":"Structural Wood Members, NEC"},
      {"sic":"2441",
        "sic_desc":"Nailed/Lock Corner Wood Boxes"},
      {"sic":"2448",
        "sic_desc":"Wood Pallets and Skids"},
      {"sic":"2449",
        "sic_desc":"Wood Containers NEC"},
      {"sic":"2451",
        "sic_desc":"Mobile Homes"},
      {"sic":"2452",
        "sic_desc":"Prefab Wood Bldgs & Components"},
      {"sic":"2491",
        "sic_desc":"Wood Preserving"},
      {"sic":"2493",
        "sic_desc":"Reconstituted Wood Products"},
      {"sic":"2499",
        "sic_desc":"Wood Products, NEC"},
      {"sic":"2511",
        "sic_desc":"Wood Household Furniture, Except Upholstered"},
      {"sic":"2512",
        "sic_desc":"Wood Household Furn, Upholster"},
      {"sic":"2514",
        "sic_desc":"Metal Household Furniture"},
      {"sic":"2515",
        "sic_desc":"Mattresses and Bedsprings"},
      {"sic":"2517",
        "sic_desc":"Wood TV, Radio, Phono Cabinet"},
      {"sic":"2519",
        "sic_desc":"Household Furniture, NEC"},
      {"sic":"2521",
        "sic_desc":"Wood Office Furniture"},
      {"sic":"2522",
        "sic_desc":"Metal Office Furniture"},
      {"sic":"2531",
        "sic_desc":"Public Building and Related Furniture"},
      {"sic":"2541",
        "sic_desc":"Wood Office and Store Fixtures, Partitions, Shelving, and Lockers"},
      {"sic":"2542",
        "sic_desc":"Office and Store Fixtures, Partitions, Shelving, and Lockers"},
      {"sic":"2591",
        "sic_desc":"Drapery Hardware and Window Blinds and Shades"},
      {"sic":"2599",
        "sic_desc":"Furniture and Fixtures, NEC"},
      {"sic":"2611",
        "sic_desc":"Pulp Mills"},
      {"sic":"2621",
        "sic_desc":"Paper Mills"},
      {"sic":"2631",
        "sic_desc":"Paperboard Mills"},
      {"sic":"2652",
        "sic_desc":"Set-Up Paperboard Boxes"},
      {"sic":"2653",
        "sic_desc":"Corrugated and Solid Fiber Boxes"},
      {"sic":"2655",
        "sic_desc":"Fiber Cans, Tubes, Drums, and Similar Products"},
      {"sic":"2656",
        "sic_desc":"Sanitary Food Containers"},
      {"sic":"2657",
        "sic_desc":"Folding Paperboard Boxes"},
      {"sic":"2671",
        "sic_desc":"Coated & Laminated Packaging"},
      {"sic":"2672",
        "sic_desc":"Coated & Laminated, NEC"},
      {"sic":"2673",
        "sic_desc":"Bags, Plastic, Lamina & Coated"},
      {"sic":"2674",
        "sic_desc":"Uncoated Paper and Multiwall Bags"},
      {"sic":"2675",
        "sic_desc":"Die-Cut Paper, Paperbrd/Cardbrd"},
      {"sic":"2676",
        "sic_desc":"Sanitary Paper Products"},
      {"sic":"2677",
        "sic_desc":"Envelopes"},
      {"sic":"2678",
        "sic_desc":"Stationery, Tablets & Rel Prod"},
      {"sic":"2679",
        "sic_desc":"Converted Paper and Paperboard Products, Not Elsewhere Classified"},
      {"sic":"2711",
        "sic_desc":"Newspapers: Publishing & Print"},
      {"sic":"2721",
        "sic_desc":"Periodicals: Publishing & Print"},
      {"sic":"2731",
        "sic_desc":"Books: Publishing & Printing"},
      {"sic":"2732",
        "sic_desc":"Book Printing"},
      {"sic":"2741",
        "sic_desc":"Miscellaneous Publishing"},
      {"sic":"2752",
        "sic_desc":"Commercial Print, Lithographic"},
      {"sic":"2754",
        "sic_desc":"Commercial Printing, Gravure"},
      {"sic":"2759",
        "sic_desc":"Commercial Printing, NEC"},
      {"sic":"2761",
        "sic_desc":"Manifold Business Forms"},
      {"sic":"2771",
        "sic_desc":"Greeting Card Publishing"},
      {"sic":"2782",
        "sic_desc":"Blankbooks, Looseleaf Binders"},
      {"sic":"2789",
        "sic_desc":"Bookbinding & Related Work"},
      {"sic":"2791",
        "sic_desc":"Typesetting"},
      {"sic":"2796",
        "sic_desc":"Platemaking Services"},
      {"sic":"2812",
        "sic_desc":"Alkalies And Chlorine"},
      {"sic":"2813",
        "sic_desc":"Industrial Gases"},
      {"sic":"2816",
        "sic_desc":"Inorganic Pigments"},
      {"sic":"2819",
        "sic_desc":"Industrial Inorganic Chemicals"},
      {"sic":"2821",
        "sic_desc":"Plastics Materials, Synthetic Resins, and Nonvulcanizable Elastomers"},
      {"sic":"2822",
        "sic_desc":"Synthetic Rubber (Vulcanizable Elastomers)"},
      {"sic":"2823",
        "sic_desc":"Cellulosic Man-Made Fibers"},
      {"sic":"2824",
        "sic_desc":"Manmade Organic Fibers, Except Cellulosic"},
      {"sic":"2833",
        "sic_desc":"Medicinal Chemicals and Botanical Products"},
      {"sic":"2834",
        "sic_desc":"Pharmaceutical Preparations"},
      {"sic":"2835",
        "sic_desc":"Diagnostic Substances"},
      {"sic":"2836",
        "sic_desc":"Biological Products, Except Diagnostic Substances"},
      {"sic":"2841",
        "sic_desc":"Soap and Other Detergents, Except Specialty Cleaners"},
      {"sic":"2842",
        "sic_desc":"Specialty Cleaning, Polishing"},
      {"sic":"2843",
        "sic_desc":"Surface Active Agents, Finishing Agents, and Sulfonated Oils"},
      {"sic":"2844",
        "sic_desc":"Perfumes, Cosmetics, and Other Toilet Preparations"},
      {"sic":"2851",
        "sic_desc":"Paints, Varnishes, Lacquers, Enamels, and Allied Products"},
      {"sic":"2861",
        "sic_desc":"Gum and Wood Chemicals"},
      {"sic":"2865",
        "sic_desc":"Cyclic Organic Crudes and Intermediates and Organic Dyes"},
      {"sic":"2869",
        "sic_desc":"Industrial Organic Chemicals, NEC"},
      {"sic":"2873",
        "sic_desc":"Nitrogen Fertilizers"},
      {"sic":"2874",
        "sic_desc":"Phosphatic Fertilizers"},
      {"sic":"2875",
        "sic_desc":"Fertilizers, Mixing Only"},
      {"sic":"2879",
        "sic_desc":"Pesticides and Agricultural Chemicals, Not Elsewhere Classified"},
      {"sic":"2891",
        "sic_desc":"Adhesives and Sealants"},
      {"sic":"2892",
        "sic_desc":"Explosives"},
      {"sic":"2893",
        "sic_desc":"Printing Ink"},
      {"sic":"2895",
        "sic_desc":"Carbon Black"},
      {"sic":"2899",
        "sic_desc":"Chemicals and Chemical Preparations, NEC"},
      {"sic":"2911",
        "sic_desc":"Petroleum Refining"},
      {"sic":"2951",
        "sic_desc":"Paving Mixtures and Blocks"},
      {"sic":"2952",
        "sic_desc":"Asphalt Felt and Coatings"},
      {"sic":"2992",
        "sic_desc":"Lubricating Oils and Greases"},
      {"sic":"2999",
        "sic_desc":"Products Of Petroleum and Coal, Not Elsewhere Classified"},
      {"sic":"3011",
        "sic_desc":"Tires and Inner Tubes"},
      {"sic":"3021",
        "sic_desc":"Rubber and Plastics Footwear"},
      {"sic":"3052",
        "sic_desc":"Rubber and Plastics Hose and Belting"},
      {"sic":"3053",
        "sic_desc":"Gaskets, Packing, and Sealing Devices"},
      {"sic":"3061",
        "sic_desc":"Mechanical Rubber Goods"},
      {"sic":"3069",
        "sic_desc":"Fabricated Rubber Products, NEC"},
      {"sic":"3081",
        "sic_desc":"Unsupported Plastics Film and Sheet"},
      {"sic":"3082",
        "sic_desc":"Unsupported Plastics Profile Shapes"},
      {"sic":"3083",
        "sic_desc":"Laminated Plastics Plate, Sheet, and Profile Shapes"},
      {"sic":"3084",
        "sic_desc":"Plastic Pipe"},
      {"sic":"3085",
        "sic_desc":"Plastic Bottles"},
      {"sic":"3086",
        "sic_desc":"Plastics Foam Products"},
      {"sic":"3087",
        "sic_desc":"Custom Compounding Of Purchased Plastics Resins"},
      {"sic":"3088",
        "sic_desc":"Plastics Plumbing Fixtures"},
      {"sic":"3089",
        "sic_desc":"Plastics Products, NEC"},
      {"sic":"3111",
        "sic_desc":"Leather Tanning and Finishing"},
      {"sic":"3131",
        "sic_desc":"Boot & Shoe Cut Stock & Findng"},
      {"sic":"3142",
        "sic_desc":"House Slippers"},
      {"sic":"3143",
        "sic_desc":"Men's Footwear, Except Athletic"},
      {"sic":"3144",
        "sic_desc":"Women's Footwear, Except Athletic"},
      {"sic":"3149",
        "sic_desc":"Footwear, Except Rubber NEC"},
      {"sic":"3151",
        "sic_desc":"Leather Gloves and Mittens"},
      {"sic":"3161",
        "sic_desc":"Luggage"},
      {"sic":"3171",
        "sic_desc":"Women's Handbags and Purses"},
      {"sic":"3172",
        "sic_desc":"Personal Leather Goods, Exc Han"},
      {"sic":"3199",
        "sic_desc":"Leather Goods NEC"},
      {"sic":"3211",
        "sic_desc":"Flat Glass"},
      {"sic":"3221",
        "sic_desc":"Glass Containers"},
      {"sic":"3229",
        "sic_desc":"Pressed and Blown Glass and Glassware, Not Elsewhere Classified"},
      {"sic":"3231",
        "sic_desc":"Glass Products, Made Of Purchased Glass"},
      {"sic":"3241",
        "sic_desc":"Cement, Hydraulic"},
      {"sic":"3251",
        "sic_desc":"Brick and Structural Clay Tile"},
      {"sic":"3253",
        "sic_desc":"Ceramic Wall and Floor Tile"},
      {"sic":"3255",
        "sic_desc":"Clay Refractories"},
      {"sic":"3259",
        "sic_desc":"Structural Clay Products NEC"},
      {"sic":"3261",
        "sic_desc":"Vitreous China Plumbing Fixture"},
      {"sic":"3262",
        "sic_desc":"Vitreous China Table and Kitchen Articles"},
      {"sic":"3263",
        "sic_desc":"Fine Earthenware"},
      {"sic":"3463",
        "sic_desc":"Nonferrous Forgings"},
      {"sic":"5172",
        "sic_desc":"Petrol & Pet Prod Wholesalers"},
      {"sic":"5181",
        "sic_desc":"Beer and Ale"},
      {"sic":"5182",
        "sic_desc":"Wine & Dist Alcoholic Beverage"},
      {"sic":"5191",
        "sic_desc":"Farm Supplies"},
      {"sic":"5192",
        "sic_desc":"Books, Periodicals & Newspaper"},
      {"sic":"5193",
        "sic_desc":"Flowers and Florists' Supplies"},
      {"sic":"5194",
        "sic_desc":"Tobacco and Tobacco Products"},
      {"sic":"5198",
        "sic_desc":"Paints, Varnishes and Supplies"},
      {"sic":"5199",
        "sic_desc":"Nondurable Goods, NEC"},
      {"sic":"5211",
        "sic_desc":"Lumber & Build Material Dealer"},
      {"sic":"5231",
        "sic_desc":"Paint, Glass & Wallpaper Store"},
      {"sic":"5251",
        "sic_desc":"Hardware Stores"},
      {"sic":"5261",
        "sic_desc":"Ret Nurseries, Lawn/Garden Store"},
      {"sic":"5271",
        "sic_desc":"Mobile Home Dealers"},
      {"sic":"5311",
        "sic_desc":"Department Stores"},
      {"sic":"5331",
        "sic_desc":"Variety Stores"},
      {"sic":"5399",
        "sic_desc":"Miscellaneous General Stores"},
      {"sic":"5411",
        "sic_desc":"Grocery Stores"},
      {"sic":"5421",
        "sic_desc":"Meat and Fish Markets"},
      {"sic":"5431",
        "sic_desc":"Fruit and Vegetable Markets"},
      {"sic":"5441",
        "sic_desc":"Candy, Nut & Confection Stores"},
      {"sic":"5451",
        "sic_desc":"Dairy Products Stores"},
      {"sic":"5461",
        "sic_desc":"Retail Bakeries"},
      {"sic":"5499",
        "sic_desc":"Miscellaneous Food Stores"},
      {"sic":"5511",
        "sic_desc":"Motor Veh. Dealers (New/Used)"},
      {"sic":"5521",
        "sic_desc":"Motor Veh. Dealers (Used Only)"},
      {"sic":"5531",
        "sic_desc":"Auto and Home Supply Stores"},
      {"sic":"5541",
        "sic_desc":"Gasoline Service Stations"},
      {"sic":"5551",
        "sic_desc":"Boat Dealers"},
      {"sic":"5561",
        "sic_desc":"Recreational Vehicle Dealers"},
      {"sic":"5571",
        "sic_desc":"Motorcycle Dealers"},
      {"sic":"5599",
        "sic_desc":"Automotive Dealers, NEC"},
      {"sic":"5611",
        "sic_desc":"Male's Clothing & Access Store"},
      {"sic":"5621",
        "sic_desc":"Women's Clothing Stores"},
      {"sic":"5632",
        "sic_desc":"Women's Access & Spec Stores"},
      {"sic":"5641",
        "sic_desc":"Children's & Inf Wear Stores"},
      {"sic":"5651",
        "sic_desc":"Family Clothing Stores"},
      {"sic":"5661",
        "sic_desc":"Shoe Stores"},
      {"sic":"5699",
        "sic_desc":"Misc Apparel & Access Stores"},
      {"sic":"5712",
        "sic_desc":"Furniture Stores"},
      {"sic":"5713",
        "sic_desc":"Floor Covering Stores"},
      {"sic":"5714",
        "sic_desc":"Drape, Curtain & Uphol Stores"},
      {"sic":"5719",
        "sic_desc":"Misc Home furnishings Stores"},
      {"sic":"5722",
        "sic_desc":"Household Appliance Stores"},
      {"sic":"5731",
        "sic_desc":"Radio, Tv & Electronics Stores"},
      {"sic":"5734",
        "sic_desc":"Computer and Software Stores"},
      {"sic":"5735",
        "sic_desc":"Record & Prerecorded Tape Storage"},
      {"sic":"5736",
        "sic_desc":"Musical Instrument Stores"},
      {"sic":"5812",
        "sic_desc":"Eating Places"},
      {"sic":"5813",
        "sic_desc":"Drinking Places (Alcoholic Beverages)"},
      {"sic":"5912",
        "sic_desc":"Drug Stores & Proprietary Stores"},
      {"sic":"5921",
        "sic_desc":"Liquor Stores"},
      {"sic":"5932",
        "sic_desc":"Used Merchandise Stores"},
      {"sic":"5941",
        "sic_desc":"Sporting Goods/Bicycle Stores"},
      {"sic":"5942",
        "sic_desc":"Book Stores"},
      {"sic":"5943",
        "sic_desc":"Stationery Stores"},
      {"sic":"0101",
        "sic_desc":"Cocoa"},
      {"sic":"0111",
        "sic_desc":"Wheat"},
      {"sic":"0112",
        "sic_desc":"Rice"},
      {"sic":"0115",
        "sic_desc":"Corn"},
      {"sic":"0116",
        "sic_desc":"Soybeans"},
      {"sic":"0119",
        "sic_desc":"Cash Grains, NEC"},
      {"sic":"0131",
        "sic_desc":"Cotton"},
      {"sic":"0132",
        "sic_desc":"Tobacco"},
      {"sic":"0133",
        "sic_desc":"Sugarcane and Sugar Beets"},
      {"sic":"0134",
        "sic_desc":"Irish Potatoes"},
      {"sic":"0139",
        "sic_desc":"Crops, Except Cash Grains, NEC"},
      {"sic":"0161",
        "sic_desc":"Vegetables and Melons"},
      {"sic":"0171",
        "sic_desc":"Berry Crops"},
      {"sic":"0172",
        "sic_desc":"Grapes"},
      {"sic":"0173",
        "sic_desc":"Tree Nuts"},
      {"sic":"0174",
        "sic_desc":"Citrus Fruits"},
      {"sic":"0175",
        "sic_desc":"Deciduous Tree Fruits"},
      {"sic":"0179",
        "sic_desc":"Fruits and Tree Nuts, NEC"},
      {"sic":"0181",
        "sic_desc":"Ornamental Nursery Products"},
      {"sic":"0182",
        "sic_desc":"Food Crops Grown Under Cover"},
      {"sic":"0191",
        "sic_desc":"General Farms, Primarily Crop"},
      {"sic":"0211",
        "sic_desc":"Beef Cattle Feedlots"},
      {"sic":"0212",
        "sic_desc":"Beef Cattle, Except Feedlots"},
      {"sic":"0213",
        "sic_desc":"Hogs"},
      {"sic":"0214",
        "sic_desc":"Sheep and Goats"},
      {"sic":"0219",
        "sic_desc":"General Livestock, NEC"},
      {"sic":"0241",
        "sic_desc":"Dairy Farms"},
      {"sic":"0251",
        "sic_desc":"Broil, Fry and Roast Chickens"},
      {"sic":"0252",
        "sic_desc":"Chicken Eggs"},
      {"sic":"0253",
        "sic_desc":"Turkey and Turkey Eggs"},
      {"sic":"0254",
        "sic_desc":"Poultry Hatcheries"},
      {"sic":"0259",
        "sic_desc":"Poultry and Eggs, NEC"},
      {"sic":"0271",
        "sic_desc":"Fur-Bearing Animals & Rabbits"},
      {"sic":"0272",
        "sic_desc":"Horses and Other Equines"},
      {"sic":"0273",
        "sic_desc":"Animal Aquaculture"},
      {"sic":"0279",
        "sic_desc":"Animal Specialties, NEC"},
      {"sic":"0291",
        "sic_desc":"Farms, Primarily Livestock"},
      {"sic":"0711",
        "sic_desc":"Soil Preparation Services"},
      {"sic":"0721",
        "sic_desc":"Crop Planting & Protection"},
      {"sic":"0722",
        "sic_desc":"Harvesting, Primarily Machine"},
      {"sic":"0723",
        "sic_desc":"Crop Prep Services for Market"},
      {"sic":"0724",
        "sic_desc":"Cotton Ginning"},
      {"sic":"0741",
        "sic_desc":"Veterinary Services For Livestock"},
      {"sic":"0742",
        "sic_desc":"Veterinary Services For Animal Specialties"},
      {"sic":"0751",
        "sic_desc":"Livestock Services, Except Vet"},
      {"sic":"0752",
        "sic_desc":"Animal Special Serv Except Vet"},
      {"sic":"0761",
        "sic_desc":"Farm Labor Contract & Crew"},
      {"sic":"0762",
        "sic_desc":"Farm Management Services"},
      {"sic":"0781",
        "sic_desc":"Landscape Counseling and Plan"},
      {"sic":"0782",
        "sic_desc":"Lawn and Garden Services"},
      {"sic":"0783",
        "sic_desc":"Ornamental Shrub and Tree Serv"},
      {"sic":"0811",
        "sic_desc":"Timber Tracts"},
      {"sic":"0831",
        "sic_desc":"Forest Products"},
      {"sic":"0851",
        "sic_desc":"Forestry Services"},
      {"sic":"0912",
        "sic_desc":"Finfish"},
      {"sic":"0913",
        "sic_desc":"Shellfish"},
      {"sic":"0919",
        "sic_desc":"Miscellaneous Marine Products"},
      {"sic":"0921",
        "sic_desc":"Fish Hatcheries and Preserves"},
      {"sic":"0971",
        "sic_desc":"Hunt & Trap & Game Propagation"},
      {"sic":"1011",
        "sic_desc":"Iron Ores"},
      {"sic":"1021",
        "sic_desc":"Copper Ores"},
      {"sic":"1031",
        "sic_desc":"Lead and Zinc Ores"},
      {"sic":"1041",
        "sic_desc":"Gold Ores"},
      {"sic":"1044",
        "sic_desc":"Silver Ores"},
      {"sic":"1061",
        "sic_desc":"Ferroalloy Ores, Except Vanadium"},
      {"sic":"1081",
        "sic_desc":"Metal Mining Services"},
      {"sic":"1094",
        "sic_desc":"Uranium-Radium-Vanadium Ores"},
      {"sic":"1099",
        "sic_desc":"Metal Ores, NEC"},
      {"sic":"3264",
        "sic_desc":"Porcelain Electrical Supplies"},
      {"sic":"3269",
        "sic_desc":"Pottery Products, NEC"},
      {"sic":"3271",
        "sic_desc":"Concrete Block & Brick"},
      {"sic":"1221",
        "sic_desc":"Bituminous Coal and Lignite Surface Mining"},
      {"sic":"1222",
        "sic_desc":"Bituminous Coal Underground Mining"},
      {"sic":"1231",
        "sic_desc":"Anthracite Mining"},
      {"sic":"1241",
        "sic_desc":"Coal Mining Service"},
      {"sic":"1311",
        "sic_desc":"Crude Petroleum & Natural Gas"},
      {"sic":"1321",
        "sic_desc":"Natural Gas Liquids"},
      {"sic":"1381",
        "sic_desc":"Drilling Oil and Gas Wells"},
      {"sic":"1382",
        "sic_desc":"Oil and Gas Field Exploration"},
      {"sic":"1389",
        "sic_desc":"Oil And & Field Services, NEC"},
      {"sic":"1411",
        "sic_desc":"Dimension Stone"},
      {"sic":"1422",
        "sic_desc":"Crushed and Broken Limestone"},
      {"sic":"1423",
        "sic_desc":"Crushed and Broken Granite"},
      {"sic":"1429",
        "sic_desc":"Crushed and Broken Stone, NEC"},
      {"sic":"1442",
        "sic_desc":"Construction Sand and Gravel"},
      {"sic":"1446",
        "sic_desc":"Industrial Sand"},
      {"sic":"1455",
        "sic_desc":"Kaolin and Ball Clay"},
      {"sic":"1459",
        "sic_desc":"Clay, Ceramic, and Refractory Minerals, Not Elsewhere Classified"},
      {"sic":"1474",
        "sic_desc":"Potash, Soda & Borate Minerals"},
      {"sic":"1475",
        "sic_desc":"Phosphate Rock"},
      {"sic":"1479",
        "sic_desc":"Chem & Fert Minera Mining, NEC"},
      {"sic":"1481",
        "sic_desc":"Nonmetal Mineral (Except Fuels)"},
      {"sic":"1499",
        "sic_desc":"Misc Nonmetal Minerals, NEC"},
      {"sic":"1521",
        "sic_desc":"Single-family Housing Construction"},
      {"sic":"1522",
        "sic_desc":"Residential Construction, NEC"},
      {"sic":"1531",
        "sic_desc":"Operative Builders"},
      {"sic":"1541",
        "sic_desc":"Gen Contract-Industrial Buildings"},
      {"sic":"1542",
        "sic_desc":"Gen Contract, Non-Residential Buildings"},
      {"sic":"1611",
        "sic_desc":"Highway and Street Construction"},
      {"sic":"1622",
        "sic_desc":"Bridge, Tunnel, and Elevated Highway Construction"},
      {"sic":"1623",
        "sic_desc":"Water, Sewer, and Utility Lines"},
      {"sic":"1629",
        "sic_desc":"Heavy Construction, NEC"},
      {"sic":"1711",
        "sic_desc":"Plumb, Heat & Air Conditioning"},
      {"sic":"1721",
        "sic_desc":"Painting and Paper Hanging"},
      {"sic":"1731",
        "sic_desc":"Electrical Work"},
      {"sic":"1741",
        "sic_desc":"Masonry, Stone Set, Stonework"},
      {"sic":"1742",
        "sic_desc":"Plstr, Drywall, Acous, & Insul"},
      {"sic":"1743",
        "sic_desc":"Terrazzo, Tile, Marble, Mosaic"},
      {"sic":"1751",
        "sic_desc":"Carpentry Work"},
      {"sic":"1752",
        "sic_desc":"Floor Lay & Other Floor Work"},
      {"sic":"1761",
        "sic_desc":"Roof, Side & Sheet Metal Work"},
      {"sic":"1771",
        "sic_desc":"Concrete Work"},
      {"sic":"1781",
        "sic_desc":"Water Well Drilling"},
      {"sic":"1791",
        "sic_desc":"Structural Steel Erection"},
      {"sic":"1793",
        "sic_desc":"Glass and Glazing Work"},
      {"sic":"1794",
        "sic_desc":"Excavation Work"},
      {"sic":"1795",
        "sic_desc":"Wrecking and Demolition Work"},
      {"sic":"1796",
        "sic_desc":"Inst Or Erection of Bldg Equip"},
      {"sic":"1799",
        "sic_desc":"Special Trade Contractors, NEC"},
      {"sic":"2011",
        "sic_desc":"Meat Packing Plants"},
      {"sic":"2013",
        "sic_desc":"Sausages & Prepared Meat Products"},
      {"sic":"2015",
        "sic_desc":"Poultry Slaughtering and Processing"},
      {"sic":"2021",
        "sic_desc":"Creamery Butter"},
      {"sic":"2022",
        "sic_desc":"Cheese, Natural and Processed"},
      {"sic":"2023",
        "sic_desc":"Condensed and Evaporated Milk"},
      {"sic":"2024",
        "sic_desc":"Ice Cream and Frozen Desserts"},
      {"sic":"2026",
        "sic_desc":"Fluid Milk"},
      {"sic":"2032",
        "sic_desc":"Canned Specialties"},
      {"sic":"2033",
        "sic_desc":"Canned Fruits, Vegetables, Preserves, Jams, and Jellies"},
      {"sic":"2034",
        "sic_desc":"Dehydrated Fruits, Veg, Soups"},
      {"sic":"2035",
        "sic_desc":"Pickled Fruits & Vegetable Sauces"},
      {"sic":"2037",
        "sic_desc":"Frozen Fruits, Fruit Juices, and Vegetables"},
      {"sic":"2038",
        "sic_desc":"Frozen Specialties, NEC"},
      {"sic":"2041",
        "sic_desc":"Flour & Other Grain Mill Products"},
      {"sic":"2043",
        "sic_desc":"Cereal Breakfast Foods"},
      {"sic":"2044",
        "sic_desc":"Rice Milling"},
      {"sic":"2045",
        "sic_desc":"Blended and Prepared Flour"},
      {"sic":"2046",
        "sic_desc":"Wet Corn Milling"},
      {"sic":"2047",
        "sic_desc":"Dog and Cat Food"},
      {"sic":"2048",
        "sic_desc":"Prepared Feeds"},
      {"sic":"2051",
        "sic_desc":"Bread & Other Bakery Products"},
      {"sic":"2052",
        "sic_desc":"Cookies and Crackers"},
      {"sic":"2053",
        "sic_desc":"Frozen Bakery Products"},
      {"sic":"2061",
        "sic_desc":"Cane Sugar, Except Refine Only"},
      {"sic":"2062",
        "sic_desc":"Cane Sugar Refining"},
      {"sic":"2063",
        "sic_desc":"Beet Sugar"},
      {"sic":"2064",
        "sic_desc":"Candy & Other Confection Products"},
      {"sic":"2066",
        "sic_desc":"Chocolate and Cocoa Products"},
      {"sic":"2067",
        "sic_desc":"Chewing Gum"},
      {"sic":"2068",
        "sic_desc":"Salted & Roasted Nuts & Seeds"},
      {"sic":"2074",
        "sic_desc":"Cottonseed Oil Mills"},
      {"sic":"2075",
        "sic_desc":"Soybean Oil Mills"},
      {"sic":"2076",
        "sic_desc":"Veg. Oil Mills, Except Corn"},
      {"sic":"2077",
        "sic_desc":"Animal and Marine Fats & Oils"},
      {"sic":"2079",
        "sic_desc":"Short, Table Oils, Margarine"},
      {"sic":"2082",
        "sic_desc":"Malt Beverages"},
      {"sic":"2083",
        "sic_desc":"Malt"},
      {"sic":"2084",
        "sic_desc":"Wines, Brandy & Brandy Spirit"},
      {"sic":"2085",
        "sic_desc":"Dist, Rectified & Blended Liq"},
      {"sic":"2086",
        "sic_desc":"Bot & Can Soft Drnk & Carb Wa"},
      {"sic":"2087",
        "sic_desc":"Flav Extr & Flav Syrups, NEC"},
      {"sic":"2091",
        "sic_desc":"Canned & Cured Fish & Seafood"},
      {"sic":"2092",
        "sic_desc":"Prepared Fresh Or Frozen Fish and Seafoods"},
      {"sic":"2095",
        "sic_desc":"Roasted Coffee"},
      {"sic":"2096",
        "sic_desc":"Potato Chips & Similar Snacks"},
      {"sic":"2097",
        "sic_desc":"Manufactured Ice"},
      {"sic":"2098",
        "sic_desc":"Macaroni, Spagh, Vermi, Noodl"},
      {"sic":"2099",
        "sic_desc":"Food Preparations, NEC"},
      {"sic":"2111",
        "sic_desc":"Cigarettes"},
      {"sic":"2121",
        "sic_desc":"Cigars"},
      {"sic":"2131",
        "sic_desc":"Tobacco (Chew & Smok) & Snuff"},
      {"sic":"2141",
        "sic_desc":"Tobacco Stemming and Redrying"},
      {"sic":"2211",
        "sic_desc":"Broad Woven Fabric Mills, Cotton"},
      {"sic":"2221",
        "sic_desc":"Broad Woven Fabric Mills, Synthetic"},
      {"sic":"2231",
        "sic_desc":"Broad Woven Fabric Mills, Wool"},
      {"sic":"2241",
        "sic_desc":"Narrow Fabric and Other Smallwares Mills"},
      {"sic":"2251",
        "sic_desc":"Women's Full-length and Knee-length Hosiery, Except Socks"},
      {"sic":"2252",
        "sic_desc":"Hosiery, NEC"},
      {"sic":"2253",
        "sic_desc":"Knit Outerwear Mills"},
      {"sic":"2254",
        "sic_desc":"Knit Underwear Mills"},
      {"sic":"2257",
        "sic_desc":"Circular Knit Fabric Mills"},
      {"sic":"2258",
        "sic_desc":"Warp Knit Fabric Mills"},
      {"sic":"2259",
        "sic_desc":"Knitting Mills, NEC"},
      {"sic":"2261",
        "sic_desc":"Finishers Of Broadwoven Fabrics Of Cotton"},
      {"sic":"2262",
        "sic_desc":"Finishers Of Broadwoven Fabrics Of Manmade Fiber and Silk"},
      {"sic":"2269",
        "sic_desc":"Finishers of Textiles, NEC"},
      {"sic":"2273",
        "sic_desc":"Carpets and Rugs, NEC"},
      {"sic":"3581",
        "sic_desc":"Automatic Merchandising Machine"},
      {"sic":"3582",
        "sic_desc":"Commercial Laundry Equipment"},
      {"sic":"3585",
        "sic_desc":"Air-Conditioning, Warm Air Heating, and Refrigeration Equipment"},
      {"sic":"3586",
        "sic_desc":"Measuring & Dispensing Pumps"},
      {"sic":"3589",
        "sic_desc":"Service Industry Machinery"},
      {"sic":"3592",
        "sic_desc":"Carburetors, Pistons, Rings, Valves"},
      {"sic":"3593",
        "sic_desc":"Fluid Power Cylinders & Actuators"},
      {"sic":"3594",
        "sic_desc":"Fluid Power Pumps and Motors"},
      {"sic":"3596",
        "sic_desc":"Scales and Balances, Except Laboratory"},
      {"sic":"3599",
        "sic_desc":"Industrial Machinery, NEC"},
      {"sic":"3612",
        "sic_desc":"Transformers"},
      {"sic":"3613",
        "sic_desc":"Switchgear & Switchboard Apparatus"},
      {"sic":"3621",
        "sic_desc":"Motors and Generators"},
      {"sic":"3624",
        "sic_desc":"Carbon and Graphite Products"},
      {"sic":"3625",
        "sic_desc":"Relays and Industrial Controls"},
      {"sic":"3629",
        "sic_desc":"Electrical Industrial Apparatus, Not Elsewhere Classified"},
      {"sic":"3631",
        "sic_desc":"Household Cooking Equipment"},
      {"sic":"3632",
        "sic_desc":"Household Refrigerators and Home and Farm Freezers"},
      {"sic":"3633",
        "sic_desc":"Household Laundry Equipment"},
      {"sic":"3634",
        "sic_desc":"Electric Housewares and Fans"},
      {"sic":"3635",
        "sic_desc":"Household Vacuum Cleaners"},
      {"sic":"3639",
        "sic_desc":"Household Appliances, NEC"},
      {"sic":"3641",
        "sic_desc":"Electric Lamps"},
      {"sic":"3643",
        "sic_desc":"Current-Carrying Wiring Device"},
      {"sic":"3644",
        "sic_desc":"Noncurrent-Carrying Wiring Device"},
      {"sic":"3645",
        "sic_desc":"Residential Lighting Fixtures"},
      {"sic":"3646",
        "sic_desc":"Commercial Lighting Fixtures"},
      {"sic":"3647",
        "sic_desc":"Vehicular Lighting Equipment"},
      {"sic":"3648",
        "sic_desc":"Lighting Equipment, NEC"},
      {"sic":"3651",
        "sic_desc":"Radio and Tv Receiving Sets"},
      {"sic":"3652",
        "sic_desc":"Phonograph Records"},
      {"sic":"3661",
        "sic_desc":"Telephone and Telegraph Apparatus"},
      {"sic":"3663",
        "sic_desc":"Radio and Television Broadcasting and Communications Equipment"},
      {"sic":"3669",
        "sic_desc":"Communications Equipment, NEC"},
      {"sic":"3671",
        "sic_desc":"Electron Tubes"},
      {"sic":"3672",
        "sic_desc":"Printed Circut Board"},
      {"sic":"3674",
        "sic_desc":"Semiconductors & Related Devices"},
      {"sic":"3675",
        "sic_desc":"Electronic Capacitors"},
      {"sic":"3676",
        "sic_desc":"Electronic Resistors"},
      {"sic":"3677",
        "sic_desc":"Electronic Coils, Transformers, and Other Inductors"},
      {"sic":"3678",
        "sic_desc":"Electronic Connectors"},
      {"sic":"3679",
        "sic_desc":"Electronic Components, NEC"},
      {"sic":"3691",
        "sic_desc":"Storage Batteries"},
      {"sic":"3692",
        "sic_desc":"Primary Batteries, Dry & Wet"},
      {"sic":"3694",
        "sic_desc":"Electrical Equipment For Internal Combustion Engines"},
      {"sic":"3695",
        "sic_desc":"Magnetic and Optical Recording Media"},
      {"sic":"3699",
        "sic_desc":"Electrical Machinery, Equipment, and Supplies, NEC"},
      {"sic":"3711",
        "sic_desc":"Motor Vehicles & Car Bodies"},
      {"sic":"3713",
        "sic_desc":"Truck & Bus Bodies"},
      {"sic":"3714",
        "sic_desc":"Motor Vehicle Parts and Accessories"},
      {"sic":"3715",
        "sic_desc":"Truck Trailers"},
      {"sic":"3716",
        "sic_desc":"Motor Homes"},
      {"sic":"3721",
        "sic_desc":"Aircraft"},
      {"sic":"3724",
        "sic_desc":"Aircraft Engines & Engine Parts"},
      {"sic":"3728",
        "sic_desc":"Aircraft Parts and Auxiliary Equipment, Not Elsewhere Classified"},
      {"sic":"3731",
        "sic_desc":"Ship Building and Repairing"},
      {"sic":"3272",
        "sic_desc":"Concrete Products, Except Block and Brick"},
      {"sic":"3273",
        "sic_desc":"Ready-Mixed Concrete"},
      {"sic":"3274",
        "sic_desc":"Lime"},
      {"sic":"3275",
        "sic_desc":"Gypsum Products"},
      {"sic":"3281",
        "sic_desc":"Cut Stone & Stone Products"},
      {"sic":"3291",
        "sic_desc":"Abrasive Products"},
      {"sic":"3292",
        "sic_desc":"Asbestos Products"},
      {"sic":"3295",
        "sic_desc":"Minerals and Earths, Ground Or Otherwise Treated"},
      {"sic":"3296",
        "sic_desc":"Mineral Wool"},
      {"sic":"3297",
        "sic_desc":"Nonclay Refractories"},
      {"sic":"3299",
        "sic_desc":"Nonmetallic Mineral Products, Not Elsewhere Classified"},
      {"sic":"3312",
        "sic_desc":"Steel Works, Blast Furnaces, and Rolling Mills"},
      {"sic":"3313",
        "sic_desc":"Electrometallurgical Products"},
      {"sic":"3315",
        "sic_desc":"Steel Wire Draw & Steel Nails"},
      {"sic":"3316",
        "sic_desc":"Cold-Rolled Steel Sheet, Strip, and Bars"},
      {"sic":"3317",
        "sic_desc":"Steel Pipe and Tubes"},
      {"sic":"3321",
        "sic_desc":"Gray Iron Foundries"},
      {"sic":"3322",
        "sic_desc":"Malleable Iron Foundries"},
      {"sic":"3324",
        "sic_desc":"Steel Investment Foundries"},
      {"sic":"3325",
        "sic_desc":"Steel Foundries, NEC"},
      {"sic":"3331",
        "sic_desc":"Primary Smelting and Refining Of Copper"},
      {"sic":"3334",
        "sic_desc":"Primary Production of Aluminum"},
      {"sic":"3339",
        "sic_desc":"Primary Smelting and Refining Of Nonferrous Metals"},
      {"sic":"3341",
        "sic_desc":"Secondary Smelting and Refining Of Nonferrous Metals"},
      {"sic":"3351",
        "sic_desc":"Rolling, Drawing, and Extruding Of Copper"},
      {"sic":"3353",
        "sic_desc":"Aluminum Sheet, Plate and Foil"},
      {"sic":"3354",
        "sic_desc":"Aluminum Extruded Products"},
      {"sic":"3355",
        "sic_desc":"Aluminum Rolling & Drawing NEC"},
      {"sic":"3356",
        "sic_desc":"Roll, Draw & Extrud Nonferrous"},
      {"sic":"3357",
        "sic_desc":"Drawing and Insulating Of Nonferrous Wire"},
      {"sic":"3363",
        "sic_desc":"Aluminum Die Casting"},
      {"sic":"3364",
        "sic_desc":"Nonferrous Die-Castings, Except Aluminum"},
      {"sic":"3365",
        "sic_desc":"Aluminum Foundries"},
      {"sic":"3366",
        "sic_desc":"Copper Foundries"},
      {"sic":"3369",
        "sic_desc":"Nonferrous Foundries, Except Aluminum and Copper"},
      {"sic":"3398",
        "sic_desc":"Metal Heat Treating"},
      {"sic":"3399",
        "sic_desc":"Primary Metal Products, NEC"},
      {"sic":"3411",
        "sic_desc":"Metal Cans"},
      {"sic":"3412",
        "sic_desc":"Metal Barrels, Drums and Pails"},
      {"sic":"3421",
        "sic_desc":"Cutlery"},
      {"sic":"3423",
        "sic_desc":"Hand and Edge Tools, NEC"},
      {"sic":"3425",
        "sic_desc":"Hand Saws and Saw Blades"},
      {"sic":"3429",
        "sic_desc":"Hardware, NEC"},
      {"sic":"3431",
        "sic_desc":"Metal Sanitary Ware"},
      {"sic":"3432",
        "sic_desc":"Plumb Fixture Fittings & Trim"},
      {"sic":"3433",
        "sic_desc":"Heating Equipment, Except Electric and Warm Air Furnaces"},
      {"sic":"3441",
        "sic_desc":"Fabricated Structural Metal"},
      {"sic":"3442",
        "sic_desc":"Metal Doors, Sash, And Trim"},
      {"sic":"3443",
        "sic_desc":"Fabricated Plate Work (Boiler Shops)"},
      {"sic":"3444",
        "sic_desc":"Sheet Metal Work"},
      {"sic":"3446",
        "sic_desc":"Architectural Metal Work"},
      {"sic":"3448",
        "sic_desc":"Prefabricated Metal Buildings"},
      {"sic":"3449",
        "sic_desc":"Miscellaneous Structural Metal Work"},
      {"sic":"3451",
        "sic_desc":"Screw Machine Products"},
      {"sic":"3452",
        "sic_desc":"Bolts, Nuts, Rivets & Washers"},
      {"sic":"3462",
        "sic_desc":"Iron and Steel Forgings"},
      {"sic":"5944",
        "sic_desc":"Jewelry Stores"},
      {"sic":"5945",
        "sic_desc":"Hobby, Toy and Game Shops"},
      {"sic":"5946",
        "sic_desc":"Camera & Photo Supply Stores"},
      {"sic":"5947",
        "sic_desc":"Gift, Novelty & Souvenir Shops"},
      {"sic":"5948",
        "sic_desc":"Luggage & Leather Goods Stores"},
      {"sic":"5949",
        "sic_desc":"Sew/Needlewk/Piece Goods Store"},
      {"sic":"5961",
        "sic_desc":"Catalog and Mail-Order Houses"},
      {"sic":"5962",
        "sic_desc":"Auto Merchandis Machine Operat"},
      {"sic":"5963",
        "sic_desc":"Direct Selling Establishments"},
      {"sic":"5983",
        "sic_desc":"Fuel Oil Dealers"},
      {"sic":"5984",
        "sic_desc":"Liq Petrol Gas (Bot Gas) Dealr"},
      {"sic":"5989",
        "sic_desc":"Fuel Dealers, NEC"},
      {"sic":"5992",
        "sic_desc":"Florists"},
      {"sic":"5993",
        "sic_desc":"Tobacco Stores and Stands"},
      {"sic":"5994",
        "sic_desc":"News Dealers and Newsstands"},
      {"sic":"5995",
        "sic_desc":"Optical Goods Stores"},
      {"sic":"5999",
        "sic_desc":"Miscellaneous Retail Stores"},
      {"sic":"6011",
        "sic_desc":"Federal Reserve Banks"},
      {"sic":"6019",
        "sic_desc":"Central Reserve Repository"},
      {"sic":"6021",
        "sic_desc":"National Commercial Banks"},
      {"sic":"6022",
        "sic_desc":"State Commercial Banks"},
      {"sic":"6029",
        "sic_desc":"Commercial Banks, NEC"},
      {"sic":"6035",
        "sic_desc":"Federal Savings Institutions"},
      {"sic":"6036",
        "sic_desc":"Savings Institutions, Exc Fed"},
      {"sic":"6061",
        "sic_desc":"Federal Credit Unions"},
      {"sic":"6062",
        "sic_desc":"State Credit Unions"},
      {"sic":"6081",
        "sic_desc":"Foreign Bank & Branches & Agen"},
      {"sic":"6082",
        "sic_desc":"Foreign Trade & Internat Banks"},
      {"sic":"6091",
        "sic_desc":"Nondeposit Trust Facilties"},
      {"sic":"6099",
        "sic_desc":"Funct Related to Dep Banking"},
      {"sic":"6111",
        "sic_desc":"Federal & Fed-Sponsored Credit"},
      {"sic":"6141",
        "sic_desc":"Personal Credit Institutions"},
      {"sic":"6153",
        "sic_desc":"Short-Term Bus. Credit Institu"},
      {"sic":"6159",
        "sic_desc":"Misc Business Credit Instituti"},
      {"sic":"6162",
        "sic_desc":"Mortg Bankers & Loan Correspon"},
      {"sic":"6163",
        "sic_desc":"Loan Brokers"},
      {"sic":"6211",
        "sic_desc":"Sec Brokers/Dealers/Flotat. Co"},
      {"sic":"6221",
        "sic_desc":"Commodity Contr Brokers & Deal"},
      {"sic":"6231",
        "sic_desc":"Security & Commodity Exchanges"},
      {"sic":"6282",
        "sic_desc":"Investment Advice"},
      {"sic":"6289",
        "sic_desc":"Security & Commodity Services"},
      {"sic":"6311",
        "sic_desc":"Life Insurance"},
      {"sic":"6321",
        "sic_desc":"Accident and Health Insurance"},
      {"sic":"6324",
        "sic_desc":"Hospital & Medical Serv Plans"},
      {"sic":"6331",
        "sic_desc":"Fire, Marine & Casualty Insur"},
      {"sic":"6351",
        "sic_desc":"Surety Insurance"},
      {"sic":"6361",
        "sic_desc":"Title Insurance"},
      {"sic":"6371",
        "sic_desc":"Pension, Health & Welfare Fund"},
      {"sic":"6399",
        "sic_desc":"Insurance Carriers, NEC"},
      {"sic":"6411",
        "sic_desc":"Insur Agents, Brokers, & Servi"},
      {"sic":"6512",
        "sic_desc":"Oper Of Nonresidential Bldgs"},
      {"sic":"6513",
        "sic_desc":"Operators of Apart Buildings"},
      {"sic":"6514",
        "sic_desc":"Oper Of Dwell Other Than Apart"},
      {"sic":"6515",
        "sic_desc":"Oper Of Res Mobile Home Sites"},
      {"sic":"6517",
        "sic_desc":"Lessors of Railroad Properties"},
      {"sic":"6519",
        "sic_desc":"Lessors of Real Property, NEC"},
      {"sic":"6531",
        "sic_desc":"Real Estate Agents & Managers"},
      {"sic":"6541",
        "sic_desc":"Title Abstract Offices"},
      {"sic":"6552",
        "sic_desc":"Land Subdividers & Dev, Ex Cem"},
      {"sic":"6553",
        "sic_desc":"Cemetery Subdividers & Develop"},
      {"sic":"6712",
        "sic_desc":"Bank Holding Companies"},
      {"sic":"6719",
        "sic_desc":"Holding Companies, NEC"},
      {"sic":"6722",
        "sic_desc":"Mgmt Invest. Offices, Open End"},
      {"sic":"6726",
        "sic_desc":"Investment Offices, NEC"},
      {"sic":"6732",
        "sic_desc":"Educat., Relig & Charity Trusts"},
      {"sic":"6733",
        "sic_desc":"Trusts, Exc Educat, Relig & Char"},
      {"sic":"6792",
        "sic_desc":"Oil Royalty Traders"},
      {"sic":"6794",
        "sic_desc":"Patent Owners and Lessors"},
      {"sic":"6798",
        "sic_desc":"Real Estate Investment Trusts"},
      {"sic":"6799",
        "sic_desc":"Investors, NEC"},
      {"sic":"7011",
        "sic_desc":"Hotels and Motels"},
      {"sic":"7021",
        "sic_desc":"Rooming and Boarding Houses"},
      {"sic":"7032",
        "sic_desc":"Sporting & Recreational Camps"},
      {"sic":"7033",
        "sic_desc":"Rec Vehicle Parks & Campsites"},
      {"sic":"7041",
        "sic_desc":"Org. Hotel & Lodg Hse, On Memb"},
      {"sic":"7211",
        "sic_desc":"Power Laundries, Res & Commerc"},
      {"sic":"7212",
        "sic_desc":"Garm Pressing/Laundries/Drycle"},
      {"sic":"7213",
        "sic_desc":"Linen Supply"},
      {"sic":"7215",
        "sic_desc":"Coin-Operated Laundries/Drycle"},
      {"sic":"7216",
        "sic_desc":"Dryclean Plants, Exc Rug Clean"},
      {"sic":"7217",
        "sic_desc":"Carpet & Upholstery Cleaning"},
      {"sic":"7218",
        "sic_desc":"Industrial Launderers"},
      {"sic":"7219",
        "sic_desc":"Laundry & Garment Services, NEC"},
      {"sic":"7221",
        "sic_desc":"Photographic Studios, Potrait"},
      {"sic":"7231",
        "sic_desc":"Beauty Shops"},
      {"sic":"7241",
        "sic_desc":"Barber Shops"},
      {"sic":"7251",
        "sic_desc":"Shoe Rep Shops & Shoeshine Par"},
      {"sic":"7261",
        "sic_desc":"Funeral Services & Crematories"},
      {"sic":"7291",
        "sic_desc":"Tax and Preparation Services"},
      {"sic":"7299",
        "sic_desc":"Miscellaneous Personal Service"},
      {"sic":"7311",
        "sic_desc":"Advertising Agencies"},
      {"sic":"7312",
        "sic_desc":"Outdoor Advertising Agencies"},
      {"sic":"7313",
        "sic_desc":"Radio, Tv & Publishers Ad Reps"},
      {"sic":"7319",
        "sic_desc":"Advertising, NEC"},
      {"sic":"7322",
        "sic_desc":"Adjustment & Collect Services"},
      {"sic":"7323",
        "sic_desc":"Credit Reporting Services"},
      {"sic":"7331",
        "sic_desc":"Direct Mail Advertis Services"},
      {"sic":"7334",
        "sic_desc":"Photocopying/Duplicating Serv"},
      {"sic":"7335",
        "sic_desc":"Commercial Photography"},
      {"sic":"7336",
        "sic_desc":"Commercial Art and Graphic Design"},
      {"sic":"7338",
        "sic_desc":"Secretarial & Court Reporting"},
      {"sic":"7342",
        "sic_desc":"Disinfecting & Exterminat Serv"},
      {"sic":"7349",
        "sic_desc":"Building Maintnenance Service"},
      {"sic":"7352",
        "sic_desc":"Medical Equipment Rental"},
      {"sic":"7353",
        "sic_desc":"Heavy Construction Equip Rental"},
      {"sic":"7359",
        "sic_desc":"Equipment Rental and Leasing,"},
      {"sic":"7361",
        "sic_desc":"Employment Agencies"},
      {"sic":"7363",
        "sic_desc":"Help Supply Services"},
      {"sic":"7371",
        "sic_desc":"Custom Computer Prog Services"},
      {"sic":"7372",
        "sic_desc":"Prepackaged Software"},
      {"sic":"7373",
        "sic_desc":"Computer Integrated Sys Design"},
      {"sic":"7374",
        "sic_desc":"Data Processing & Preparation"},
      {"sic":"7375",
        "sic_desc":"Information Retrieval Services"},
      {"sic":"7376",
        "sic_desc":"Computer Facilities Management"},
      {"sic":"7377",
        "sic_desc":"Computer Rental and Leasing"},
      {"sic":"7378",
        "sic_desc":"Computer Maintenance & Repair"},
      {"sic":"7379",
        "sic_desc":"Computer Related Services, NEC"},
      {"sic":"7381",
        "sic_desc":"Detective & Armored Car Servic"},
      {"sic":"7382",
        "sic_desc":"Security Systems Services"},
      {"sic":"7383",
        "sic_desc":"News Syndicates"},
      {"sic":"7384",
        "sic_desc":"Photofinishing Laboratories"},
      {"sic":"7389",
        "sic_desc":"Business Services, NEC"},
      {"sic":"7513",
        "sic_desc":"Truck Rent & Lease, No Drivers"},
      {"sic":"7514",
        "sic_desc":"Passenger Car Rental"},
      {"sic":"7515",
        "sic_desc":"Passenger Car Leasing"},
      {"sic":"7519",
        "sic_desc":"Utility Trailer & RV Rental"},
      {"sic":"7521",
        "sic_desc":"Automobile Parking"},
      {"sic":"7532",
        "sic_desc":"Top & Body Repair & Paint Shop"},
      {"sic":"7533",
        "sic_desc":"Auto Exhaust System Rep Shops"},
      {"sic":"7534",
        "sic_desc":"Tire Retreading & Repair Shops"},
      {"sic":"7536",
        "sic_desc":"Auto Glass Replacement Shops"},
      {"sic":"7537",
        "sic_desc":"Auto Transmission Repair Shops"},
      {"sic":"7538",
        "sic_desc":"General Auto Repair Shops"},
      {"sic":"7539",
        "sic_desc":"Automotive Repair Shops, NEC"},
      {"sic":"7542",
        "sic_desc":"Car Washes"},
      {"sic":"7549",
        "sic_desc":"Auto Serv, Exc Rep & Carwashes"},
      {"sic":"7622",
        "sic_desc":"Radio & Television Repair Shop"},
      {"sic":"7623",
        "sic_desc":"Refrig & Ac Serv & Rep Shops"},
      {"sic":"7629",
        "sic_desc":"Elec & Electronic Repair Shops"},
      {"sic":"7631",
        "sic_desc":"Watch, Clock & Jewelry Repair"},
      {"sic":"7641",
        "sic_desc":"Reupholstery & Furniture Rep"},
      {"sic":"7692",
        "sic_desc":"Welding Repair"},
      {"sic":"7694",
        "sic_desc":"Armature Rewinding Shops"},
      {"sic":"7699",
        "sic_desc":"Repair Shops & Related Service"},
      {"sic":"7812",
        "sic_desc":"Motion Picture & Video Prod"},
      {"sic":"7819",
        "sic_desc":"Services Allied to Motion Pictures"},
      {"sic":"7822",
        "sic_desc":"Motion Picture & Tape Distrib"},
      {"sic":"7829",
        "sic_desc":"Serv Allied to Motion Pic Dist"},
      {"sic":"7832",
        "sic_desc":"Motion Pic Thea., Ex Drive-In"},
      {"sic":"7833",
        "sic_desc":"Drive-In Motion Pic Theatres"},
      {"sic":"7841",
        "sic_desc":"Video Tape Rental"},
      {"sic":"7911",
        "sic_desc":"Dance Studios, Schools & Halls"},
      {"sic":"7922",
        "sic_desc":"Thea. Prod (Exc Motion Picture"},
      {"sic":"7929",
        "sic_desc":"Bands, Orch, Actors & Entertai"},
      {"sic":"7933",
        "sic_desc":"Bowling Centers"},
      {"sic":"7941",
        "sic_desc":"Prof Sports Clubs & Promoters"},
      {"sic":"7948",
        "sic_desc":"Racing, Including Track Opera"},
      {"sic":"7991",
        "sic_desc":"Physical Fitness Facilities"},
      {"sic":"7992",
        "sic_desc":"Public Golf Courses"},
      {"sic":"7993",
        "sic_desc":"Coin Operated Amusement Devi"},
      {"sic":"7996",
        "sic_desc":"Amusement Parks"},
      {"sic":"7997",
        "sic_desc":"Membership Sports & Rec Clubs"},
      {"sic":"7999",
        "sic_desc":"Amusement and Recreation, NEC"},
      {"sic":"8011",
        "sic_desc":"Offices and Clinics Of Doctors Of Medicine"},
      {"sic":"8021",
        "sic_desc":"Offices and Clinics of Dentists"},
      {"sic":"8031",
        "sic_desc":"Offices and Clinics Of Doctors Of Osteopathy"},
      {"sic":"8041",
        "sic_desc":"Offices and Clinics Of Chiropractors"},
      {"sic":"8042",
        "sic_desc":"Offices and Clinics Of Optometrists"},
      {"sic":"8043",
        "sic_desc":"Offices and Clinics Of Podiatrists"},
      {"sic":"8049",
        "sic_desc":"Offices of Health Practitioner"},
      {"sic":"8051",
        "sic_desc":"Skilled Nursing Care Facilities"},
      {"sic":"8052",
        "sic_desc":"Intermediate Care Facilities"},
      {"sic":"8059",
        "sic_desc":"Nursing and Personal Care, NEC"},
      {"sic":"8062",
        "sic_desc":"General Medical and Surgical Hospitals"},
      {"sic":"8063",
        "sic_desc":"Psychiatric Hospitals"},
      {"sic":"8069",
        "sic_desc":"Specialty Hospitals"},
      {"sic":"8071",
        "sic_desc":"Medical Laboratories"},
      {"sic":"8072",
        "sic_desc":"Dental Laboratories"},
      {"sic":"8082",
        "sic_desc":"Home Health Care Services"},
      {"sic":"8092",
        "sic_desc":"Kidney Dialysis Centers"},
      {"sic":"8093",
        "sic_desc":"Specialty Outpatient Clinics"},
      {"sic":"8099",
        "sic_desc":"Health & Allied Services, NEC"},
      {"sic":"8111",
        "sic_desc":"Legal Services"},
      {"sic":"8211",
        "sic_desc":"Elementary & Secondary Schools"},
      {"sic":"8221",
        "sic_desc":"Colleges, Univ & Prof Schools"},
      {"sic":"8222",
        "sic_desc":"Junior Colleges & Tech Institu"},
      {"sic":"8231",
        "sic_desc":"Libraries"},
      {"sic":"8243",
        "sic_desc":"Data Processing Schools"},
      {"sic":"8244",
        "sic_desc":"Business & Secretarial Schools"},
      {"sic":"8249",
        "sic_desc":"Vocational Schools, NEC"},
      {"sic":"8299",
        "sic_desc":"Schools & Educational Services"},
      {"sic":"8322",
        "sic_desc":"Individual and Family Services"},
      {"sic":"8331",
        "sic_desc":"Job Training & Voc Rehab Servi"},
      {"sic":"8351",
        "sic_desc":"Child Day Care Services"},
      {"sic":"8361",
        "sic_desc":"Residential Care"},
      {"sic":"8399",
        "sic_desc":"Social Services, NEC"},
      {"sic":"8412",
        "sic_desc":"Museums and Art Galleries"},
      {"sic":"8422",
        "sic_desc":"Botanical & Zoological Gardens"},
      {"sic":"8611",
        "sic_desc":"Business Associations"},
      {"sic":"8621",
        "sic_desc":"Professional Membership Organ"},
      {"sic":"8631",
        "sic_desc":"Labor Unions & Labor Organiza"},
      {"sic":"8641",
        "sic_desc":"Civic, Social & Fraternal Ass."},
      {"sic":"8651",
        "sic_desc":"Political Organizations"},
      {"sic":"8661",
        "sic_desc":"Religious Organizations"},
      {"sic":"8699",
        "sic_desc":"Membership Organizations, NEC"},
      {"sic":"8711",
        "sic_desc":"Engineering Services"},
      {"sic":"8712",
        "sic_desc":"Architectural Services"},
      {"sic":"8713",
        "sic_desc":"Surveying Services"},
      {"sic":"8721",
        "sic_desc":"Acc., Auditing & Bookkeeping"},
      {"sic":"8731",
        "sic_desc":"Commercial Physical Research"},
      {"sic":"8732",
        "sic_desc":"Commercial Nonphysical Resear"},
      {"sic":"8733",
        "sic_desc":"Noncommercial Research Organi"},
      {"sic":"8734",
        "sic_desc":"Commercial Testing Laboratory"},
      {"sic":"8741",
        "sic_desc":"Management Services"},
      {"sic":"8742",
        "sic_desc":"Management Consulting Service"},
      {"sic":"8743",
        "sic_desc":"Public Relations Services"},
      {"sic":"8744",
        "sic_desc":"Facilities Support Services"},
      {"sic":"8748",
        "sic_desc":"Business Consulting, NEC"},
      {"sic":"8811",
        "sic_desc":"Private Households"},
      {"sic":"8999",
        "sic_desc":"Services, NEC"},
      {"sic":"9111",
        "sic_desc":"Executive Offices"},
      {"sic":"9121",
        "sic_desc":"Legislative Bodies"},
      {"sic":"9131",
        "sic_desc":"Exec & Legis Offices Combined"},
      {"sic":"9199",
        "sic_desc":"General Government, NEC"},
      {"sic":"9211",
        "sic_desc":"Courts"},
      {"sic":"9221",
        "sic_desc":"Police Protection"},
      {"sic":"9222",
        "sic_desc":"Legal Counsel & Prosecution"},
      {"sic":"9223",
        "sic_desc":"Correctional Institutions"},
      {"sic":"9224",
        "sic_desc":"Fire Protection"},
      {"sic":"9229",
        "sic_desc":"Public Order and Safety, NEC"},
      {"sic":"9311",
        "sic_desc":"Public Finance"},
      {"sic":"9411",
        "sic_desc":"Administration of Educat Prog"},
      {"sic":"9431",
        "sic_desc":"Admin of Pub Health Programs"},
      {"sic":"9441",
        "sic_desc":"Adm Of Social/Human Resource"},
      {"sic":"9451",
        "sic_desc":"Adm Of Vet Affairs, Ex Hea/Ins"},
      {"sic":"9511",
        "sic_desc":"Air & Water Res & Sol Wste Mgt"},
      {"sic":"9512",
        "sic_desc":"Land, Min, Wildlife/Forest Con"},
      {"sic":"9531",
        "sic_desc":"Admin of Housing Programs"},
      {"sic":"9532",
        "sic_desc":"Adm Of Urb Plan/Comm/Rurl Dev"},
      {"sic":"9611",
        "sic_desc":"Admin of General Economic Pro"},
      {"sic":"9621",
        "sic_desc":"Reg & Admin of Trans Programs"},
      {"sic":"9631",
        "sic_desc":"Reg & Adm Of Comms, Elec, Gas"},
      {"sic":"9641",
        "sic_desc":"Reg Of Agri Marketing & Commod"},
      {"sic":"9651",
        "sic_desc":"Reg, Lic & Insp Of Comm Sector"},
      {"sic":"9661",
        "sic_desc":"Space Research and Technology"},
      {"sic":"9711",
        "sic_desc":"National Security"},
      {"sic":"9721",
        "sic_desc":"International Security"},
      {"sic":"9999",
        "sic_desc":"Nonclassifiable Establishments"},
      {"sic":"2819PHOS",
        "sic_desc":"Industrial Inorganic Chemicals (Phosphate Manufacturing)"},
      {"sic":"2874FER",
        "sic_desc":"Phosphatic Fertilizers (Fertilizer Manufacturing)"},
      {"sic":"2611-1",
        "sic_desc":"Pulp Mills"},
      {"sic":"2611-2",
        "sic_desc":"Pulp Mills"},
      {"sic":"2611-3",
        "sic_desc":"Pulp Mills"},
      {"sic":"2621-1",
        "sic_desc":"Paper Mills"},
      {"sic":"2621-2",
        "sic_desc":"Paper Mills"},
      {"sic":"2621-3",
        "sic_desc":"Paper Mills"},
      {"sic":"2631-1",
        "sic_desc":"Paperboard Mills"},
      {"sic":"2631-2",
        "sic_desc":"Paperboard Mills"},
      {"sic":"2631-3",
        "sic_desc":"Paperboard Mills"},
      {"sic":"2048GRAIN",
        "sic_desc":"Prepared Feeds and Feed Ingredients For Animals (Grain Mills)"},
      {"sic":"2819NMM",
        "sic_desc":"Industrial Inorganic Chemicals (Nonferrous Metals Manufacturing)"},
      {"sic":"CWT",
        "sic_desc":"Centralized Waste Treaters"},
      {"sic":"MPM",
        "sic_desc":"Metal Products and Machinery"},
      {"sic":"2048PH",
        "sic_desc":"Prepared Feeds and Feed Ingredients For Animals and Fowls"},
      {"sic":"2823P",
        "sic_desc":"Cellulosic Man-Made Fibers (Pesticides)"},
      {"sic":"2844P",
        "sic_desc":"Perfumes, Cosmetics, Toilet Prep (Pesticides)"},
      {"sic":"2821P",
        "sic_desc":"Plastics Materials, Synthetic Resins, and Nonvulcanizable Elastomers"},
      {"sic":"2842P",
        "sic_desc":"Specialty Cleaning, Polishing (Pesticides)"},
      {"sic":"2824P",
        "sic_desc":"Manmade Organic Fibers, Except Cellulosic"},
      {"sic":"2865P",
        "sic_desc":"Cyclic Organic Crudes and Intermediates, and Organic Dyes"},
      {"sic":"2899P",
        "sic_desc":"Chemicals and Chemical Preparations, Not Elsewhere Classified"},
      {"sic":"2891P",
        "sic_desc":"Adhesives and Sealants (Pesticides)"},
      {"sic":"2869P",
        "sic_desc":"Industrial Organic Chemicals, Not Elsewhere Classified"},
      {"sic":"5169P",
        "sic_desc":"Chemicals and Allied Products (Pesticides)"},
      {"sic":"2834P",
        "sic_desc":"Pharmaceutical Preparations (Pesticides)"},
      {"sic":"VCCAP",
        "sic_desc":"Chlorine and Chlorinated Hydrocarbons (Pesticides)"},
      {"sic":"2048MPP",
        "sic_desc":"Prepared Feeds and Feed Ingredients For Animals and Fowls"},
      {"sic":"VCCA",
        "sic_desc":"Chlorine and Chlorinated Hydrocarbons"},
      {"sic":"2411-1",
        "sic_desc":"Logging Camps/Logging Contract (Pulp and Paper)"},
      {"sic":"2892OCPSF",
        "sic_desc":"Explosives (OCPSF)"},
      {"sic":"4953-1",
        "sic_desc":"Refuse Systems"},
      {"sic":"4953WC",
        "sic_desc":"Refuse Systems"},
      {"sic":"4953-2",
        "sic_desc":"Refuse Systems"},
      {"sic":"4953L",
        "sic_desc":"Refuse Systems"},
      {"sic":"SUPER",
        "sic_desc":"Superfund Site"},
      {"sic":"3624CB",
        "sic_desc":"Carbon and Graphite Products (Carbon Black)"},
      {"sic":"3341CC",
        "sic_desc":"Secondary Smelting and Refining Of Nonferrous Metals"},
      {"sic":"3471CC",
        "sic_desc":"Plating and Polishing (Coil Coating)"},
      {"sic":"3431PE",
        "sic_desc":"Metal Sanitary Ware (Porcelain Enameling)"},
      {"sic":"3469PE",
        "sic_desc":"Metal Stampings, NEC (Porcelain Enameling)"},
      {"sic":"3633PE",
        "sic_desc":"Household Laundry Equipment (Porcelain Enameling)"},
      {"sic":"3639PE",
        "sic_desc":"Household Appliances, NEC (Porcelain Enameling)"},
      {"sic":"2016",
        "sic_desc":"Poultry Dressing Plants"},
      {"sic":"2080",
        "sic_desc":"Beverages"},
      {"sic":"2440",
        "sic_desc":"Wood Containers"},
      {"sic":"3332",
        "sic_desc":"Primary Lead"},
      {"sic":"3360",
        "sic_desc":"Nonferrous Foundries (Castings)"},
      {"sic":"3362",
        "sic_desc":"Nonferrous Foundries (Brass, Bronze)"},
      {"sic":"3622",
        "sic_desc":"Industrial Controls"},
      {"sic":"3670",
        "sic_desc":"Electronic Components & Accessories"}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "SicCode" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "SicCode"
  }, null, {})
};
