module.exports = {
  up(queryInterface) {
    let records = [{"sic":"3732",
      "sic_desc":"BOAT BUILDING AND REPAIRING"},
      {"sic":"3743",
        "sic_desc":"RAILROAD EQUIPMENT"},
      {"sic":"3751",
        "sic_desc":"MOTORCYCLES, BICYCLES AND PART"},
      {"sic":"3761",
        "sic_desc":"GUIDED MISSILES & SPACE VEHICL"},
      {"sic":"3764",
        "sic_desc":"SPACE PROPULSION UNITS & PARTS"},
      {"sic":"3769",
        "sic_desc":"SPACE VEHICLE EQUIPMENT, NEC"},
      {"sic":"3792",
        "sic_desc":"TRAVEL TRAILERS AND CAMPERS"},
      {"sic":"3795",
        "sic_desc":"TANKS AND TANK COMPONENTS"},
      {"sic":"3799",
        "sic_desc":"TRANSPORTATION EQUIPMENT, NEC"},
      {"sic":"3812",
        "sic_desc":"SEARCH & NAVIGATION EQUIPMENT"},
      {"sic":"3821",
        "sic_desc":"LAB APPARATUS & FURNITURE"},
      {"sic":"3822",
        "sic_desc":"ENVIRONMENTAL CONTROLS"},
      {"sic":"3823",
        "sic_desc":"PROCESS CONTROL INSTRUMENTS"},
      {"sic":"3824",
        "sic_desc":"FLUID METERS & COUNTING DEVICE"},
      {"sic":"3825",
        "sic_desc":"INSTRUMENTS TO MEASURE ELECTRI"},
      {"sic":"3826",
        "sic_desc":"ANALYTICAL INSTRUMENTS"},
      {"sic":"3827",
        "sic_desc":"OPTICAL INSTRUMENTS AND LENSES"},
      {"sic":"3829",
        "sic_desc":"MEASURING & CONTROLLING DEVICE"},
      {"sic":"3841",
        "sic_desc":"SURGICAL & MEDICAL INSTRUMENTS"},
      {"sic":"3842",
        "sic_desc":"SURGICAL APPLIANCES & SUPPLIES"},
      {"sic":"3843",
        "sic_desc":"DENTAL EQUIPMENT AND SUPPLIES"},
      {"sic":"3844",
        "sic_desc":"X-RAY APPARATUS AND TUBES"},
      {"sic":"3845",
        "sic_desc":"ELECTROMEDICAL EQUIPMENT"},
      {"sic":"3851",
        "sic_desc":"OPHTHALMIC GOODS"},
      {"sic":"3861",
        "sic_desc":"PHOTOGRAPHIC EQUIP & SUPPLIES"},
      {"sic":"3873",
        "sic_desc":"WATCHES, CLOCKS & WATCHCASES"},
      {"sic":"3911",
        "sic_desc":"JEWELRY, PRECIOUS METAL"},
      {"sic":"3914",
        "sic_desc":"SILVERWARE AND PLATED WARE"},
      {"sic":"3915",
        "sic_desc":"JEWELERS' MATERIALS & LAPIDARY"},
      {"sic":"3931",
        "sic_desc":"MUSICAL INSTRUMENTS"},
      {"sic":"3942",
        "sic_desc":"DOLLS"},
      {"sic":"3944",
        "sic_desc":"GAMES, TOYS & CHILDREN'S VEHIC"},
      {"sic":"3949",
        "sic_desc":"SPORTING & ATHLETIC GOODS, NEC"},
      {"sic":"3951",
        "sic_desc":"PENS & MECHANICAL PENCILS"},
      {"sic":"3952",
        "sic_desc":"LEAD PENCILS AND ART GOODS"},
      {"sic":"3953",
        "sic_desc":"MARKING DEVICES"},
      {"sic":"3955",
        "sic_desc":"CARBON PAPER AND INKED RIBBONS"},
      {"sic":"3961",
        "sic_desc":"COSTUME JEWELRY"},
      {"sic":"3965",
        "sic_desc":"FASTENERS, BUTTONS, NEEDLES"},
      {"sic":"3991",
        "sic_desc":"BROOMS AND BRUSHES"},
      {"sic":"3993",
        "sic_desc":"SIGNS AND ADVERTISING DISPLAYS"},
      {"sic":"3995",
        "sic_desc":"BURIAL CASKETS"},
      {"sic":"3996",
        "sic_desc":"HARD SURFACE FLOOR COVERINGS"},
      {"sic":"3999",
        "sic_desc":"MANUFACTURING INDUSTRIES, NEC"},
      {"sic":"4011",
        "sic_desc":"RAILROADS, LINE HAUL OPERATING"},
      {"sic":"4013",
        "sic_desc":"RAILROAD SWTCHING & TERM ESTAB"},
      {"sic":"4111",
        "sic_desc":"LOCAL AND SUBURBAN TRANSIT"},
      {"sic":"4119",
        "sic_desc":"LOCAL PASSENGER TRANSPORTATION"},
      {"sic":"4121",
        "sic_desc":"TAXICABS"},
      {"sic":"4131",
        "sic_desc":"INTERCITY & RURAL BUS TRANSPOR"},
      {"sic":"4141",
        "sic_desc":"LOCAL BUS CHARTER SERVICE"},
      {"sic":"4142",
        "sic_desc":"BUS CHARTER SERVICE, EXC LOCAL"},
      {"sic":"4151",
        "sic_desc":"SCHOOL BUSES"},
      {"sic":"4173",
        "sic_desc":"BUS TERMINAL & SERVICE FACILIT"},
      {"sic":"4212",
        "sic_desc":"LOCAL TRUCKING WITHOUT STORAGE"},
      {"sic":"4213",
        "sic_desc":"TRUCKING, EXCEPT LOCAL"},
      {"sic":"4214",
        "sic_desc":"LOCAL TRUCKING WITH STORAGE"},
      {"sic":"4215",
        "sic_desc":"COURIER SERVICES, EXCEPT AIR"},
      {"sic":"4221",
        "sic_desc":"FARM PROD WAREHOUSING & STORAG"},
      {"sic":"4222",
        "sic_desc":"REFRIGERTAED WAREHOUSING & STO"},
      {"sic":"4225",
        "sic_desc":"GENERAL WAREHOUSING & STORAGE"},
      {"sic":"4226",
        "sic_desc":"SPECIAL WAREHOUSING & STORAGE"},
      {"sic":"4231",
        "sic_desc":"TRUCKING TERMINAL FACILITIES"},
      {"sic":"4311",
        "sic_desc":"UNITED STATES POSTAL SERVICE"},
      {"sic":"4412",
        "sic_desc":"DEEP SEA FOREIGN TRANSP OF FRE"},
      {"sic":"4424",
        "sic_desc":"DEEP SEA DOMES TRANSP OF FREIG"},
      {"sic":"4432",
        "sic_desc":"FREIGHT TRANSP ON THE GR LAKES"},
      {"sic":"4449",
        "sic_desc":"WATER TRANSP OF FREIGHT, NEC"},
      {"sic":"4481",
        "sic_desc":"DEEP SEA PAS TRANSP, EXC FERRY"},
      {"sic":"4482",
        "sic_desc":"FERRIES"},
      {"sic":"4489",
        "sic_desc":"WATER PASSENGER TRANSPORTATION"},
      {"sic":"4491",
        "sic_desc":"MARINE CARGO HANDLING"},
      {"sic":"4492",
        "sic_desc":"TOWING AND TUGBOAT SERVICE"},
      {"sic":"4493",
        "sic_desc":"MARINAS"},
      {"sic":"4499",
        "sic_desc":"WATER TRANSPORTATION SERIVCES"},
      {"sic":"4512",
        "sic_desc":"AIR TRANSPORTATION, SCHEDULED"},
      {"sic":"4513",
        "sic_desc":"AIR COURIER SERVICES"},
      {"sic":"4522",
        "sic_desc":"AIR TRANSP, NONSCHEDULED"},
      {"sic":"4581",
        "sic_desc":"AIRPORTS, FLYING FIELDS & SER"},
      {"sic":"4612",
        "sic_desc":"CRUDE PETROLEUM PIPELINES"},
      {"sic":"4613",
        "sic_desc":"REFINED PETROLEUM PIPELINE"},
      {"sic":"4619",
        "sic_desc":"PIPELINES, NEC"},
      {"sic":"4724",
        "sic_desc":"TRAVEL AGENCIES"},
      {"sic":"4725",
        "sic_desc":"TOUR OPERATORS"},
      {"sic":"4729",
        "sic_desc":"PASSENGER TRANSP ARRANGEMENT"},
      {"sic":"4731",
        "sic_desc":"FREIGHT TRANSP ARRANGEMENT"},
      {"sic":"4741",
        "sic_desc":"RENTAL OF RAILROAD CARS"},
      {"sic":"4783",
        "sic_desc":"PACKING AND CRATING"},
      {"sic":"4785",
        "sic_desc":"INSPECTION & FIXED FACILITIE"},
      {"sic":"4789",
        "sic_desc":"TRANSPORTATION SERVICES, NEC"},
      {"sic":"4812",
        "sic_desc":"RADIOTELEPHONE COMMUNICATIONS"},
      {"sic":"4813",
        "sic_desc":"TELEPHONE COM, EXCEPT RADIO"},
      {"sic":"4822",
        "sic_desc":"TELEGRAPH & OTHER COMMUNICATI"},
      {"sic":"4832",
        "sic_desc":"RADIO BROADCASTING, NEC"},
      {"sic":"4833",
        "sic_desc":"TELEVISION BROADCASTING"},
      {"sic":"4841",
        "sic_desc":"CABLE & OTHER PAY TV SERVICES"},
      {"sic":"4899",
        "sic_desc":"COMMUNICATION SERVICES, NEC"},
      {"sic":"4911",
        "sic_desc":"ELECTRICAL SERVICES"},
      {"sic":"4922",
        "sic_desc":"NATURAL GAS TRANSMISSION"},
      {"sic":"4923",
        "sic_desc":"NAT GAS TRANSMISSION & DISTRIB"},
      {"sic":"4924",
        "sic_desc":"NATURAL GAS DISTRIBUTION"},
      {"sic":"4925",
        "sic_desc":"MIXED,MANUFAC,OR LIQ GAS PROD"},
      {"sic":"4931",
        "sic_desc":"ELEC & OTHER SERVICES COMBINED"},
      {"sic":"4932",
        "sic_desc":"GAS & OTHER SERVICES COMBINED"},
      {"sic":"4939",
        "sic_desc":"COMBINATION UTILITIES, NEC"},
      {"sic":"4941",
        "sic_desc":"WATER SUPPLY"},
      {"sic":"4952",
        "sic_desc":"SEWERAGE SYSTEMS"},
      {"sic":"4953",
        "sic_desc":"REFUSE SYSTEMS"},
      {"sic":"4959",
        "sic_desc":"SANITARY SERVICES, NEC"},
      {"sic":"4961",
        "sic_desc":"STEAM & AIR-CONDITIONING SUP"},
      {"sic":"4971",
        "sic_desc":"IRRIGATION SYSTEMS"},
      {"sic":"5012",
        "sic_desc":"AUTOMOBILES AND OTHER VEHICLES"},
      {"sic":"5013",
        "sic_desc":"MOTOR VEHICLE PARTS & NEW SUP"},
      {"sic":"5014",
        "sic_desc":"TIRES AND TUBES"},
      {"sic":"5015",
        "sic_desc":"MOTOR VEHICLE PARTS, USED"},
      {"sic":"5021",
        "sic_desc":"FURNITURE"},
      {"sic":"5023",
        "sic_desc":"HOMEFURNISHINGS"},
      {"sic":"5031",
        "sic_desc":"LUMBER,PLYWOOD,MILLWORK,& PANL"},
      {"sic":"5032",
        "sic_desc":"BRICK, STONE & RELAT MATERIALS"},
      {"sic":"5033",
        "sic_desc":"ROOFING, SIDING AND INSULATION"},
      {"sic":"5039",
        "sic_desc":"CONSTRUCTION MATERIALS, NEC"},
      {"sic":"5043",
        "sic_desc":"PHOTOGRAPHIC EQUIP & SUPPLIES"},
      {"sic":"5044",
        "sic_desc":"OFFICE EQUIPMENT"},
      {"sic":"5045",
        "sic_desc":"COMPUTERS, PERIPHERALS, & SOFT"},
      {"sic":"5046",
        "sic_desc":"COMMERCIAL EQUIPMENT, NEC"},
      {"sic":"5047",
        "sic_desc":"MEDICAL AND OFFICE EQUIPMENT"},
      {"sic":"5048",
        "sic_desc":"OPHTHALMIC GOODS"},
      {"sic":"5049",
        "sic_desc":"PROFESSIONAL EQUIPMENT, NEC"},
      {"sic":"5051",
        "sic_desc":"METAL SERVICE CENTERS & OFFICE"},
      {"sic":"5052",
        "sic_desc":"COAL & OTHER MINERALS & ORES"},
      {"sic":"5063",
        "sic_desc":"ELECTRICAL APPARATUS AND EQUIP"},
      {"sic":"5064",
        "sic_desc":"ELEC APPLIANCES/TV & RADIO SET"},
      {"sic":"5065",
        "sic_desc":"ELECTRONIC PARTS AND EQUIPMENT"},
      {"sic":"5072",
        "sic_desc":"HARDWARE"},
      {"sic":"5074",
        "sic_desc":"PLUMB & HEAT EQUIP & SUPPLIES"},
      {"sic":"5075",
        "sic_desc":"AIR HEAT & AIR-COND. EQUIP/SUP"},
      {"sic":"5078",
        "sic_desc":"REFRIGERATION EQUIP & SUPPLIES"},
      {"sic":"5082",
        "sic_desc":"CONST & MINING MACHINE & EQUIP"},
      {"sic":"5083",
        "sic_desc":"FARM & GARDEN MACHINE & EQUIP"},
      {"sic":"5084",
        "sic_desc":"INDUSTRIAL MACHINERY AND EQUIP"},
      {"sic":"5085",
        "sic_desc":"INDUSTRIAL SUPPLIES"},
      {"sic":"5087",
        "sic_desc":"SERVICE ESTABLISH EQUIP & SUPP"},
      {"sic":"5088",
        "sic_desc":"TRANS EQUIP & SUPP, EXC MOTOR"},
      {"sic":"5091",
        "sic_desc":"SPORTING & RECREATIONAL GOODS"},
      {"sic":"5092",
        "sic_desc":"TOYS & HOBBY GOODS & SUPPLIES"},
      {"sic":"5093",
        "sic_desc":"SCRAP & WASTE MATERIALS"},
      {"sic":"5094",
        "sic_desc":"JEWELRY, WATCHES, PRECIOUS STO"},
      {"sic":"5099",
        "sic_desc":"DURABLE GOODS, NEC"},
      {"sic":"5111",
        "sic_desc":"PRINTING AND WRITING PAPER"},
      {"sic":"5112",
        "sic_desc":"STATIONERY AND OFFICE SUPPLIES"},
      {"sic":"5113",
        "sic_desc":"INDUST & PERSONAL PAPER SERVIC"},
      {"sic":"5122",
        "sic_desc":"DRUGS, DRUG PRPPRIE & SUNDRIES"},
      {"sic":"5131",
        "sic_desc":"PIECE GOODS AND NOTIONS"},
      {"sic":"5136",
        "sic_desc":"MALE'S CLOTHING & FURNISHINGS"},
      {"sic":"5137",
        "sic_desc":"WOMEN'S, CHILD & INF CLOTHING"},
      {"sic":"5139",
        "sic_desc":"FOOTWEAR"},
      {"sic":"5141",
        "sic_desc":"GROCERIES, GENERAL LINE"},
      {"sic":"5142",
        "sic_desc":"PACKAGED FROZEN FOODS"},
      {"sic":"5143",
        "sic_desc":"DAIRY PROD, EXC DRIED & CANNED"},
      {"sic":"5144",
        "sic_desc":"POULTRY AND POULTRY PRODUCTS"},
      {"sic":"5145",
        "sic_desc":"CONFECTIONERY"},
      {"sic":"5146",
        "sic_desc":"FISH AND SEAFOODS"},
      {"sic":"5147",
        "sic_desc":"MEATS AND MEAT PRODUCTS"},
      {"sic":"5148",
        "sic_desc":"FRESH FRUITS AND VEGETABLES"},
      {"sic":"5149",
        "sic_desc":"GROCERIES & RELATED PRODUCTS"},
      {"sic":"5153",
        "sic_desc":"GRAIN AND FIELD BEANS"},
      {"sic":"5154",
        "sic_desc":"LIVESTOCK"},
      {"sic":"5159",
        "sic_desc":"FARM-PRODUCT RAW MATERIALS"},
      {"sic":"5162",
        "sic_desc":"PLASTIC MATER & BASIC SHAPES"},
      {"sic":"5169",
        "sic_desc":"CHEMICALS AND ALLIED PRODUCTS"},
      {"sic":"5171",
        "sic_desc":"PETROLEUM BULK STATIONS & TERM"},
      {"sic":"3465",
        "sic_desc":"AUTOMOTIVE STAMPINGS"},
      {"sic":"3466",
        "sic_desc":"CROWNS AND CLOSURES"},
      {"sic":"3469",
        "sic_desc":"METAL STAMPINGS, NEC"},
      {"sic":"3471",
        "sic_desc":"PLATING AND POLISHING"},
      {"sic":"3479",
        "sic_desc":"METAL COATING & ALLIED SERVIC"},
      {"sic":"3482",
        "sic_desc":"SMALL ARMS AMMUNITION"},
      {"sic":"3483",
        "sic_desc":"AMMUNIT., EXC. FOR SMALL ARMS"},
      {"sic":"3484",
        "sic_desc":"SMALL ARMS"},
      {"sic":"3489",
        "sic_desc":"ORDNANCE AND ACCESSORIES, NEC"},
      {"sic":"3491",
        "sic_desc":"INDUSTRIAL VALVES"},
      {"sic":"3492",
        "sic_desc":"FLUID POWER VALVES & HOSE FITT"},
      {"sic":"3493",
        "sic_desc":"STEEL SPRINGS, EXCEPT WIRE"},
      {"sic":"3494",
        "sic_desc":"VALVES AND PIPE FITTINGS, NEC"},
      {"sic":"3495",
        "sic_desc":"WIRE SPRINGS"},
      {"sic":"3496",
        "sic_desc":"MISC. FABRICATED WIRE PRODUCTS"},
      {"sic":"3497",
        "sic_desc":"METAL FOIL AND LEAF"},
      {"sic":"3498",
        "sic_desc":"FABRICATED PIPE AND FITTINGS"},
      {"sic":"3499",
        "sic_desc":"FABRICATED METAL PRODUCTS NEC"},
      {"sic":"3511",
        "sic_desc":"TURBINES & TURBINE GENERATOR"},
      {"sic":"3519",
        "sic_desc":"INTERNAL COMBUSTION ENGINES,"},
      {"sic":"3523",
        "sic_desc":"FARM MACHINERY AND EQUIPMENT"},
      {"sic":"3524",
        "sic_desc":"LAWN AND GARDEN EQUIPMENT"},
      {"sic":"3531",
        "sic_desc":"CONSTRUCTION MACHINERY"},
      {"sic":"3532",
        "sic_desc":"MINING MACHINERY"},
      {"sic":"3533",
        "sic_desc":"OIL FIELD MACHINERY"},
      {"sic":"3534",
        "sic_desc":"ELEVATORS AND MOVING STAIRWAYS"},
      {"sic":"3535",
        "sic_desc":"CONVEYORS & CONVEYING EQUIPMEN"},
      {"sic":"3536",
        "sic_desc":"CRANES/HOISTS/MONORAIL SYSTEMS"},
      {"sic":"3537",
        "sic_desc":"INDUSTRIAL TRUCKS AND TRACTORS"},
      {"sic":"3541",
        "sic_desc":"MACHINE TOOLS, METAL CUTTING"},
      {"sic":"3542",
        "sic_desc":"MACHINE TOOLS, METAL FORMING"},
      {"sic":"3543",
        "sic_desc":"INDUSTRIAL PATTERNS"},
      {"sic":"3544",
        "sic_desc":"SPECIAL DIES/TOOLS/JIGS & FIXT"},
      {"sic":"3545",
        "sic_desc":"MACHINE TOOL ACCESSORIES"},
      {"sic":"3546",
        "sic_desc":"POWER DRIVEN HAND TOOLS"},
      {"sic":"3547",
        "sic_desc":"ROLLING MILL MACHINERY"},
      {"sic":"3548",
        "sic_desc":"WELDING APPARATUS"},
      {"sic":"3549",
        "sic_desc":"METALWORKING MACHINERY, NEC"},
      {"sic":"3552",
        "sic_desc":"TEXTILE MACHINERY"},
      {"sic":"3553",
        "sic_desc":"WOODWORKING MACHINERY"},
      {"sic":"3554",
        "sic_desc":"PAPER INDUSTRIES MACHINERY"},
      {"sic":"3555",
        "sic_desc":"PRINTING TRADES MACHINERY"},
      {"sic":"3556",
        "sic_desc":"FOOD PRODUCTS MACHINERY"},
      {"sic":"3559",
        "sic_desc":"SPECIAL INDUSTRY MACHINERY,NEC"},
      {"sic":"3561",
        "sic_desc":"PUMPS AND PUMPING EQUIPMENT"},
      {"sic":"3562",
        "sic_desc":"BALL AND ROLLER BEARINGS"},
      {"sic":"3563",
        "sic_desc":"AIR AND GAS COMPRESSORS"},
      {"sic":"3564",
        "sic_desc":"BLOWER AND FANS"},
      {"sic":"3565",
        "sic_desc":"PACKAGING MACHINERY"},
      {"sic":"3566",
        "sic_desc":"SPEED CHANGERS, DRIVES & GEARS"},
      {"sic":"3567",
        "sic_desc":"INDUSTRIAL FURNACES AND OVENS"},
      {"sic":"3568",
        "sic_desc":"POWER TRANSMISSION EQUIPMENT"},
      {"sic":"3569",
        "sic_desc":"GENERAL INDUSTRIAL MACHINERY"},
      {"sic":"3571",
        "sic_desc":"ELECTRONIC COMPUTERS"},
      {"sic":"3572",
        "sic_desc":"COMPUTER STORAGE DEVICES"},
      {"sic":"3575",
        "sic_desc":"COMPUTER TERMINALS"},
      {"sic":"3577",
        "sic_desc":"COMPUTER PERIPHERAL EQUIP,NEC"},
      {"sic":"3578",
        "sic_desc":"CALC & ACCOUNTING EQUIPMENT"},
      {"sic":"3579",
        "sic_desc":"OFFICE MACHINES"},
      {"sic":"2281",
        "sic_desc":"YARN SPIN MILLS:COTTON, MM FIB"},
      {"sic":"2282",
        "sic_desc":"YARN TEXT, THROW, TWIST & WIND"},
      {"sic":"2284",
        "sic_desc":"THREAD MILLS"},
      {"sic":"2295",
        "sic_desc":"COATED FABRICS, NOT RUBBERIZED"},
      {"sic":"2296",
        "sic_desc":"TIRE CORD AND FABRIC"},
      {"sic":"2297",
        "sic_desc":"NONWOVEN FABRICS"},
      {"sic":"2298",
        "sic_desc":"CORDAGE AND TWINE"},
      {"sic":"2299",
        "sic_desc":"TEXTILE GOODS, NEC"},
      {"sic":"2311",
        "sic_desc":"MEN'S & BOY'S SUITS, COATS"},
      {"sic":"2321",
        "sic_desc":"MEN'S, & BOY'S SHIRTS"},
      {"sic":"2322",
        "sic_desc":"MEN'S & BOYS UNDERWEAR & NIGHT"},
      {"sic":"2323",
        "sic_desc":"MEN'S, YOUTH'S & BOYS NECKWEAR"},
      {"sic":"2325",
        "sic_desc":"MEN & BOY SEP TROUSERS & SLACK"},
      {"sic":"2326",
        "sic_desc":"MEN'S & BOY'S WORK CLOTHING"},
      {"sic":"2329",
        "sic_desc":"MEN'S, YOUTH'S & BOY'S CLOTHNG"},
      {"sic":"2331",
        "sic_desc":"WOMEN, MIS, JR' BLSES, WAISTS"},
      {"sic":"2335",
        "sic_desc":"WOMEN'S, MISSES' & JRS' DRESS"},
      {"sic":"2337",
        "sic_desc":"WOMEN, MIS', JRS' SUITS, SHIRT"},
      {"sic":"2339",
        "sic_desc":"WOMEN'S, MISS' & JR' OUTERWEAR"},
      {"sic":"2341",
        "sic_desc":"WOMENS,MIS',CHLD'S,INF UNDERWE"},
      {"sic":"2342",
        "sic_desc":"BRASSIERS,GIRDLES & ALLIED GAR"},
      {"sic":"2353",
        "sic_desc":"HATS, CAPS AND MILLINERY"},
      {"sic":"2361",
        "sic_desc":"GIRLS, CHILDS & INFS OUTERWEAR"},
      {"sic":"2369",
        "sic_desc":"GIRLS, CHILDS & INFS OUTERWEAR"},
      {"sic":"2371",
        "sic_desc":"FUR GOODS"},
      {"sic":"2381",
        "sic_desc":"DRESS & WK GLOVE EXC KNIT/LEAT"},
      {"sic":"2384",
        "sic_desc":"ROBES & DRESSING GOWNS"},
      {"sic":"2385",
        "sic_desc":"RAINCOATS & RAINGEAR"},
      {"sic":"2386",
        "sic_desc":"LEATHER & SHEEP-LINED CLOTHING"},
      {"sic":"2387",
        "sic_desc":"APPAREL BELTS"},
      {"sic":"2389",
        "sic_desc":"APPAREL & ACCESSORIES, NEC"},
      {"sic":"2391",
        "sic_desc":"CURTAINS & DRAPERIES"},
      {"sic":"2392",
        "sic_desc":"HOUSEFURNISHINGS, EXC CURTAINS"},
      {"sic":"2393",
        "sic_desc":"TEXTILE BAGS"},
      {"sic":"2394",
        "sic_desc":"CANVAS & RELATED PRODUCTS"},
      {"sic":"2395",
        "sic_desc":"PLEATING, DECOR/NOVELTY STITCH"},
      {"sic":"2396",
        "sic_desc":"AUTOMOTIVE TRIMMINGS, APPAREL"},
      {"sic":"2397",
        "sic_desc":"SCHIFFLI MACHINE EMBROIDERIES"},
      {"sic":"2399",
        "sic_desc":"FABRCATED TEXTILE PRODUCTS NEC"},
      {"sic":"2411",
        "sic_desc":"LOGGING CAMPS/LOGGING CONTRACT"},
      {"sic":"2421",
        "sic_desc":"SAWMILLS & PLANING MILLS, GEN"},
      {"sic":"2426",
        "sic_desc":"HARDWOOD DIMEN & FLOORING MILL"},
      {"sic":"2429",
        "sic_desc":"SPECIAL PRODUCT SAWMILLS NEC"},
      {"sic":"2431",
        "sic_desc":"MILLWORK"},
      {"sic":"2434",
        "sic_desc":"WOOD KITCHEN CABINETS"},
      {"sic":"2435",
        "sic_desc":"HARDWOOD VENEER AND PLYWOOD"},
      {"sic":"2436",
        "sic_desc":"SOFTWOOD VENEER AND PLYWOOD"},
      {"sic":"2439",
        "sic_desc":"STRUCTURAL WOOD MEMBERS, NEC"},
      {"sic":"2441",
        "sic_desc":"NAILED/LOCK CORNER WOOD BOXES"},
      {"sic":"2448",
        "sic_desc":"WOOD PALLETS AND SKIDS"},
      {"sic":"2449",
        "sic_desc":"WOOD CONTAINERS NEC"},
      {"sic":"2451",
        "sic_desc":"MOBILE HOMES"},
      {"sic":"2452",
        "sic_desc":"PREFAB WOOD BLDGS & COMPONENTS"},
      {"sic":"2491",
        "sic_desc":"WOOD PRESERVING"},
      {"sic":"2493",
        "sic_desc":"RECONSTITUTED WOOD PRODUCTS"},
      {"sic":"2499",
        "sic_desc":"WOOD PRODUCTS, NEC"},
      {"sic":"2511",
        "sic_desc":"WOOD HOUSEHOLD FURN, EXC UPHOL"},
      {"sic":"2512",
        "sic_desc":"WOOD HOUSEHOLD FURN, UPHOLSTER"},
      {"sic":"2514",
        "sic_desc":"METAL HOUSEHOLD FURNITURE"},
      {"sic":"2515",
        "sic_desc":"MATTRESSES AND BEDSPRINGS"},
      {"sic":"2517",
        "sic_desc":"WOOD TV, RADIO, PHONO CABINET"},
      {"sic":"2519",
        "sic_desc":"HOUSEHOLD FURNITURE, NEC"},
      {"sic":"2521",
        "sic_desc":"WOOD OFFICE FURNITURE"},
      {"sic":"2522",
        "sic_desc":"METAL OFFICE FURNITURE"},
      {"sic":"2531",
        "sic_desc":"PUBLIC BUILDING/RELATED FURNIT"},
      {"sic":"2541",
        "sic_desc":"WOOD PARTI,SHELF,LOCK,ETC"},
      {"sic":"2542",
        "sic_desc":"METAL PARTI,SHELF,LOCKERS"},
      {"sic":"2591",
        "sic_desc":"DRAPE HARDWARE/WINDOW BLINDS"},
      {"sic":"2599",
        "sic_desc":"FURNITURE AND FIXTURES, NEC"},
      {"sic":"2611",
        "sic_desc":"PULP MILLS"},
      {"sic":"2621",
        "sic_desc":"PAPER MILLS"},
      {"sic":"2631",
        "sic_desc":"PAPERBOARD MILLS"},
      {"sic":"2652",
        "sic_desc":"SET-UP PAPERBOARD BOXES"},
      {"sic":"2653",
        "sic_desc":"CORRUGATED/SOLID FIBER BOXES"},
      {"sic":"2655",
        "sic_desc":"FIBER CANS, TUBES,DRUMS & PROD"},
      {"sic":"2656",
        "sic_desc":"SANITARY FOOD CONTAINERS"},
      {"sic":"2657",
        "sic_desc":"FOLDING PAPERBOARD BOXES"},
      {"sic":"2671",
        "sic_desc":"COATED & LAMINATED PACKAGING"},
      {"sic":"2672",
        "sic_desc":"COATED & LAMINATED, NEC"},
      {"sic":"2673",
        "sic_desc":"BAGS, PLASTIC, LAMINA & COATED"},
      {"sic":"2674",
        "sic_desc":"BAGS,UNCOATD PAPER & MULTIWALL"},
      {"sic":"2675",
        "sic_desc":"DIE-CUT PAPER,PAPERBRD/CARDBRD"},
      {"sic":"2676",
        "sic_desc":"SANITARY PAPER PRODUCTS"},
      {"sic":"2677",
        "sic_desc":"ENVELOPES"},
      {"sic":"2678",
        "sic_desc":"STATIONERY,TABLETS & REL PROD"},
      {"sic":"2679",
        "sic_desc":"CONV PAPER & PAPERBRD PRODUCTS"},
      {"sic":"2711",
        "sic_desc":"NEWSPAPERS: PUBLISHING & PRINT"},
      {"sic":"2721",
        "sic_desc":"PERIODICALS: PUBLISHING & PRIN"},
      {"sic":"2731",
        "sic_desc":"BOOKS: PUBLISHING & PRINTING"},
      {"sic":"2732",
        "sic_desc":"BOOK PRINTING"},
      {"sic":"2741",
        "sic_desc":"MISCELLANEOUS PUBLISHING"},
      {"sic":"2752",
        "sic_desc":"COMMERCIAL PRINT, LITHOGRAPHIC"},
      {"sic":"2754",
        "sic_desc":"COMMERCIAL PRINTING, GRAVURE"},
      {"sic":"2759",
        "sic_desc":"COMMERCIAL PRINTING, NEC"},
      {"sic":"2761",
        "sic_desc":"MANIFOLD BUSINESS FORMS"},
      {"sic":"2771",
        "sic_desc":"GREETING CARD PUBLISHING"},
      {"sic":"2782",
        "sic_desc":"BLANKBOOKS,LOOSELEAF BINDERS"},
      {"sic":"2789",
        "sic_desc":"BOOKBINDING & RELATED WORK"},
      {"sic":"2791",
        "sic_desc":"TYPESETTING"},
      {"sic":"2796",
        "sic_desc":"PLATEMAKING SERVICES"},
      {"sic":"2812",
        "sic_desc":"ALKALIES AND CHLORINE"},
      {"sic":"2813",
        "sic_desc":"INDUSTRIAL GASES"},
      {"sic":"2816",
        "sic_desc":"INORGANIC PIGMENTS"},
      {"sic":"2819",
        "sic_desc":"INDUSTRIAL INORGANIC CHEMICALS"},
      {"sic":"2821",
        "sic_desc":"PLSTC MAT./SYN RESINS/NV ELAST"},
      {"sic":"2822",
        "sic_desc":"SYN RUBBER (VULCAN ELASTOMERS)"},
      {"sic":"2823",
        "sic_desc":"CELLULOSIC MAN-MADE FIBERS"},
      {"sic":"2824",
        "sic_desc":"SYN ORG FIBERS,EXCEPT CELLULOS"},
      {"sic":"2833",
        "sic_desc":"MEDICINAL CHEM/BOTANICAL PRODU"},
      {"sic":"2834",
        "sic_desc":"PHARMACEUTICAL PREPARATIONS"},
      {"sic":"2835",
        "sic_desc":"DIAGNOSTIC SUBSTANCES"},
      {"sic":"2836",
        "sic_desc":"BIOLOGCAL PROD, EXCEPT DIAGNOS"},
      {"sic":"2841",
        "sic_desc":"SOAP/DETERG EXC SPECIAL CLEANR"},
      {"sic":"2842",
        "sic_desc":"SPECIALTY CLEANING, POLISHING"},
      {"sic":"2843",
        "sic_desc":"SURF ACTIVE AGENT, FIN AGENTS"},
      {"sic":"2844",
        "sic_desc":"PERFUMES,COSMETICS,TOILET PREP"},
      {"sic":"2851",
        "sic_desc":"PAINTS/VARNISH/LACQUERS/ENAMEL"},
      {"sic":"2861",
        "sic_desc":"GUM AND WOOD CHEMICALS"},
      {"sic":"2865",
        "sic_desc":"CYCLIC CRUDES INTERM., DYES"},
      {"sic":"2869",
        "sic_desc":"INDUST. ORGANIC CHEMICALS NEC"},
      {"sic":"2873",
        "sic_desc":"NITROGEN FERTILIZERS"},
      {"sic":"2874",
        "sic_desc":"PHOSPHATIC FERTILIZERS"},
      {"sic":"2875",
        "sic_desc":"FERTILIZERS, MIXING ONLY"},
      {"sic":"2879",
        "sic_desc":"PESTICIDES & AGRICULTURAL CHEM"},
      {"sic":"2891",
        "sic_desc":"ADHESIVES AND SEALANTS"},
      {"sic":"2892",
        "sic_desc":"EXPLOSIVES"},
      {"sic":"2893",
        "sic_desc":"PRINTING INK"},
      {"sic":"2895",
        "sic_desc":"CARBON BLACK"},
      {"sic":"2899",
        "sic_desc":"CHEMICALS & CHEM PREP, NEC"},
      {"sic":"2911",
        "sic_desc":"PETROLEUM REFINING"},
      {"sic":"2951",
        "sic_desc":"PAVING MIXTURES AND BLOCKS"},
      {"sic":"2952",
        "sic_desc":"ASPHALT FELT AND COATINGS"},
      {"sic":"2992",
        "sic_desc":"LUBRICATING OILS AND GREASES"},
      {"sic":"2999",
        "sic_desc":"PROD OF PETROLEUM & COAL, NEC"},
      {"sic":"3011",
        "sic_desc":"TIRES AND INNER TUBES"},
      {"sic":"3021",
        "sic_desc":"RUBBER AND PLASTICS FOOTWEAR"},
      {"sic":"3052",
        "sic_desc":"RUBBER & PLASTICS HOSE & BELT"},
      {"sic":"3053",
        "sic_desc":"GASKETS, PACKING & SEALING DEV"},
      {"sic":"3061",
        "sic_desc":"MECHANICAL RUBBER GOODS"},
      {"sic":"3069",
        "sic_desc":"FABRICATED RUBBER PRODUCTS,NEC"},
      {"sic":"3081",
        "sic_desc":"UNSUPPORTED PLSTICS FILM/SHEET"},
      {"sic":"3082",
        "sic_desc":"UNSUPPORTED PLASTICS PROF SHAP"},
      {"sic":"3083",
        "sic_desc":"LAMINATED PLASTICS PLATE/SHEET"},
      {"sic":"3084",
        "sic_desc":"PLASTIC PIPE"},
      {"sic":"3085",
        "sic_desc":"PLASTIC BOTTLES"},
      {"sic":"3086",
        "sic_desc":"PLASTICS FOAM PRODUCTS"},
      {"sic":"3087",
        "sic_desc":"CUSTOM COMPOUNDED PURCH. RESIN"},
      {"sic":"3088",
        "sic_desc":"PLASTICS PLUMBING FIXTURES"},
      {"sic":"3089",
        "sic_desc":"PLASTICS PRODUCTS, NEC"},
      {"sic":"3111",
        "sic_desc":"LEATHER TANNING AND FINISHING"},
      {"sic":"3131",
        "sic_desc":"BOOT & SHOE CUT STOCK & FINDNG"},
      {"sic":"3142",
        "sic_desc":"HOUSE SLIPPERS"},
      {"sic":"3143",
        "sic_desc":"MEN'S FOOTWEAR,EXCEPT ATHLETIC"},
      {"sic":"3144",
        "sic_desc":"WOMEN'S FOOTWEAR,EXCEPT ATHLET"},
      {"sic":"3149",
        "sic_desc":"FOOTWEAR, EXCEPT RUBBER NEC"},
      {"sic":"3151",
        "sic_desc":"LEATHER GLOVES AND MITTENS"},
      {"sic":"3161",
        "sic_desc":"LUGGAGE"},
      {"sic":"3171",
        "sic_desc":"WOMEN'S HANDBAGS AND PURSES"},
      {"sic":"3172",
        "sic_desc":"PERSONAL LEATHER GOODS,EXC HAN"},
      {"sic":"3199",
        "sic_desc":"LEATHER GOODS NEC"},
      {"sic":"3211",
        "sic_desc":"FLAT GLASS"},
      {"sic":"3221",
        "sic_desc":"GLASS CONTAINERS"},
      {"sic":"3229",
        "sic_desc":"PRESSED & BLOWN GLASS & GWARE"},
      {"sic":"3231",
        "sic_desc":"GLASS PROD MADE OF PURCH. GLAS"},
      {"sic":"3241",
        "sic_desc":"CEMENT, HYDRAULIC"},
      {"sic":"3251",
        "sic_desc":"BRICK AND STRUCTURAL CLAY TILE"},
      {"sic":"3253",
        "sic_desc":"CERAMIC WALL AND FLOOR TILE"},
      {"sic":"3255",
        "sic_desc":"CLAY REFRACTORIES"},
      {"sic":"3259",
        "sic_desc":"STRUCTURAL CLAY PRODUCTS NEC"},
      {"sic":"3261",
        "sic_desc":"VITREOUS CHINA PLUMBING FIXTUR"},
      {"sic":"3262",
        "sic_desc":"VIT CHINA TABLE & KTCHN ARTICL"},
      {"sic":"3263",
        "sic_desc":"FINE EARTHENWARE"},
      {"sic":"3463",
        "sic_desc":"NONFERROUS FORGINGS"},
      {"sic":"5172",
        "sic_desc":"PETROL & PET PROD WHOLESALERS"},
      {"sic":"5181",
        "sic_desc":"BEER AND ALE"},
      {"sic":"5182",
        "sic_desc":"WINE & DIST ALCOHOLIC BEVERAGE"},
      {"sic":"5191",
        "sic_desc":"FARM SUPPLIES"},
      {"sic":"5192",
        "sic_desc":"BOOKS, PERIODICALS & NEWSPAPER"},
      {"sic":"5193",
        "sic_desc":"FLOWERS AND FLORISTS' SUPPLIES"},
      {"sic":"5194",
        "sic_desc":"TOBACCO AND TOBACCO PRODUCTS"},
      {"sic":"5198",
        "sic_desc":"PAINTS, VARNISHES AND SUPPLIES"},
      {"sic":"5199",
        "sic_desc":"NONDURABLE GOODS, NEC"},
      {"sic":"5211",
        "sic_desc":"LUMBER & BUILD MATERIAL DEALER"},
      {"sic":"5231",
        "sic_desc":"PAINT, GLASS & WALLPAPER STORE"},
      {"sic":"5251",
        "sic_desc":"HARDWARE STORES"},
      {"sic":"5261",
        "sic_desc":"RET NURSERIES,LAWN/GARDN STORE"},
      {"sic":"5271",
        "sic_desc":"MOBILE HOME DEALERS"},
      {"sic":"5311",
        "sic_desc":"DEPARTMENT STORES"},
      {"sic":"5331",
        "sic_desc":"VARIETY STORES"},
      {"sic":"5399",
        "sic_desc":"MISCELLANEOUS GENERAL STORES"},
      {"sic":"5411",
        "sic_desc":"GROCERY STORES"},
      {"sic":"5421",
        "sic_desc":"MEAT AND FISH MARKETS"},
      {"sic":"5431",
        "sic_desc":"FRUIT AND VEGETABLE MARKETS"},
      {"sic":"5441",
        "sic_desc":"CANDY, NUT & CONFECTION STORES"},
      {"sic":"5451",
        "sic_desc":"DAIRY PRODUCTS STORES"},
      {"sic":"5461",
        "sic_desc":"RETAIL BAKERIES"},
      {"sic":"5499",
        "sic_desc":"MISCELLANEOUS FOOD STORES"},
      {"sic":"5511",
        "sic_desc":"MOTOR VEH. DEALERS (NEW/USED)"},
      {"sic":"5521",
        "sic_desc":"MOTOR VEH. DEALERS (USED ONLY)"},
      {"sic":"5531",
        "sic_desc":"AUTO AND HOME SUPPLY STORES"},
      {"sic":"5541",
        "sic_desc":"GASOLINE SERVICE STATIONS"},
      {"sic":"5551",
        "sic_desc":"BOAT DEALERS"},
      {"sic":"5561",
        "sic_desc":"RECREATIONAL VEHICLE DEALERS"},
      {"sic":"5571",
        "sic_desc":"MOTORCYCLE DEALERS"},
      {"sic":"5599",
        "sic_desc":"AUTOMOTIVE DEALERS, NEC"},
      {"sic":"5611",
        "sic_desc":"MALE'S CLOTHING & ACCESS STORE"},
      {"sic":"5621",
        "sic_desc":"WOMEN'S CLOTHING STORES"},
      {"sic":"5632",
        "sic_desc":"WOMEN'S ACCESS & SPEC STORES"},
      {"sic":"5641",
        "sic_desc":"CHILDREN'S & INF WEAR STORES"},
      {"sic":"5651",
        "sic_desc":"FAMILY CLOTHING STORES"},
      {"sic":"5661",
        "sic_desc":"SHOE STORES"},
      {"sic":"5699",
        "sic_desc":"MISC APPAREL & ACCESS STORES"},
      {"sic":"5712",
        "sic_desc":"FURNITURE STORES"},
      {"sic":"5713",
        "sic_desc":"FLOOR COVERING STORES"},
      {"sic":"5714",
        "sic_desc":"DRAPE, CURTAIN & UPHOL STORES"},
      {"sic":"5719",
        "sic_desc":"MISC HOMEFURNISHINGS STORES"},
      {"sic":"5722",
        "sic_desc":"HOUSEHOLD APPLIANCE STORES"},
      {"sic":"5731",
        "sic_desc":"RADIO, TV & ELECTRONICS STORES"},
      {"sic":"5734",
        "sic_desc":"COMPUTER AND SOFTWARE STORES"},
      {"sic":"5735",
        "sic_desc":"RECORD & PRERECORDED TAPE STOR"},
      {"sic":"5736",
        "sic_desc":"MUSICAL INSTRUMENT STORES"},
      {"sic":"5812",
        "sic_desc":"EATING PLACES"},
      {"sic":"5813",
        "sic_desc":"DRINKING PLACES (ALCOHOLIC BEV"},
      {"sic":"5912",
        "sic_desc":"DRUG STORES & PROPRIETARY STOR"},
      {"sic":"5921",
        "sic_desc":"LIQUOR STORES"},
      {"sic":"5932",
        "sic_desc":"USED MERCHANDISE STORES"},
      {"sic":"5941",
        "sic_desc":"SPORTING GOODS/BICYCLE STORES"},
      {"sic":"5942",
        "sic_desc":"BOOK STORES"},
      {"sic":"5943",
        "sic_desc":"STATIONERY STORES"},
      {"sic":"0101",
        "sic_desc":"COCOA"},
      {"sic":"0111",
        "sic_desc":"WHEAT"},
      {"sic":"0112",
        "sic_desc":"RICE"},
      {"sic":"0115",
        "sic_desc":"CORN"},
      {"sic":"0116",
        "sic_desc":"SOYBEANS"},
      {"sic":"0119",
        "sic_desc":"CASH GRAINS, NEC"},
      {"sic":"0131",
        "sic_desc":"COTTON"},
      {"sic":"0132",
        "sic_desc":"TOBACCO"},
      {"sic":"0133",
        "sic_desc":"SUGARCANE AND SUGAR BEETS"},
      {"sic":"0134",
        "sic_desc":"IRISH POTATOES"},
      {"sic":"0139",
        "sic_desc":"CROPS, EXCEPT CASH GRAINS, NEC"},
      {"sic":"0161",
        "sic_desc":"VEGETABLES AND MELONS"},
      {"sic":"0171",
        "sic_desc":"BERRY CROPS"},
      {"sic":"0172",
        "sic_desc":"GRAPES"},
      {"sic":"0173",
        "sic_desc":"TREE NUTS"},
      {"sic":"0174",
        "sic_desc":"CITRUS FRUITS"},
      {"sic":"0175",
        "sic_desc":"DECIDUOUS TREE FRUITS"},
      {"sic":"0179",
        "sic_desc":"FRUITS AND TREE NUTS, NEC"},
      {"sic":"0181",
        "sic_desc":"ORNAMENTAL NURSERY PRODUCTS"},
      {"sic":"0182",
        "sic_desc":"FOOD CROPS GROWN UNDER COVER"},
      {"sic":"0191",
        "sic_desc":"GENERAL FARMS, PRIMARILY CROP"},
      {"sic":"0211",
        "sic_desc":"BEEF CATTLE FEEDLOTS"},
      {"sic":"0212",
        "sic_desc":"BEEF CATTLE, EXCEPT FEEDLOTS"},
      {"sic":"0213",
        "sic_desc":"HOGS"},
      {"sic":"0214",
        "sic_desc":"SHEEP AND GOATS"},
      {"sic":"0219",
        "sic_desc":"GENERAL LIVESTOCK, NEC"},
      {"sic":"0241",
        "sic_desc":"DAIRY FARMS"},
      {"sic":"0251",
        "sic_desc":"BROIL, FRY AND ROAST CHICKENS"},
      {"sic":"0252",
        "sic_desc":"CHICKEN EGGS"},
      {"sic":"0253",
        "sic_desc":"TURKEY AND TURKEY EGGS"},
      {"sic":"0254",
        "sic_desc":"POULTRY HATCHERIES"},
      {"sic":"0259",
        "sic_desc":"POULTRY AND EGGS, NEC"},
      {"sic":"0271",
        "sic_desc":"FUR-BEARING ANIMALS & RABBITS"},
      {"sic":"0272",
        "sic_desc":"HORSES AND OTHER EQUINES"},
      {"sic":"0273",
        "sic_desc":"ANIMAL AQUACULTURE"},
      {"sic":"0279",
        "sic_desc":"ANIMAL SPECIALTIES, NEC"},
      {"sic":"0291",
        "sic_desc":"FARMS, PRIMARILY LIVESTOCK"},
      {"sic":"0711",
        "sic_desc":"SOIL PREPARATION SERVICES"},
      {"sic":"0721",
        "sic_desc":"CROP PLANTING & PROTECTION"},
      {"sic":"0722",
        "sic_desc":"HARVESTING, PRIMARILY MACHINE"},
      {"sic":"0723",
        "sic_desc":"CROP PREP SERVICES FOR MARKET"},
      {"sic":"0724",
        "sic_desc":"COTTON GINNING"},
      {"sic":"0741",
        "sic_desc":"VET SERVICES FOR LIVESTOCK"},
      {"sic":"0742",
        "sic_desc":"VET SERV FOR ANIMAL SPECIALTY"},
      {"sic":"0751",
        "sic_desc":"LIVESTOCK SERVICES, EXCEPT VET"},
      {"sic":"0752",
        "sic_desc":"ANIMAL SPECIAL SERV EXCEPT VET"},
      {"sic":"0761",
        "sic_desc":"FARM LABOR CONTRACT & CREW"},
      {"sic":"0762",
        "sic_desc":"FARM MANAGEMENT SERVICES"},
      {"sic":"0781",
        "sic_desc":"LANDSCAPE COUNSELING AND PLAN"},
      {"sic":"0782",
        "sic_desc":"LAWN AND GARDEN SERVICES"},
      {"sic":"0783",
        "sic_desc":"ORNAMENTAL SHRUB AND TREE SERV"},
      {"sic":"0811",
        "sic_desc":"TIMBER TRACTS"},
      {"sic":"0831",
        "sic_desc":"FOREST PRODUCTS"},
      {"sic":"0851",
        "sic_desc":"FORESTRY SERVICES"},
      {"sic":"0912",
        "sic_desc":"FINFISH"},
      {"sic":"0913",
        "sic_desc":"SHELLFISH"},
      {"sic":"0919",
        "sic_desc":"MISCELLANEOUS MARINE PRODUCTS"},
      {"sic":"0921",
        "sic_desc":"FISH HATCHERIES AND PRESERVES"},
      {"sic":"0971",
        "sic_desc":"HUNT & TRAP & GAME PROPOGATION"},
      {"sic":"1011",
        "sic_desc":"IRON ORES"},
      {"sic":"1021",
        "sic_desc":"COPPER ORES"},
      {"sic":"1031",
        "sic_desc":"LEAD AND ZINC ORES"},
      {"sic":"1041",
        "sic_desc":"GOLD ORES"},
      {"sic":"1044",
        "sic_desc":"SILVER ORES"},
      {"sic":"1061",
        "sic_desc":"FERROALLOY ORES, EXCL VANADIUM"},
      {"sic":"1081",
        "sic_desc":"METAL MINING SERVICES"},
      {"sic":"1094",
        "sic_desc":"URANIUM-RADIUM-VANADIUM ORES"},
      {"sic":"1099",
        "sic_desc":"METAL ORES, NEC"},
      {"sic":"3264",
        "sic_desc":"PORCELAIN ELECTRICAL SUPPLIES"},
      {"sic":"3269",
        "sic_desc":"POTTERY PRODUCTS, NEC"},
      {"sic":"3271",
        "sic_desc":"CONCRETE BLOCK & BRICK"},
      {"sic":"1221",
        "sic_desc":"BITUMINOUS COAL & LIG, SURFACE"},
      {"sic":"1222",
        "sic_desc":"BITUMINOUS COAL & LIG, UNDERGR"},
      {"sic":"1231",
        "sic_desc":"ANTHRACITE MINING"},
      {"sic":"1241",
        "sic_desc":"COAL MINING SERVICE"},
      {"sic":"1311",
        "sic_desc":"CRUDE PETROLEUM & NATURAL GAS"},
      {"sic":"1321",
        "sic_desc":"NATURAL GAS LIQUIDS"},
      {"sic":"1381",
        "sic_desc":"DRILLING OIL AND GAS WELLS"},
      {"sic":"1382",
        "sic_desc":"OIL AND GAS FIELD EXPLORATION"},
      {"sic":"1389",
        "sic_desc":"OIL AND & FIELD SERVICES, NEC"},
      {"sic":"1411",
        "sic_desc":"DIMENSION STONE"},
      {"sic":"1422",
        "sic_desc":"CRUSHED AND BROKEN LIMESTONE"},
      {"sic":"1423",
        "sic_desc":"CRUSHED AND BROKEN GRANITE"},
      {"sic":"1429",
        "sic_desc":"CRUSHED AND BROKEN STONE, NEC"},
      {"sic":"1442",
        "sic_desc":"CONSTRUCTION SAND AND GRAVEL"},
      {"sic":"1446",
        "sic_desc":"INDUSTRIAL SAND"},
      {"sic":"1455",
        "sic_desc":"KAOLIN AND BALL CLAY"},
      {"sic":"1459",
        "sic_desc":"CLAY, CERAMIC & REFRAC MAT NEC"},
      {"sic":"1474",
        "sic_desc":"POTASH, SODA & BORATE MINERALS"},
      {"sic":"1475",
        "sic_desc":"PHOSPHATE ROCK"},
      {"sic":"1479",
        "sic_desc":"CHEM & FERT MINERA MINING, NEC"},
      {"sic":"1481",
        "sic_desc":"NONMETAL MINERAL (EXCEPT FUELS"},
      {"sic":"1499",
        "sic_desc":"MISC NONMETAL MINERALS, NEC"},
      {"sic":"1521",
        "sic_desc":"CONTRACTORS-SINGLE FAMILY HOUS"},
      {"sic":"1522",
        "sic_desc":"GEN CONTRACT-RES, NOT SINFA"},
      {"sic":"1531",
        "sic_desc":"OPERATIVE BUILDERS"},
      {"sic":"1541",
        "sic_desc":"GEN CONTRACT-INDUST. BLDGS."},
      {"sic":"1542",
        "sic_desc":"GEN CONTRACT, NON-RES BLDGS."},
      {"sic":"1611",
        "sic_desc":"HWY & ST CONST., EXC. ELEV HWY"},
      {"sic":"1622",
        "sic_desc":"BRIDGE, TUNNEL & ELEV HWY CONS"},
      {"sic":"1623",
        "sic_desc":"H2O, SEW, PIPE & COM. & POWR"},
      {"sic":"1629",
        "sic_desc":"HEAVY CONSTRUCTION, NEC"},
      {"sic":"1711",
        "sic_desc":"PLUMB, HEAT & AIR CONDITIONING"},
      {"sic":"1721",
        "sic_desc":"PAINTING AND PAPER HANGING"},
      {"sic":"1731",
        "sic_desc":"ELECTRICAL WORK"},
      {"sic":"1741",
        "sic_desc":"MASONRY, STONE SET, STONE WORK"},
      {"sic":"1742",
        "sic_desc":"PLSTR, DRYWALL, ACOUS, & INSUL"},
      {"sic":"1743",
        "sic_desc":"TERRAZZO,TILE,MARBLE, MOSAIC"},
      {"sic":"1751",
        "sic_desc":"CARPENTRY WORK"},
      {"sic":"1752",
        "sic_desc":"FLOOR LAY & OTHER FLOOR WORK"},
      {"sic":"1761",
        "sic_desc":"ROOF, SIDE & SHEET METAL WORK"},
      {"sic":"1771",
        "sic_desc":"CONCRETE WORK"},
      {"sic":"1781",
        "sic_desc":"WATER WELL DRILLING"},
      {"sic":"1791",
        "sic_desc":"STRUCTURAL STEEL ERECTION"},
      {"sic":"1793",
        "sic_desc":"GLASS AND GLAZING WORK"},
      {"sic":"1794",
        "sic_desc":"EXCAVATION WORK"},
      {"sic":"1795",
        "sic_desc":"WRECKING AND DEMOLTION WORK"},
      {"sic":"1796",
        "sic_desc":"INST OR ERECTION OF BLDG EQUIP"},
      {"sic":"1799",
        "sic_desc":"SPECIAL TRADE CONTRACTORS, NEC"},
      {"sic":"2011",
        "sic_desc":"MEAT PACKING PLANTS"},
      {"sic":"2013",
        "sic_desc":"SAUSAGES & PREPARED MEAT PROD"},
      {"sic":"2015",
        "sic_desc":"POULTRY SLAUGHTERING & PROCESS"},
      {"sic":"2021",
        "sic_desc":"CREAMERY BUTTER"},
      {"sic":"2022",
        "sic_desc":"CHEESE, NATURAL AND PROCESSED"},
      {"sic":"2023",
        "sic_desc":"CONDENSED AND EVAPORATED MILK"},
      {"sic":"2024",
        "sic_desc":"ICE CREAM AND FROZEN DESSERTS"},
      {"sic":"2026",
        "sic_desc":"FLUID MILK"},
      {"sic":"2032",
        "sic_desc":"CANNED SPECIALTIES"},
      {"sic":"2033",
        "sic_desc":"CANNED FRUITS, VEG, PRES, JAM"},
      {"sic":"2034",
        "sic_desc":"DEHYDRATED FRUITS, VEG, SOUPS"},
      {"sic":"2035",
        "sic_desc":"PICKLED FRTS & VEG. SAUCES"},
      {"sic":"2037",
        "sic_desc":"FROZEN FRTS, FRT JUICES & VEG"},
      {"sic":"2038",
        "sic_desc":"FROZEN SPECIALTIES, NEC"},
      {"sic":"2041",
        "sic_desc":"FLOUR & OTHER GRAIN MILL PROD"},
      {"sic":"2043",
        "sic_desc":"CEREAL BREAKFAST FOODS"},
      {"sic":"2044",
        "sic_desc":"RICE MILLING"},
      {"sic":"2045",
        "sic_desc":"BLENDED AND PREPARED FLOUR"},
      {"sic":"2046",
        "sic_desc":"WET CORN MILLING"},
      {"sic":"2047",
        "sic_desc":"DOG AND CAT FOOD"},
      {"sic":"2048",
        "sic_desc":"PREP FEEDS & INGRED FOR ANIMA"},
      {"sic":"2051",
        "sic_desc":"BREAD & OTHER BAKERY PRODUCTS"},
      {"sic":"2052",
        "sic_desc":"COOKIES AND CRACKERS"},
      {"sic":"2053",
        "sic_desc":"FROZEN BAKERY PRODUCTS"},
      {"sic":"2061",
        "sic_desc":"CANE SUGAR, EXCEPT REFINE ONLY"},
      {"sic":"2062",
        "sic_desc":"CANE SUGAR REFINING"},
      {"sic":"2063",
        "sic_desc":"BEET SUGAR"},
      {"sic":"2064",
        "sic_desc":"CANDY & OTHER CONFECTION PROD"},
      {"sic":"2066",
        "sic_desc":"CHOCOLATE AND COCOA PRODUCTS"},
      {"sic":"2067",
        "sic_desc":"CHEWING GUM"},
      {"sic":"2068",
        "sic_desc":"SALTED & ROASTED NUTS & SEEDS"},
      {"sic":"2074",
        "sic_desc":"COTTONSEED OIL MILLS"},
      {"sic":"2075",
        "sic_desc":"SOYBEAN OIL MILLS"},
      {"sic":"2076",
        "sic_desc":"VEG. OIL MILLS, EXCEPT CORN"},
      {"sic":"2077",
        "sic_desc":"ANIMAL AND MARINE FATS & OILS"},
      {"sic":"2079",
        "sic_desc":"SHORT, TABLE OILS, MARGERINE"},
      {"sic":"2082",
        "sic_desc":"MALT BEVERAGES"},
      {"sic":"2083",
        "sic_desc":"MALT"},
      {"sic":"2084",
        "sic_desc":"WINES, BRANDY & BRANDY SPIRIT"},
      {"sic":"2085",
        "sic_desc":"DIST, RECTIFIED & BLENDED LIQ"},
      {"sic":"2086",
        "sic_desc":"BOT & CAN SOFT DRNK & CARB WA"},
      {"sic":"2087",
        "sic_desc":"FLAV EXTR & FLAV SYRUPS, NEC"},
      {"sic":"2091",
        "sic_desc":"CANNED & CURED FISH & SEAFOOD"},
      {"sic":"2092",
        "sic_desc":"FRE OR FROZ PCK FISH, SEAFOOD"},
      {"sic":"2095",
        "sic_desc":"ROASTED COFFEE"},
      {"sic":"2096",
        "sic_desc":"POTATO CHIPS & SIMILAR SNACKS"},
      {"sic":"2097",
        "sic_desc":"MANUFACTURED ICE"},
      {"sic":"2098",
        "sic_desc":"MACARONI, SPAGH, VERMI, NOODL"},
      {"sic":"2099",
        "sic_desc":"FOOD PREPARATIONS, NEC"},
      {"sic":"2111",
        "sic_desc":"CIGARETTES"},
      {"sic":"2121",
        "sic_desc":"CIGARS"},
      {"sic":"2131",
        "sic_desc":"TOBACCO (CHEW & SMOK) & SNUFF"},
      {"sic":"2141",
        "sic_desc":"TOBACCO STEMMING AND REDRYING"},
      {"sic":"2211",
        "sic_desc":"BROAD WOVEN FABRIC MILLS, COTT"},
      {"sic":"2221",
        "sic_desc":"BROAD WOVEN FABRIC MILLS, SYNT"},
      {"sic":"2231",
        "sic_desc":"BROAD WOVEN FABRIC MILLS, WOOL"},
      {"sic":"2241",
        "sic_desc":"NARROW FAB & OTHER SMALLWARES"},
      {"sic":"2251",
        "sic_desc":"WOMEN'S FULL/KNEE LENGTH HOSRY"},
      {"sic":"2252",
        "sic_desc":"HOSIERY, NEC"},
      {"sic":"2253",
        "sic_desc":"KNIT OUTERWEAR MILLS"},
      {"sic":"2254",
        "sic_desc":"KNIT UNDERWEAR MILLS"},
      {"sic":"2257",
        "sic_desc":"CIRCULAR KNIT FABRIC MILLS"},
      {"sic":"2258",
        "sic_desc":"WARP KNIT FABRIC MILLS"},
      {"sic":"2259",
        "sic_desc":"KNITTING MILLS, NEC"},
      {"sic":"2261",
        "sic_desc":"FINISH OF BRD WOV FAB OF COTTN"},
      {"sic":"2262",
        "sic_desc":"FINISH OF BRD WOV FAB/MAN-MADE"},
      {"sic":"2269",
        "sic_desc":"FINISHERS OF TEXTILES, NEC"},
      {"sic":"2273",
        "sic_desc":"CARPETS AND RUGS, NEC"},
      {"sic":"3581",
        "sic_desc":"AUTOMATIC MERCHANDISING MACHIN"},
      {"sic":"3582",
        "sic_desc":"COMMERCIAL LAUNDRY EQUIPMENT"},
      {"sic":"3585",
        "sic_desc":"REFRIGERATION & HEATING EQUIP"},
      {"sic":"3586",
        "sic_desc":"MEASURING & DISPENSING PUMPS"},
      {"sic":"3589",
        "sic_desc":"SERVICE INDUSTRY MACHINERY"},
      {"sic":"3592",
        "sic_desc":"CARBURETORS,PISTONS,RINGS,VALV"},
      {"sic":"3593",
        "sic_desc":"FLUID POWER CYLINDERS & ACTUAT"},
      {"sic":"3594",
        "sic_desc":"FLUID POWER PUMPS AND MOTORS"},
      {"sic":"3596",
        "sic_desc":"SCALES AND BALANCES, EXC. LAB"},
      {"sic":"3599",
        "sic_desc":"INDUSTRIAL MACHINERY, NEC"},
      {"sic":"3612",
        "sic_desc":"TRANSFORMERS"},
      {"sic":"3613",
        "sic_desc":"SWITCHGEAR & SWITCHBOARD APPAR"},
      {"sic":"3621",
        "sic_desc":"MOTORS AND GENERATORS"},
      {"sic":"3624",
        "sic_desc":"CARBON AND GRAPHITE PRODUCTS"},
      {"sic":"3625",
        "sic_desc":"RELAYS AND INDUSTRIAL CONTROLS"},
      {"sic":"3629",
        "sic_desc":"ELECTRICAL INDUSTRIAL APPARATS"},
      {"sic":"3631",
        "sic_desc":"HOUSEHOLD COOKING EQUIPMENT"},
      {"sic":"3632",
        "sic_desc":"HOUSEHOLD REFRIG. & FREEZERS"},
      {"sic":"3633",
        "sic_desc":"HOUSEHOLD LAUNDRY EQUIPMENT"},
      {"sic":"3634",
        "sic_desc":"ELECTRIC HOUSEWARES AND FANS"},
      {"sic":"3635",
        "sic_desc":"HOUSEHOLD VACUUM CLEANERS"},
      {"sic":"3639",
        "sic_desc":"HOUSEHOLD APPLIANCES, NEC"},
      {"sic":"3641",
        "sic_desc":"ELECTRIC LAMPS"},
      {"sic":"3643",
        "sic_desc":"CURRENT-CARRYING WIRING DEVICE"},
      {"sic":"3644",
        "sic_desc":"NONCURRENT-CARRYING WIRING DEV"},
      {"sic":"3645",
        "sic_desc":"RESIDENTIAL LIGHTING FIXTURES"},
      {"sic":"3646",
        "sic_desc":"COMMERCIAL LIGHTING FIXTURES"},
      {"sic":"3647",
        "sic_desc":"VEHICULAR LIGHTING EQUIPMENT"},
      {"sic":"3648",
        "sic_desc":"LIGHTING EQUIPMENT, NEC"},
      {"sic":"3651",
        "sic_desc":"RADIO AND TV RECEIVING SETS"},
      {"sic":"3652",
        "sic_desc":"PHONOGRAPH RECORDS"},
      {"sic":"3661",
        "sic_desc":"TELEPHONE/TELEGRAPH APPARATUS"},
      {"sic":"3663",
        "sic_desc":"RADIO & TV COMMUNICATION EQUIP"},
      {"sic":"3669",
        "sic_desc":"COMMUNICATIONS EQUIPMENT, NEC."},
      {"sic":"3671",
        "sic_desc":"ELECTRON TUBES"},
      {"sic":"3672",
        "sic_desc":"PRINTED CIRCUT BOARD"},
      {"sic":"3674",
        "sic_desc":"SEMICONDUCTORS & RELATED DEVIC"},
      {"sic":"3675",
        "sic_desc":"ELECTRONIC CAPACITORS"},
      {"sic":"3676",
        "sic_desc":"RESISTORS FOR ELEC APPLICATION"},
      {"sic":"3677",
        "sic_desc":"ELEC COILS, TRANSF. & INDUCTOR"},
      {"sic":"3678",
        "sic_desc":"CONNECTORS FOR ELEC APPLICATIO"},
      {"sic":"3679",
        "sic_desc":"ELECTRONIC COMPONENTS, NEC"},
      {"sic":"3691",
        "sic_desc":"STORAGE BATTERIES"},
      {"sic":"3692",
        "sic_desc":"PRIMARY BATTERIES, DRY & WET"},
      {"sic":"3694",
        "sic_desc":"ELEC EQUIP FOR INT COMBUS ENGI"},
      {"sic":"3695",
        "sic_desc":"MAG & OPTICAL RECORDING MEDIA"},
      {"sic":"3699",
        "sic_desc":"ELEC MACHINERY,EQUIP & SUPPLIE"},
      {"sic":"3711",
        "sic_desc":"MOTOR VEHICLES & CAR BODIES"},
      {"sic":"3713",
        "sic_desc":"TRUCK & BUS BODIES"},
      {"sic":"3714",
        "sic_desc":"MOTOR VEHICLE PARTS & ACCESSOR"},
      {"sic":"3715",
        "sic_desc":"TRUCK TRAILERS"},
      {"sic":"3716",
        "sic_desc":"MOTOR HOMES"},
      {"sic":"3721",
        "sic_desc":"AIRCRAFT"},
      {"sic":"3724",
        "sic_desc":"AIRCRAFT ENGINES & ENGINE PART"},
      {"sic":"3728",
        "sic_desc":"AIRCRAFT PARTS AND EQUIP, NEC"},
      {"sic":"3731",
        "sic_desc":"SHIP BUILDING AND REPAIRING"},
      {"sic":"3272",
        "sic_desc":"CONCRETE PROD EXC BLCK & BRICK"},
      {"sic":"3273",
        "sic_desc":"READY-MIXED CONCRETE"},
      {"sic":"3274",
        "sic_desc":"LIME"},
      {"sic":"3275",
        "sic_desc":"GYPSUM PRODUCTS"},
      {"sic":"3281",
        "sic_desc":"CUT STONE & STONE PRODUCTS"},
      {"sic":"3291",
        "sic_desc":"ABRASIVE PRODUCTS"},
      {"sic":"3292",
        "sic_desc":"ASBESTOS PRODUCTS"},
      {"sic":"3295",
        "sic_desc":"MINE & EARTHS, GROUND OR TREAT"},
      {"sic":"3296",
        "sic_desc":"MINERAL WOOL"},
      {"sic":"3297",
        "sic_desc":"NONCLAY REFRACTORIES"},
      {"sic":"3299",
        "sic_desc":"NONMETALLIC MINERAL PROD, NEC"},
      {"sic":"3312",
        "sic_desc":"BLAST FURN/STEEL WORKS/ROLLING"},
      {"sic":"3313",
        "sic_desc":"ELECTROMETALLURGICAL PRODUCTS"},
      {"sic":"3315",
        "sic_desc":"STEEL WIRE DRAW & STEEL NAILS"},
      {"sic":"3316",
        "sic_desc":"COLD ROLLED STEEL SHEET/STRIP"},
      {"sic":"3317",
        "sic_desc":"STEEL PIPE AND TUBES"},
      {"sic":"3321",
        "sic_desc":"GRAY IRON FOUNDRIES"},
      {"sic":"3322",
        "sic_desc":"MALLEABLE IRON FOUNDRIES"},
      {"sic":"3324",
        "sic_desc":"STEEL INVESTMENT FOUNDRIES"},
      {"sic":"3325",
        "sic_desc":"STEEL FOUNDRIES, NEC"},
      {"sic":"3331",
        "sic_desc":"PRIMRY SMELTING & COPPER REFIN"},
      {"sic":"3334",
        "sic_desc":"PRIMARY PRODUCTION OF ALUMINUM"},
      {"sic":"3339",
        "sic_desc":"PRMRY SMELT/NONFERROUS METALS"},
      {"sic":"3341",
        "sic_desc":"2NDARY SMELT/NONFERROUS METALS"},
      {"sic":"3351",
        "sic_desc":"ROLL/DRAW/EXTRUDING OF COPPER"},
      {"sic":"3353",
        "sic_desc":"ALUMINUM SHEET, PLATE AND FOIL"},
      {"sic":"3354",
        "sic_desc":"ALUMINUM EXTRUDED PRODUCTS"},
      {"sic":"3355",
        "sic_desc":"ALUMINUM ROLLING & DRAWING NEC"},
      {"sic":"3356",
        "sic_desc":"ROLL, DRAW & EXTRUD NONFERROUS"},
      {"sic":"3357",
        "sic_desc":"DRAW/INSULAT OF NONFERROUS WIR"},
      {"sic":"3363",
        "sic_desc":"ALUMINUM DIE CASTING"},
      {"sic":"3364",
        "sic_desc":"NONFERROUS DIE CAST, EXC. ALUM"},
      {"sic":"3365",
        "sic_desc":"ALUMINUM FOUNDRIES"},
      {"sic":"3366",
        "sic_desc":"COPPER FOUNDRIES"},
      {"sic":"3369",
        "sic_desc":"NONFERROUS FOUNDRIES, EXC ALUM"},
      {"sic":"3398",
        "sic_desc":"METAL HEAT TREATING"},
      {"sic":"3399",
        "sic_desc":"PRIMARY METAL PRODUCTS, NEC"},
      {"sic":"3411",
        "sic_desc":"METAL CANS"},
      {"sic":"3412",
        "sic_desc":"METAL BARRELS, DRUMS AND PAILS"},
      {"sic":"3421",
        "sic_desc":"CUTLERY"},
      {"sic":"3423",
        "sic_desc":"HAND AND EDGE TOOLS, NEC"},
      {"sic":"3425",
        "sic_desc":"HAND SAWS AND SAW BLADES"},
      {"sic":"3429",
        "sic_desc":"HARDWARE, NEC"},
      {"sic":"3431",
        "sic_desc":"METAL SANITARY WARE"},
      {"sic":"3432",
        "sic_desc":"PLUMB FIXTURE FITTINGS & TRIM"},
      {"sic":"3433",
        "sic_desc":"HEATING EQUIP, EXCEPT ELECTRIC"},
      {"sic":"3441",
        "sic_desc":"FABRICATED STRUCTURAL METAL"},
      {"sic":"3442",
        "sic_desc":"METAL DOORS, SASH, AND TRIM"},
      {"sic":"3443",
        "sic_desc":"FAB PLATE WORK (BOILER SHOPS)"},
      {"sic":"3444",
        "sic_desc":"SHEET METAL WORK"},
      {"sic":"3446",
        "sic_desc":"ARCHITECTURAL METAL WORK"},
      {"sic":"3448",
        "sic_desc":"PREFABRICATED METAL BUILDINGS"},
      {"sic":"3449",
        "sic_desc":"MISC. STRUCTUAL METAL WORK"},
      {"sic":"3451",
        "sic_desc":"SCREW MACHINE PRODUCTS"},
      {"sic":"3452",
        "sic_desc":"BOLTS, NUTS, RIVETS & WASHERS"},
      {"sic":"3462",
        "sic_desc":"IRON AND STEEL FORGINGS"},
      {"sic":"5944",
        "sic_desc":"JEWELERY STORES"},
      {"sic":"5945",
        "sic_desc":"HOBBY, TOY AND GAME SHOPS"},
      {"sic":"5946",
        "sic_desc":"CAMERA & PHOTO SUPPLY STORES"},
      {"sic":"5947",
        "sic_desc":"GIFT, NOVELTY & SOUVENIR SHOPS"},
      {"sic":"5948",
        "sic_desc":"LUGGAGE & LEATHER GOODS STORES"},
      {"sic":"5949",
        "sic_desc":"SEW/NEEDLEWK/PIECE GOODS STORE"},
      {"sic":"5961",
        "sic_desc":"CATALOG AND MAIL-ORDER HOUSES"},
      {"sic":"5962",
        "sic_desc":"AUTO MERCHANDIS MACHINE OPERAT"},
      {"sic":"5963",
        "sic_desc":"DIRECT SELLING ESTABLISHMENTS"},
      {"sic":"5983",
        "sic_desc":"FUEL OIL DEALERS"},
      {"sic":"5984",
        "sic_desc":"LIQ PETROL GAS (BOT GAS) DEALR"},
      {"sic":"5989",
        "sic_desc":"FUEL DEALERS, NEC"},
      {"sic":"5992",
        "sic_desc":"FLORISTS"},
      {"sic":"5993",
        "sic_desc":"TOBACCO STORES AND STANDS"},
      {"sic":"5994",
        "sic_desc":"NEWS DEALERS AND NEWSSTANDS"},
      {"sic":"5995",
        "sic_desc":"OPTICAL GOODS STORES"},
      {"sic":"5999",
        "sic_desc":"MISCELLANEOUS RETAIL STORES"},
      {"sic":"6011",
        "sic_desc":"FEDERAL RESERVE BANKS"},
      {"sic":"6019",
        "sic_desc":"CENTRAL RESERVE REPOSITORY"},
      {"sic":"6021",
        "sic_desc":"NATIONAL COMMERCIAL BANKS"},
      {"sic":"6022",
        "sic_desc":"STATE COMMERCIAL BANKS"},
      {"sic":"6029",
        "sic_desc":"COMMERCIAL BANKS, NEC"},
      {"sic":"6035",
        "sic_desc":"FEDERAL SAVINGS INSTITUTIONS"},
      {"sic":"6036",
        "sic_desc":"SAVINGS INSTITUTIONS, EXC FED"},
      {"sic":"6061",
        "sic_desc":"FEDERAL CREDIT UNIONS"},
      {"sic":"6062",
        "sic_desc":"STATE CREDIT UNIONS"},
      {"sic":"6081",
        "sic_desc":"FOREIGN BANK & BRANCHES & AGEN"},
      {"sic":"6082",
        "sic_desc":"FOREIGN TRADE & INTERNAT BANKS"},
      {"sic":"6091",
        "sic_desc":"NONDEPOSIT TRUST FACILTIES"},
      {"sic":"6099",
        "sic_desc":"FUNCT RELATED TO DEP BANKING"},
      {"sic":"6111",
        "sic_desc":"FEDERAL & FED-SPONSORED CREDIT"},
      {"sic":"6141",
        "sic_desc":"PERSONAL CREDIT INSTITUTIONS"},
      {"sic":"6153",
        "sic_desc":"SHORT-TERM BUS. CREDIT INSTITU"},
      {"sic":"6159",
        "sic_desc":"MISC BUSINESS CREDIT INSTITUTI"},
      {"sic":"6162",
        "sic_desc":"MORTG BANKERS & LOAN CORRESPON"},
      {"sic":"6163",
        "sic_desc":"LOAN BROKERS"},
      {"sic":"6211",
        "sic_desc":"SEC BROKERS/DEALERS/FLOTAT. CO"},
      {"sic":"6221",
        "sic_desc":"COMMODITY CONTR BROKERS & DEAL"},
      {"sic":"6231",
        "sic_desc":"SECURITY & COMMODITY EXCHANGES"},
      {"sic":"6282",
        "sic_desc":"INVESTMENT ADVICE"},
      {"sic":"6289",
        "sic_desc":"SECURITY & COMMODITY SERVICES"},
      {"sic":"6311",
        "sic_desc":"LIFE INSURANCE"},
      {"sic":"6321",
        "sic_desc":"ACCIDENT AND HEALTH INSURANCE"},
      {"sic":"6324",
        "sic_desc":"HOSPITAL & MEDICAL SERV PLANS"},
      {"sic":"6331",
        "sic_desc":"FIRE, MARINE & CASUALTY INSUR"},
      {"sic":"6351",
        "sic_desc":"SURETY INSURANCE"},
      {"sic":"6361",
        "sic_desc":"TITLE INSURANCE"},
      {"sic":"6371",
        "sic_desc":"PENSION, HEALTH & WELFARE FUND"},
      {"sic":"6399",
        "sic_desc":"INSURANCE CARRIERS, NEC"},
      {"sic":"6411",
        "sic_desc":"INSUR AGENTS, BROKERS, & SERVI"},
      {"sic":"6512",
        "sic_desc":"OPER OF NONRESIDENTIAL BLDGS"},
      {"sic":"6513",
        "sic_desc":"OPERATORS OF APART BUILDINGS"},
      {"sic":"6514",
        "sic_desc":"OPER OF DWELL OTHER THAN APART"},
      {"sic":"6515",
        "sic_desc":"OPER OF RES MOBILE HOME SITES"},
      {"sic":"6517",
        "sic_desc":"LESSORS OF RAILROAD PROPERTIES"},
      {"sic":"6519",
        "sic_desc":"LESSORS OF REAL PROPERTY, NEC"},
      {"sic":"6531",
        "sic_desc":"REAL ESTATE AGENTS & MANAGERS"},
      {"sic":"6541",
        "sic_desc":"TITLE ABSTRACT OFFICES"},
      {"sic":"6552",
        "sic_desc":"LAND SUBDIVIDERS & DEV, EX CEM"},
      {"sic":"6553",
        "sic_desc":"CEMETERY SUBDIVIDERS & DEVELOP"},
      {"sic":"6712",
        "sic_desc":"BANK HOLDING COMPANIES"},
      {"sic":"6719",
        "sic_desc":"HOLDING COMPANIES, NEC"},
      {"sic":"6722",
        "sic_desc":"MGMT INVEST. OFFICES, OPEN END"},
      {"sic":"6726",
        "sic_desc":"INVESTMENT OFFICES, NEC"},
      {"sic":"6732",
        "sic_desc":"EDUCAT.,RELIG & CHARITY TRUSTS"},
      {"sic":"6733",
        "sic_desc":"TRUSTS,EXC EDUCAT,RELIG & CHAR"},
      {"sic":"6792",
        "sic_desc":"OIL ROYALTY TRADERS"},
      {"sic":"6794",
        "sic_desc":"PATENT OWNERS AND LESSORS"},
      {"sic":"6798",
        "sic_desc":"REAL ESTATE INVESTMENT TRUSTS"},
      {"sic":"6799",
        "sic_desc":"INVESTORS, NEC"},
      {"sic":"7011",
        "sic_desc":"HOTELS AND MOTELS"},
      {"sic":"7021",
        "sic_desc":"ROOMING AND BOARDING HOUSES"},
      {"sic":"7032",
        "sic_desc":"SPORTING & RECREATIONAL CAMPS"},
      {"sic":"7033",
        "sic_desc":"REC VEHICLE PARKS & CAMPSITES"},
      {"sic":"7041",
        "sic_desc":"ORG. HOTEL & LODG HSE, ON MEMB"},
      {"sic":"7211",
        "sic_desc":"POWER LAUNDRIES, RES & COMMERC"},
      {"sic":"7212",
        "sic_desc":"GARM PRESSING/LAUNDRIES/DRYCLE"},
      {"sic":"7213",
        "sic_desc":"LINEN SUPPLY"},
      {"sic":"7215",
        "sic_desc":"COIN-OPERATED LAUNDRIES/DRYCLE"},
      {"sic":"7216",
        "sic_desc":"DRYCLEAN PLANTS, EXC RUG CLEAN"},
      {"sic":"7217",
        "sic_desc":"CARPET & UPHOLSTERY CLEANING"},
      {"sic":"7218",
        "sic_desc":"INDUSTRIAL LAUNDERERS"},
      {"sic":"7219",
        "sic_desc":"LAUNDRY & GARMENT SERVICES,NEC"},
      {"sic":"7221",
        "sic_desc":"PHOTOGRAPHIC STUDIOS, POTRAIT"},
      {"sic":"7231",
        "sic_desc":"BEAUTY SHOPS"},
      {"sic":"7241",
        "sic_desc":"BARBER SHOPS"},
      {"sic":"7251",
        "sic_desc":"SHOE REP SHOPS & SHOESHINE PAR"},
      {"sic":"7261",
        "sic_desc":"FUNERAL SERVICES & CREMATORIES"},
      {"sic":"7291",
        "sic_desc":"TAX AND PREPARATION SERVICES"},
      {"sic":"7299",
        "sic_desc":"MISCELLANEOUS PERSONAL SERVICE"},
      {"sic":"7311",
        "sic_desc":"ADVERTISING AGENCIES"},
      {"sic":"7312",
        "sic_desc":"OUTDOOR ADVERTISING AGENCIES"},
      {"sic":"7313",
        "sic_desc":"RADIO, TV & PUBLISHERS AD REPS"},
      {"sic":"7319",
        "sic_desc":"ADVERTISING, NEC"},
      {"sic":"7322",
        "sic_desc":"ADJUSTMENT & COLLECT SERVICES"},
      {"sic":"7323",
        "sic_desc":"CREDIT REPORTING SERVICES"},
      {"sic":"7331",
        "sic_desc":"DIRECT MAIL ADVERTIS SERVICES"},
      {"sic":"7334",
        "sic_desc":"PHOTOCOPYING/DUPLICATING SERV"},
      {"sic":"7335",
        "sic_desc":"COMMERCIAL PHOTOGRAPHY"},
      {"sic":"7336",
        "sic_desc":"COMM ART & GRAPHIC DESIGN"},
      {"sic":"7338",
        "sic_desc":"SECRETARIAL & COURT REPORTING"},
      {"sic":"7342",
        "sic_desc":"DISINFECTING & EXTERMINAT SERV"},
      {"sic":"7349",
        "sic_desc":"BUILDING MAINTNENANCE SERVICE"},
      {"sic":"7352",
        "sic_desc":"MEDICAL EQUIPMENT RENTAL"},
      {"sic":"7353",
        "sic_desc":"HEAVY CONSTRUCTON EQUIP RENTAL"},
      {"sic":"7359",
        "sic_desc":"EQUIPMENT RENTAL AND LEASING,"},
      {"sic":"7361",
        "sic_desc":"EMPLOYMENT AGENCIES"},
      {"sic":"7363",
        "sic_desc":"HELP SUPPLY SERVICES"},
      {"sic":"7371",
        "sic_desc":"CUSTOM COMPUTER PROG SERVICES"},
      {"sic":"7372",
        "sic_desc":"PREPACKAGED SOFTWARE"},
      {"sic":"7373",
        "sic_desc":"COMPUTER INTEGRATED SYS DESIGN"},
      {"sic":"7374",
        "sic_desc":"DATA PROCESSING & PREPARATION"},
      {"sic":"7375",
        "sic_desc":"INFORMATION RETRIEVAL SERVICES"},
      {"sic":"7376",
        "sic_desc":"COMPUTER FACILITIES MANAGEMENT"},
      {"sic":"7377",
        "sic_desc":"COMPUTER RENTAL AND LEASING"},
      {"sic":"7378",
        "sic_desc":"COMPUTER MAINTENANCE & REPAIR"},
      {"sic":"7379",
        "sic_desc":"COMPUTER RELATED SERVICES, NEC"},
      {"sic":"7381",
        "sic_desc":"DETECTIVE & ARMORED CAR SERVIC"},
      {"sic":"7382",
        "sic_desc":"SECURITY SYSTEMS SERVICES"},
      {"sic":"7383",
        "sic_desc":"NEWS SYNDICATES"},
      {"sic":"7384",
        "sic_desc":"PHOTOFINISHING LABORATORIES"},
      {"sic":"7389",
        "sic_desc":"BUSINESS SERVICES, NEC"},
      {"sic":"7513",
        "sic_desc":"TRUCK RENT & LEASE, NO DRIVERS"},
      {"sic":"7514",
        "sic_desc":"PASSENGER CAR RENTAL"},
      {"sic":"7515",
        "sic_desc":"PASSENGER CAR LEASING"},
      {"sic":"7519",
        "sic_desc":"UTILITY TRAILER & RV RENTAL"},
      {"sic":"7521",
        "sic_desc":"AUTOMOBILE PARKING"},
      {"sic":"7532",
        "sic_desc":"TOP & BODY REPAIR & PAINT SHOP"},
      {"sic":"7533",
        "sic_desc":"AUTO EXHAUST SYSTEM REP SHOPS"},
      {"sic":"7534",
        "sic_desc":"TIRE RETREADING & REPAIR SHOPS"},
      {"sic":"7536",
        "sic_desc":"AUTO GLASS REPLACEMENT SHOPS"},
      {"sic":"7537",
        "sic_desc":"AUTO TRANSMISSION REPAIR SHOPS"},
      {"sic":"7538",
        "sic_desc":"GENERAL AUTO REPAIR SHOPS"},
      {"sic":"7539",
        "sic_desc":"AUTOMOTIVE REPAIR SHOPS, NEC"},
      {"sic":"7542",
        "sic_desc":"CAR WASHES"},
      {"sic":"7549",
        "sic_desc":"AUTO SERV, EXC REP & CARWASHES"},
      {"sic":"7622",
        "sic_desc":"RADIO & TELEVISION REPAIR SHOP"},
      {"sic":"7623",
        "sic_desc":"REFRIG & AC SERV & REP SHOPS"},
      {"sic":"7629",
        "sic_desc":"ELEC & ELECTRONIC REPAIR SHOPS"},
      {"sic":"7631",
        "sic_desc":"WATCH, CLOCK & JEWELRY REPAIR"},
      {"sic":"7641",
        "sic_desc":"REUPHOLSTERY & FURNITURE REP"},
      {"sic":"7692",
        "sic_desc":"WELDING REPAIR"},
      {"sic":"7694",
        "sic_desc":"ARMATURE REWINDING SHOPS"},
      {"sic":"7699",
        "sic_desc":"REPAIR SHOPS & RELATED SERVICE"},
      {"sic":"7812",
        "sic_desc":"MOTION PICTURE & VIDEO PROD"},
      {"sic":"7819",
        "sic_desc":"SERV. ALLIED TO MOTION PICTURE"},
      {"sic":"7822",
        "sic_desc":"MOTION PICTURE & TAPE DISTRIB"},
      {"sic":"7829",
        "sic_desc":"SERV ALLIED TO MOTION PIC DIST"},
      {"sic":"7832",
        "sic_desc":"MOTION PIC THEA., EX DRIVE-IN"},
      {"sic":"7833",
        "sic_desc":"DRIVE-IN MOTION PIC THEATRES"},
      {"sic":"7841",
        "sic_desc":"VIDEO TAPE RENTAL"},
      {"sic":"7911",
        "sic_desc":"DANCE STUDIOS, SCHOOLS & HALLS"},
      {"sic":"7922",
        "sic_desc":"THEA. PROD (EXC MOTION PICTURE"},
      {"sic":"7929",
        "sic_desc":"BANDS, ORCH, ACTORS & ENTERTAI"},
      {"sic":"7933",
        "sic_desc":"BOWLING CENTERS"},
      {"sic":"7941",
        "sic_desc":"PROF SPORTS CLUBS & PROMOTERS"},
      {"sic":"7948",
        "sic_desc":"RACING, INCLUDING TRACK OPERA"},
      {"sic":"7991",
        "sic_desc":"PHYSICAL FITNESS FACILITIES"},
      {"sic":"7992",
        "sic_desc":"PUBLIC GOLF COURSES"},
      {"sic":"7993",
        "sic_desc":"COIN OPERATED AMUSEMENT DEVI"},
      {"sic":"7996",
        "sic_desc":"AMUSEMENT PARKS"},
      {"sic":"7997",
        "sic_desc":"MEMBERSHIP SPORTS & REC CLUBS"},
      {"sic":"7999",
        "sic_desc":"AMUSEMENT AND RECREATION, NEC"},
      {"sic":"8011",
        "sic_desc":"OFFICES & CLINICS OF MED DOCT"},
      {"sic":"8021",
        "sic_desc":"OUTPATIENT CARE FACILITIES"},
      {"sic":"8031",
        "sic_desc":"OFFICES/CLINCS OF DOC OF OSTEO"},
      {"sic":"8041",
        "sic_desc":"OFFICES & CLINICS OF CHIROPRAC"},
      {"sic":"8042",
        "sic_desc":"OFFICES & CLINICS OF OPTOMETRI"},
      {"sic":"8043",
        "sic_desc":"OFFICES & CLINICS OF PODIATRIS"},
      {"sic":"8049",
        "sic_desc":"OFFICES OF HEALTH PRACTITIONER"},
      {"sic":"8051",
        "sic_desc":"SKILLED NURSING CARE FACILITIE"},
      {"sic":"8052",
        "sic_desc":"INTERMEDIATE CARE FACILITIES"},
      {"sic":"8059",
        "sic_desc":"NURSING AND PERSONAL CARE, NEC"},
      {"sic":"8062",
        "sic_desc":"GEN. MEDICAL/SURGICAL HOSPITAL"},
      {"sic":"8063",
        "sic_desc":"PSYCHIATRIC HOSPITALS"},
      {"sic":"8069",
        "sic_desc":"SPECIALTY HOSPITALS"},
      {"sic":"8071",
        "sic_desc":"MEDICAL LABORATORIES"},
      {"sic":"8072",
        "sic_desc":"DENTAL LABORATORIES"},
      {"sic":"8082",
        "sic_desc":"HOME HEALTH CARE SERVICES"},
      {"sic":"8092",
        "sic_desc":"KIDNEY DIALYSIS CENTERS"},
      {"sic":"8093",
        "sic_desc":"SPECIALITY OUTPATIENT CLINICS"},
      {"sic":"8099",
        "sic_desc":"HEALTH & ALLIED SERVICES, NEC"},
      {"sic":"8111",
        "sic_desc":"LEGAL SERVICES"},
      {"sic":"8211",
        "sic_desc":"ELEMENTARY & SECONDARY SCHOOLS"},
      {"sic":"8221",
        "sic_desc":"COLLEGES, UNIV & PROF SCHOOLS"},
      {"sic":"8222",
        "sic_desc":"JUNIOR COLLEGES & TECH INSTITU"},
      {"sic":"8231",
        "sic_desc":"LIBRARIES"},
      {"sic":"8243",
        "sic_desc":"DATA PROCESSING SCHOOLS"},
      {"sic":"8244",
        "sic_desc":"BUSINESS & SECRETARIAL SCHOOLS"},
      {"sic":"8249",
        "sic_desc":"VOCATIONAL SCHOOLS, NEC"},
      {"sic":"8299",
        "sic_desc":"SCHOOLS & EDUCATIONAL SERVICES"},
      {"sic":"8322",
        "sic_desc":"INDIVIDUAL AND FAMILY SERVICES"},
      {"sic":"8331",
        "sic_desc":"JOB TRAINING & VOC REHAB SERVI"},
      {"sic":"8351",
        "sic_desc":"CHILD DAY CARE SERVICES"},
      {"sic":"8361",
        "sic_desc":"RESIDENTIAL CARE"},
      {"sic":"8399",
        "sic_desc":"SOCIAL SERVICES, NEC"},
      {"sic":"8412",
        "sic_desc":"MUSEUMS AND ART GALLERIES"},
      {"sic":"8422",
        "sic_desc":"BOTANICAL & ZOOLOGICAL GARDENS"},
      {"sic":"8611",
        "sic_desc":"BUSINESS ASSOCIATIONS"},
      {"sic":"8621",
        "sic_desc":"PROFESSIONAL MEMBERSHIP ORGAN"},
      {"sic":"8631",
        "sic_desc":"LABOR UNIONS & LABOR ORGANIZA"},
      {"sic":"8641",
        "sic_desc":"CIVIC, SOCIAL & FRATERNAL ASS."},
      {"sic":"8651",
        "sic_desc":"POLITICAL ORGANIZATIONS"},
      {"sic":"8661",
        "sic_desc":"RELIGIOUS ORGANIZATIONS"},
      {"sic":"8699",
        "sic_desc":"MEMBERSHIP ORGANIZATIONS, NEC"},
      {"sic":"8711",
        "sic_desc":"ENGINEERING SERVICES"},
      {"sic":"8712",
        "sic_desc":"ARCHITECTURAL SERVICES"},
      {"sic":"8713",
        "sic_desc":"SURVEYING SERVICES"},
      {"sic":"8721",
        "sic_desc":"ACC., AUDITING & BOOKKEEPING"},
      {"sic":"8731",
        "sic_desc":"COMMERCIAL PHYSICAL RESEARCH"},
      {"sic":"8732",
        "sic_desc":"COMMERCIAL NONPHYSICAL RESEAR"},
      {"sic":"8733",
        "sic_desc":"NONCOMMERCIAL RESEARCH ORGANI"},
      {"sic":"8734",
        "sic_desc":"COMMERCIAL TESTING LABORATORY"},
      {"sic":"8741",
        "sic_desc":"MANAGEMENT SERVICES"},
      {"sic":"8742",
        "sic_desc":"MANAGEMENT CONSULTING SERVICE"},
      {"sic":"8743",
        "sic_desc":"PUBLIC RELATIONS SERVICES"},
      {"sic":"8744",
        "sic_desc":"FACILITIES SUPPORT SERVICES"},
      {"sic":"8748",
        "sic_desc":"BUSINESS CONSULTING, NEC"},
      {"sic":"8811",
        "sic_desc":"PRIVATE HOUSEHOLDS"},
      {"sic":"8999",
        "sic_desc":"SERVICES, NEC"},
      {"sic":"9111",
        "sic_desc":"EXECUTIVE OFFICES"},
      {"sic":"9121",
        "sic_desc":"LEGISLATIVE BODIES"},
      {"sic":"9131",
        "sic_desc":"EXEC & LEGIS OFFICES COMBINED"},
      {"sic":"9199",
        "sic_desc":"GENERAL GOVERNMENT, NEC"},
      {"sic":"9211",
        "sic_desc":"COURTS"},
      {"sic":"9221",
        "sic_desc":"POLICE PROTECTION"},
      {"sic":"9222",
        "sic_desc":"LEGAL COUNSEL & PROSECUTION"},
      {"sic":"9223",
        "sic_desc":"CORRECTIONAL INSTITUTIONS"},
      {"sic":"9224",
        "sic_desc":"FIRE PROTECTION"},
      {"sic":"9229",
        "sic_desc":"PUBLIC ORDER AND SAFETY, NEC"},
      {"sic":"9311",
        "sic_desc":"PUBLIC FINANCE"},
      {"sic":"9411",
        "sic_desc":"ADMINISTRATION OF EDUCAT PROG"},
      {"sic":"9431",
        "sic_desc":"ADMIN OF PUB HEALTH PROGRAMS"},
      {"sic":"9441",
        "sic_desc":"ADM OF SOCIAL/HUMAN RESOURCE"},
      {"sic":"9451",
        "sic_desc":"ADM OF VET AFFAIRS, EX HEA/INS"},
      {"sic":"9511",
        "sic_desc":"AIR & WATER RES & SOL WSTE MGT"},
      {"sic":"9512",
        "sic_desc":"LAND, MIN, WILDLIFE/FOREST CON"},
      {"sic":"9531",
        "sic_desc":"ADMIN OF HOUSING PROGRAMS"},
      {"sic":"9532",
        "sic_desc":"ADM OF URB PLAN/COMM/RURL DEV"},
      {"sic":"9611",
        "sic_desc":"ADMIN OF GENERAL ECONOMIC PRO"},
      {"sic":"9621",
        "sic_desc":"REG & ADMIN OF TRANS PROGRAMS"},
      {"sic":"9631",
        "sic_desc":"REG & ADM OF COMMS, ELEC, GAS"},
      {"sic":"9641",
        "sic_desc":"REG OF AGRI MARKETING & COMMOD"},
      {"sic":"9651",
        "sic_desc":"REG, LIC & INSP OF COMM SECTOR"},
      {"sic":"9661",
        "sic_desc":"SPACE RESEARCH AND TECHNOLOGY"},
      {"sic":"9711",
        "sic_desc":"NATIONAL SECURITY"},
      {"sic":"9721",
        "sic_desc":"INTERNATIONAL SECURITY"},
      {"sic":"9999",
        "sic_desc":"NONCLASSIFIABLE ESTABLISHMENTS"},
      {"sic":"2819PHOS",
        "sic_desc":"INDUSTRIAL INORGANIC CHEMICALS (PHOSPHATE MANUFACTURING)"},
      {"sic":"2874FER",
        "sic_desc":"PHOSPHATIC FERTILIZERS (FERTILIZER MANUFACTURING)"},
      {"sic":"2611-1",
        "sic_desc":"PULP MILLS- Phase I"},
      {"sic":"2611-2",
        "sic_desc":"PULP MILLS- Phase II"},
      {"sic":"2611-3",
        "sic_desc":"PULP MILLS- Phase III"},
      {"sic":"2621-1",
        "sic_desc":"PAPER MILLS- Phase I"},
      {"sic":"2621-2",
        "sic_desc":"PAPER MILLS- Phase II"},
      {"sic":"2621-3",
        "sic_desc":"PAPER MILLS- Phase III"},
      {"sic":"2631-1",
        "sic_desc":"PAPERBOARD MILLS- Phase I"},
      {"sic":"2631-2",
        "sic_desc":"PAPERBOARD MILLS- Phase II"},
      {"sic":"2631-3",
        "sic_desc":"PAPERBOARD MILLS- Phase III"},
      {"sic":"2048GRAIN",
        "sic_desc":"PREP FEEDS & INGRED FOR ANIMA (GRAIN MILLS)"},
      {"sic":"2819NMM",
        "sic_desc":"INDUSTRIAL INORGANIC CHEMICALS (NONFERROUS METALS MANUFACTURING)"},
      {"sic":"CWT",
        "sic_desc":"CENTRALIZED WASTE TREATERS"},
      {"sic":"MPM",
        "sic_desc":"METAL PRODUCTS AND MACHINERY"},
      {"sic":"2048Ph",
        "sic_desc":"PREP FEEDS & INGRED FOR ANIMA (PHARMACEUTICALS)"},
      {"sic":"2823P",
        "sic_desc":"CELLULOSIC MAN-MADE FIBERS (PESTICIDES)"},
      {"sic":"2844P",
        "sic_desc":"PERFUMES,COSMETICS,TOILET PREP (PESTICIDES)"},
      {"sic":"2821P",
        "sic_desc":"PLSTC MAT./SYN RESINS/NV ELAST (PESTICIDES)"},
      {"sic":"2842P",
        "sic_desc":"SPECIALTY CLEANING, POLISHING (PESTICIDES)"},
      {"sic":"2824P",
        "sic_desc":"SYN ORG FIBERS,EXCEPT CELLULOS (PESTICIDES)"},
      {"sic":"2865P",
        "sic_desc":"CYCLIC CRUDES INTERM., DYES (PESTICIDES)"},
      {"sic":"2899P",
        "sic_desc":"CHEMICALS & CHEM PREP, NEC (PESTICIDES)"},
      {"sic":"2891P",
        "sic_desc":"ADHESIVES AND SEALANTS (PESTICIDES)"},
      {"sic":"2869P",
        "sic_desc":"INDUST. ORGANIC CHEMICALS NEC (PESTICIDES)"},
      {"sic":"5169P",
        "sic_desc":"CHEMICALS AND ALLIED PRODUCTS (PESTICIDES)"},
      {"sic":"2834P",
        "sic_desc":"PHARMACEUTICAL PREPARATIONS (PESTICIDES)"},
      {"sic":"VCCAP",
        "sic_desc":"CHLORINE AND CHLORINATED HYDROCARBONS (PESTICIDES)"},
      {"sic":"2048MPP",
        "sic_desc":"PREP FEEDS & INGRED FOR ANIMA (MEAT AND POULTRY)"},
      {"sic":"VCCA",
        "sic_desc":"CHLORINE AND CHLORINATED HYDROCARBONS"},
      {"sic":"2411-1",
        "sic_desc":"LOGGING CAMPS/LOGGING CONTRACT (PULP AND PAPER PHASE I)"},
      {"sic":"2892OCPSF",
        "sic_desc":"EXPLOSIVES (OCPSF)"},
      {"sic":"4953-1",
        "sic_desc":"REFUSE SYSTEMS"},
      {"sic":"4953WC",
        "sic_desc":"REFUSE SYSTEMS (WASTE COMBUSTORS)"},
      {"sic":"4953-2",
        "sic_desc":"REFUSE SYSTEMS"},
      {"sic":"4953L",
        "sic_desc":"REFUSE SYSTEMS (LANDFILLS)"},
      {"sic":"SUPER",
        "sic_desc":"SUPERFUND SITE"},
      {"sic":"3624CB",
        "sic_desc":"CARBON AND GRAPHITE PRODUCTS (CARBON BLACK)"},
      {"sic":"3341CC",
        "sic_desc":"2NDARY SMELT/NONFERROUS METALS (COIL COATING)"},
      {"sic":"3471CC",
        "sic_desc":"PLATING AND POLISHING (COIL COATING)"},
      {"sic":"3431PE",
        "sic_desc":"METAL SANITARY WARE (PORCELAIN ENAMELING)"},
      {"sic":"3469PE",
        "sic_desc":"METAL STAMPINGS, NEC (PORCELAIN ENAMELING)"},
      {"sic":"3633PE",
        "sic_desc":"HOUSEHOLD LAUNDRY EQUIPMENT (PORCELAIN ENAMELING)"},
      {"sic":"3639PE",
        "sic_desc":"HOUSEHOLD APPLIANCES, NEC (PORCELAIN ENAMELING)"},
      {"sic":"2016",
        "sic_desc":"POULTRY DRESSING PLANTS"},
      {"sic":"2080",
        "sic_desc":"BEVERAGES"},
      {"sic":"2440",
        "sic_desc":"WOOD CONTAINERS"},
      {"sic":"3332",
        "sic_desc":"PRIMARY LEAD"},
      {"sic":"3360",
        "sic_desc":"NONFERROUS FOUNDRIES (CASTINGS)"},
      {"sic":"3362",
        "sic_desc":"NONFERROUS FOUNDRIES (BRASS, BRONZE)"},
      {"sic":"3622",
        "sic_desc":"INDUSTRIAL CONTROLS"},
      {"sic":"3670",
        "sic_desc":"ELECTRONIC COMPONENTS & ACCESSORIES"}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "SicCode" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "SicCode"
  }, null, {})
};
