module.exports = {
  up(queryInterface) {
    let records = [{"name":"Anoxic/anaerobic fixed film biological treatment",
      "code":"AAFF",
      "category":"Biological",
      "variations":null,
      "description":"Biological treatment in which microorganisms attach to inert media and break down organic materials in the absence of oxygen. A clarifier is included."},
      {"name":"Alkaline Chlorination",
        "code":"AC",
        "category":"Chemical",
        "variations":null,
        "description":"Used to destroy cyanides. Most often the process is operated in two stages, with separate tanks for each stage. Destruction of dilute solutions of cyanide by chlorination can be accomplished by direct addition of sodium hypochlorite (NaOCl), or by addition of chlorine gas plus sodium hydroxide (NaOH) to the wastewater."},
      {"name":"Aerobic Digestion",
        "code":"AD",
        "category":"Biological",
        "variations":"Aerated biological removal, digestion",
        "description":"Biodegradable organic compounds in wastewater are consumed by microorganisms. This process is aerated."},
      {"name":"Adsorptive Media",
        "code":"ADSM",
        "category":"Sorption",
        "variations":null,
        "description":"Removal of pollutants via surface adhesion to media, not elsewhere classified (e.g., new materials)."},
      {"name":"Aerobic Fixed Film Biological Treatment",
        "code":"AFF",
        "category":"Biological",
        "variations":"Attached growth, fixed bed reactor, rotating biological contactor, trickling filter, fluidized bed reactor",
        "description":"Biological treatment process that uses a medium such as rock, plastic, wood, or other natural or synthetic solid material that will support biomass on its surface and within its porous structure.  Microorganisms attach to inert media and break down organic materials in the presence of oxygen. This process is aerated and includes a clarifier."},
      {"name":"Aeration",
        "code":"AIR",
        "category":"Physical, NEC",
        "variations":"Aeration channel, aerobic polishing cell",
        "description":"Providing contact with air or pure oxygen to increase dissolved oxygen (DO) in wastewater."},
      {"name":"Hydrolysis, Alkaline or Acid",
        "code":"AKH",
        "category":"Chemical",
        "variations":null,
        "description":"Addition of an acid or base (e.g., sodium or potassium hydroxide) to enhance biodegradability of organic substances. Used as a pre-treatment step before biological treatment and to reduce the toxicity of pesticides."},
      {"name":"Anaerobic Digestion",
        "code":"AND",
        "category":"Biological",
        "variations":"non-aerated, anoxic",
        "description":"Biological treatment in which microorganisms break down biodegradable material in the absence of oxygen (i.e., non-aerated). A clarifier is included."},
      {"name":"Anaerobic Fixed Film Biological Treatment",
        "code":"ANFF",
        "category":"Biological",
        "variations":"attached growth, fixed bed reactor, fluidized bed reactor",
        "description":"Biological treatment process that uses a medium such as rock, plastic, wood, or other natural or synthetic solid material that will support biomass on its surface and within its porous structure.  Microorganisms attach to inert media and break down organic materials in the absence of oxygen. A clarifier is included."},
      {"name":"Anaerobic Membrane Bioreactor",
        "code":"AnMBR",
        "category":"Biological",
        "variations":null,
        "description":"Combination of suspended growth biological treatment under low or zero dissolved oxygen conditions and ultrafiltration within one treatment unit/reactor. A clarifier is included."},
      {"name":"Anaerobic Suspended Growth",
        "code":"ANSG",
        "category":"Biological",
        "variations":"anaerobic lagoon",
        "description":"Biodegradable organic compounds in wastewater are consumed by microorganisms in the absence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water. A clarifier is included."},
      {"name":"Antibiofouling",
        "code":"ANTIBIO",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Antibiofouling step to prevent the accumulation of microorganisms on the surfaces of wastewater treatment structures."},
      {"name":"Advanced Oxidation Processes, NEC",
        "code":"AOP",
        "category":"Chemical",
        "variations":"Supercritical Water Oxidation, Catalytic Oxidation, Photo Catalysis (UV + TiO2), Fenton's Reagent",
        "description":"Technologies that use the hydroxyl radical (-OH) for oxidation, not elsewhere classified (NEC)."},
      {"name":"Aerobic Suspended Growth",
        "code":"ASG",
        "category":"Biological",
        "variations":"activated sludge, aerobic lagoon",
        "description":"Biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water. This process is aerated and includes a clarifier."},
      {"name":"Ammonia stripping",
        "code":"AST",
        "category":"Physical, NEC",
        "variations":null,
        "description":"The removal of ammonia with equilibrium vapor pressure at ambient temperatures."},
      {"name":"Bioaugmentation",
        "code":"AUG",
        "category":"Biological",
        "variations":null,
        "description":"Addition of specialized microbial strains in a bioreactor to enhance the ability of the microbial community to respond to operational conditions and/or degrade compounds."},
      {"name":"Biological Activated Filters",
        "code":"BAC",
        "category":"Biological",
        "variations":"Granular media that support microbial growth, submerged aerated filter",
        "description":"Biological filters remove contaminants by three main mechanisms: biodegradation, adsorption of micropollutants, and filtration of suspended solids. The microbial growth attached to the filter media (biofilm) consumes the organic matter."},
      {"name":"Biofilm Airlift Suspension Reactor",
        "code":"BASR",
        "category":"Biological",
        "variations":"airlift bioreactor",
        "description":"Pneumatic device with defined channels for fluid flow. Air pumped into the unit forces the fluid to flow through channels (internal or external loops). Usually will contain gas, solid and liquid phase."},
      {"name":"Bag & Cartridge Filtration",
        "code":"BCF",
        "category":"Filtration",
        "variations":null,
        "description":"Used to remove suspended solids, typically in systems with lower flow rates. Filter media are shaped as bags or cylindrical cartridges."},
      {"name":"Ballasted Clarification",
        "code":"BCLAR",
        "category":"Physical, NEC",
        "variations":"BioMag, CoMag, enhanced settling, high rate settling, Actiflo",
        "description":"Removal of solids deposited by sedimentation, with improved gravitational settling rates by the addition of a weighing agent to the clarifier, typically magnetite or sand."},
      {"name":"Biological Treatment",
        "code":"BIO",
        "category":"Biological",
        "variations":null,
        "description":"Biodegradable organic compounds in wastewater are consumed by microorganisms."},
      {"name":"Best Management Practices",
        "code":"BMP",
        "category":"--",
        "variations":null,
        "description":"Best management practices include treatment requirements, operating procedures, and practices to control plant site runoff, spillage or leaks, sludge or waste disposal, or drainage from raw material storage."},
      {"name":"Biological Nutrient Removal",
        "code":"BNR",
        "category":"Biological",
        "variations":"Modified Ludzack-Ettinger (MLE) Process",
        "description":"Biological treatment that can include nitrification, denitrification and/or phosphorus removal and incorporate anaerobic, anoxic, and aerated zones into the process configurations."},
      {"name":"Chemical Disinfection",
        "code":"CD",
        "category":"Chemical",
        "variations":"Hydroxyl Radical, Oxygen, Ozone, Hydrogen Peroxide, Chlorine species, Halogens",
        "description":"Use of chemicals to disinfect (destroy pathogens in) wastewater."},
      {"name":"Cloth Filtration",
        "code":"CF",
        "category":"Filtration",
        "variations":"cloth media (disc) filter",
        "description":"Water is passed through a cloth medium to remove solids. Cloth is often shaped into discs."},
      {"name":"Controlled Hydrodynamic Cavitation",
        "code":"CHC",
        "category":"Physical, NEC",
        "variations":"mechanical energy device",
        "description":"Device that uses mechanical energy to prevent biofouling, scale and corrosion. The high temperatures and physical forces generated promote chemical reactions, oxidize organic compounds and kill pathogens. Cavitation is the formation and implosion of cavities (bubbles) in a liquid."},
      {"name":"Chemical Precipitation",
        "code":"ChemPre",
        "category":"Chemical",
        "variations":null,
        "description":"Process to remove suspended solids from water. This term is also used for the addition of lime, alum, ferric sulfite, or other precipitants to remove soluble metals from solution by forming insoluble compounds. A chemical precipitation system is typically a mix tank where chemical addition occurs followed by a clarifier or other settling unit."},
      {"name":"Clarification",
        "code":"CLAR",
        "category":"Physical, NEC",
        "variations":"Settling, sedimentation",
        "description":"Removal of solids deposited by sedimentation, without the aid of flocculants."},
      {"name":"Cyanide Destruction",
        "code":"CND",
        "category":"Chemical",
        "variations":null,
        "description":"Conversion of cyanide into a less toxic compound through an oxidation reaction."},
      {"name":"Chemical Nitrogen Removal",
        "code":"CNR",
        "category":"Chemical",
        "variations":null,
        "description":"Redox reaction to remove nitrogen from water or convert between different forms of nitrogen."},
      {"name":"Chemical Oxidation",
        "code":"CO",
        "category":"Chemical",
        "variations":"hydrogen peroxide, permanganate, chlorine, bleach",
        "description":"Addition of chemicals (in any phase) to oxidize organic compounds. Ozonation is identified separately."},
      {"name":"Coagulation/Flocculation",
        "code":"COAGFL",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Removal of solids deposited by sedimentation in a non-reactive system where physical \"clumping\" of solids occurs with the addition of polymer or a flocculant."},
      {"name":"Chemical Phosphorous Removal",
        "code":"CPR",
        "category":"Chemical",
        "variations":null,
        "description":"Addition of metal-salts, most commonly alum, to precipitate phosphorus species out of solution."},
      {"name":"Centrifugal Separators",
        "code":"CS",
        "category":"Physical, NEC",
        "variations":"(liquid) hydrocyclone",
        "description":"Mechanical separation of liquids or particles of different densities. Used to separate oil from water and separate light from dense solids."},
      {"name":"Crystallization",
        "code":"CYS",
        "category":"Physical, NEC",
        "variations":"Fluidized bed crystallization",
        "description":"Crystallization describes the formation of solid crystals precipitating from a solution. It can be applied post-evaporation to create a solid waste product or to recover a product in the wastewater. When used for product recovery, crystallization combines four treatment steps - coagulation, flocculation, sludge/water separation, and dewatering. High-purity, reusable water is also produced."},
      {"name":"Dissolved Air Flotation",
        "code":"DAF",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Air is dissolved under pressure and then released at atmospheric pressure in a tank. The released air creates bubbles which adhere to suspended solids, causing the solids to float to the surface where they can be removed by skimming. Removes suspended solids, oil and grease."},
      {"name":"Dechlorination",
        "code":"DCL",
        "category":"Chemical",
        "variations":null,
        "description":"The process of removing residual chlorine from disinfected wastewater prior to discharge into the environment. Sulfur dioxide is most commonly used. Not to be confused with degradation of chlorinated organics."},
      {"name":"Capacitive Deionization",
        "code":"DEI",
        "category":"Physical, NEC",
        "variations":"electro-sorption",
        "description":"Removal of dissolved ions through an electrochemical mechanism."},
      {"name":"Denitrification",
        "code":"DENIT",
        "category":"Biological",
        "variations":null,
        "description":"Process by which nitrates are reduced to gaseous nitrogen by facultative anaerobes."},
      {"name":"Dissolved Gas Flotation",
        "code":"DGF",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Natural gas, nitrogen, or other gas is dissolved under pressure and then released at atmospheric pressure in a tank. The released air creates bubbles which adhere to suspended solids, causing the solids to float to the surface where they can be removed by skimming. Removes suspended solids, oil and grease."},
      {"name":"Degasification",
        "code":"DGS",
        "category":"Physical, NEC",
        "variations":"membrane degasification, forced draft degasification",
        "description":"Removal of dissolved gases from water by pressure reduction, membrane degasification, or an unspecified method. This includes heating to remove a gas."},
      {"name":"Dry Operation",
        "code":"DRY",
        "category":null,
        "variations":null,
        "description":"Dry operation that results in no wastestream generation."},
      {"name":"Distillation",
        "code":"DST",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Wastewater is heated to form steam, leaving inorganic compounds and large, non-volatile organic molecules behind. The steam is then condensed, forming purified water. Distillation requires input of energy and collection of the purified water."},
      {"name":"Enhanced Biological Phosphorus Removal",
        "code":"EBPR",
        "category":"Biological",
        "variations":"Enhanced biological phosphorus uptake",
        "description":"Use of phosphate-accumulating organisms to store phosphate within the cell. Phosphate is removed in the waste sludge."},
      {"name":"Electrocoagulation",
        "code":"EC",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Wastewater passes across metal electrodes to remove colloids, heavy metals, and emulsified oils. The direct current solubilizes metal ions and destabilizes charged particles, promoting coagulation and flocculation."},
      {"name":"Electrodialysis",
        "code":"ED",
        "category":"Membrane",
        "variations":"Electrodialysis Reversal (EDR)",
        "description":"Ion exchange membranes that use electrical current to separate dissolved contaminants from the wastewater. Ions move in a potential ?eld across alternating polymeric anion and cation-exchange membranes. A potential difference applied across the membranes traps ions and separates a brine waste stream from purified water. Electrodialysis works best for removing low molecular weight charged species."},
      {"name":"Chemical Emulsion Treatment",
        "code":"EMUL",
        "category":"Chemical",
        "variations":"Chemical emulsion breaking",
        "description":"Removal of emulsion via chemical means."},
      {"name":"Flow Equalization",
        "code":"EQ",
        "category":"Physical, NEC",
        "variations":"buffer tank, flow control, flow balance",
        "description":"Basin, lagoon, tank or reactor that serves to control a variable flow of wastewater to achieve a near constant flow into the treatment system or between units."},
      {"name":"Evaporation",
        "code":"EVAP",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Water is vaporized and sometimes condensed for reuse. The remaining product is concentrated brine containing the dissolved solids from the original wastewater. The process may be carried out naturally in solar (shallow) evaporation ponds or through the use of commercially available evaporation equipment."},
      {"name":"Facultative Lagoon",
        "code":"FAC",
        "category":"Biological",
        "variations":null,
        "description":"Biological treatment where the layer of water near the surface contains dissolved oxygen due to atmospheric reaeration and algal respiration, a condition that supports aerobic and facultative organisms. The bottom layer of the lagoon includes sludge deposits and supports anaerobic organisms. The intermediate anoxic layer, termed the facultative zone, ranges from aerobic near the top to anaerobic at the bottom. A clarifier is included."},
      {"name":"Denitrification Filter",
        "code":"FDN",
        "category":"Biological",
        "variations":null,
        "description":"Granular-media filtration bed that supports growth of denitrifying bacteria, reduces nitrate to nitrogen gas, and removes suspended solids."},
      {"name":"Granular-Media Filtration",
        "code":"FI",
        "category":"Filtration",
        "variations":"Conventional, Multi-media, or Sand Filtration",
        "description":"Removal of suspended solids accomplished by passing wastewater through a filter bed of granular media. Media may include sand, walnut shells and steel slag."},
      {"name":"Other Filtration",
        "code":"FILT",
        "category":"Filtration",
        "variations":null,
        "description":"Filtration (excluding membranes) that is not bag & cartridge, cloth filtration, or granular-media filtration. Filtration removes suspended solids by mechanical straining (i.e., trapping them between grains of the filter medium)."},
      {"name":"Flotation",
        "code":"FLOAT",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Flotation is the use of air bubbles to remove light suspended solids and oils from wastewater. Pollutants adhere to the air bubbles, causing them to float to the surface where they can be removed by skimming. Flotation that may consist of induced air flotation or vacuum flotation."},
      {"name":"Forward Osmosis",
        "code":"FO",
        "category":"Membrane",
        "variations":"engineered or manipulated osmosis",
        "description":"Wastewater passes through a selectively permeable membrane driven by the osmotic pressure difference across the membrane. Wastewater is drawn across a membrane to a solution with a higher concentration (relative to the wastewater). The resulting separated water must then be further treated to produce a high-quality effluent."},
      {"name":"Granular Activated Carbon",
        "code":"GAC",
        "category":"Sorption",
        "variations":null,
        "description":"Uses the physical/chemical adsorption process to remove soluble contaminants from wastewater. The adsorptive media is activated carbon."},
      {"name":"Gasification",
        "code":"GAS",
        "category":"Chemical",
        "variations":"downdraft, updraft or fluidized bed gasifier",
        "description":"Thermo-chemical process to convert carbon-containing biosolids into gas (carbon dioxide and methane) and energy. Resulting energy can be used for heating. Gases are used to generate fuels, electricity and heat. Gasification also reduces the volume of solids for disposal."},
      {"name":"Gravity Separation",
        "code":"GravS",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Removal of solids by gravity settling  without chemical addition that is not described as clarification or surface impoundment."},
      {"name":"Granular Sludge Sequencing Batch Reactor",
        "code":"GSBR",
        "category":"Biological",
        "variations":null,
        "description":"Aerobic biological treatment with enhanced sludge settling by formation of granular sludge, without the use of carrier materials. Granular sludge developed by selection of biomass with short settling times."},
      {"name":"Integrated Fixed Film Activated Sludge",
        "code":"IFAS",
        "category":"Biological",
        "variations":"addition of carrier media to activated sludge",
        "description":"Carrier media added to an activated sludge system (i.e., biodegradable organic compounds in wastewater are consumed by microorganisms) to increase loadings without increasing the plant footprint. Often used for retrofits."},
      {"name":"Ion Exchange",
        "code":"ION",
        "category":"Chemical, Sorption",
        "variations":"softening, deionization",
        "description":"Physical-chemical process in which ions are swapped between a solution phase and a solid resin phase. Different resins are used to target different charged particles. Commonly used for softening (removing dissolved calcium and magnesium) and nitrate removal."},
      {"name":"Liquid Extraction",
        "code":"LE",
        "category":"Chemical",
        "variations":"(flotation) liquid-liquid extraction, solvent extraction",
        "description":"Separation of chemicals based on different solubilities in two solutes. Allows recovery of the chemical from wastewater."},
      {"name":"Moving Bed Bioreactor",
        "code":"MBBR",
        "category":"Biological",
        "variations":null,
        "description":"A hybrid suspended growth-fixed film system. \"Biocarrier\" media are provided in the unit for the microorganisms to grow on. Increases the effective surface area for reaction while reducing the footprint of the system."},
      {"name":"Membrane Bioreactor",
        "code":"MBR",
        "category":"Biological",
        "variations":null,
        "description":"Combination of aerobic suspended growth biological treatment with ultrafiltration within one treatment unit/reactor. Ultrafiltration replaces the use of secondary clarifiers (solids separation) in conventional wastewater treatment plants. Can be used to reduce BOD, TSS, nitrogen and phosphorus."},
      {"name":"Membrane Distillation",
        "code":"MD",
        "category":"Membrane",
        "variations":null,
        "description":"Thermal-driven separation process where only vapor molecules pass through a microporous hydrophobic membrane. The driving force is the vapor pressure difference induced by the temperature difference across the membrane."},
      {"name":"Membrane Filtration",
        "code":"MF",
        "category":"Membrane",
        "variations":"Includes microfiltration, ultrafiltration and other engineered materials",
        "description":"Includes microfiltration, ultrafiltration and other engineered materials. Includes filtration methods that remove particles as small as 100 nanometers (nm) (microfiltration) and 10 nm (ultrafiltration). Many molecules are within this size range."},
      {"name":"Mechanical Pre-Treatment",
        "code":"MPT",
        "category":"Physical, NEC",
        "variations":"screen, bar, rack, grit chamber, comminuter, grinder, preliminary treatment",
        "description":"Physical removal of debris and coarse solids. This is often a first step in wastewater treatment, which serves to protect downstream treatment equipment."},
      {"name":"Nanofiltration",
        "code":"NANO",
        "category":"Membrane",
        "variations":null,
        "description":"A membrane filtration method used to remove particles as small as 1 nanometer (nm) from wastewater. This includes divalent and large monovalent ions (e.g., heavy metals). Used for desalination and softening."},
      {"name":"Nitrification",
        "code":"NIT",
        "category":"Biological",
        "variations":null,
        "description":"Biological oxidation of ammonia or ammonium to nitrite followed by the oxidation of the nitrite to nitrate."},
      {"name":"Other Gas Stripping",
        "code":"OST",
        "category":"Physical, NEC",
        "variations":null,
        "description":"The removal of gases with equilibrium vapor pressures at ambient temperatures, including volatile organic compounds (VOCs)."},
      {"name":"Oil/Water Separation",
        "code":"OW",
        "category":"Physical, NEC",
        "variations":"API Separators",
        "description":"Removal of gross quantities of oil and suspended solids by skimming and collecting oil from the surface of the wastewater. Includes API separators."},
      {"name":"Oil/Water Separation",
        "code":"OWS",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Removal of oil and suspended solids by a process not classified as an API separator, as skimming, or as a centrifugal separator."},
      {"name":"Ozonation",
        "code":"OZ",
        "category":"Chemical",
        "variations":null,
        "description":"Ozone is a highly unstable gas used to either oxidize organic substances or disinfect wastewater. It must be produced onsite for immediate use in a contact chamber."},
      {"name":"Powdered Activated Carbon",
        "code":"PAC",
        "category":"Sorption",
        "variations":null,
        "description":"Uses the physical/chemical adsorption process to remove soluble contaminants from wastewater for particles less than or equal to 1.0 millimeters (mm) in diameter."},
      {"name":"Chemical Reduction",
        "code":"REDX",
        "category":"Chemical",
        "variations":"hexavalent chromium reduction",
        "description":"Reaction where the chemical gains electrons, accompanied by a decrease in oxidation state."},
      {"name":"Recycle/reuse",
        "code":"REUSE",
        "category":"--",
        "variations":null,
        "description":"Recycle/reuse of wastewater or a portion of the wastewater stream."},
      {"name":"Reverse Osmosis",
        "code":"RO",
        "category":"Membrane",
        "variations":"Desalination",
        "description":"A membrane filtration method used to remove small ions (e.g., Na+) from wastewater that uses pressure as the driving separation force."},
      {"name":"Sequencing Batch Reactor",
        "code":"SBR",
        "category":"Biological",
        "variations":null,
        "description":"Aerobic biological treatment with enhanced sludge settling without the use of carrier materials. Steps include fill, react, settle, decant, and idle."},
      {"name":"Surface Impoundment",
        "code":"SI",
        "category":"Physical, NEC",
        "variations":"Pond",
        "description":"Natural or man-made topographic depression, primarily made of earthen material, used to volatilize and/or settle materials."},
      {"name":"Sorption, NEC",
        "code":"SORP",
        "category":"Sorption",
        "variations":null,
        "description":"Physical/chemical process where pollutants attach to the sorption media, not elsewhere classified (NEC)."},
      {"name":"Stripping",
        "code":"ST",
        "category":"Physical, NEC",
        "variations":"air or gas stripping",
        "description":"The removal of substances with equilibrium vapor pressures at ambient temperatures."},
      {"name":"Thermal treatment",
        "code":"THERMAL",
        "category":"Physical, NEC",
        "variations":null,
        "description":"Process of using high temperatures to treat wastewater. Evaporation, distillation, and volatilization are identified separately."},
      {"name":"Ultrasound",
        "code":"US",
        "category":"Physical, NEC",
        "variations":"Sonification",
        "description":"High frequency bandwidth of sound applied to agitate particles in solution and disrupt cell membranes. Used in water storage facilities to suppress algal growth and biofilm formation."},
      {"name":"UV",
        "code":"UV",
        "category":"Chemical",
        "variations":"ultraviolet light or radiation",
        "description":"Ultraviolet radiation penetrates the wastewater to oxidize organics and/or disinfect. Used as a last, polishing step in wastewater treatment. May be used with chemical oxidants such as peroxide and ozone."},
      {"name":"Volatilization",
        "code":"VOL",
        "category":"Physical, NEC",
        "variations":null,
        "description":"The removal of substances with equilibrium vapor pressures at ambient temperatures through volatilization."},
      {"name":"Wet Air Oxidation",
        "code":"WAO",
        "category":"Chemical",
        "variations":null,
        "description":"The oxidation of soluble or suspended components in water using oxygen as the oxidizing agent. Air is used as the source of oxygen."},
      {"name":"Constructed Wetlands",
        "code":"WET",
        "category":"Biological",
        "variations":"Reed bed, artificial wetland, peat land",
        "description":"Application of natural processes and use of vegetation to remove BOD, nutrients, and suspended solids. \"Green\" technology that can minimize energy use for water treatment."},
      {"name":"Zero Liquid Discharge",
        "code":"ZLD",
        "category":"--",
        "variations":null,
        "description":"Zero liquid discharge (no technology specified)."},
      {"name":"Zero Valent Iron",
        "code":"ZVI",
        "category":"Chemical, Sorption",
        "variations":"nZVI",
        "description":"Granular or nanoscale ZVI is used to remove metals by adsorption and reductive precipitation mechanisms. Used through a separate reactor unit. Similar configuration to granular-media filtration."},
      {"name":"Other Wastewater Treatment",
        "code":"OTHER",
        "category":"--",
        "variations":null,
        "description":"Wastewater treatment technology that is either not captured by other technology codes or is unspecified."},
      {"name":"Hauling Solid Waste",
        "code":"HAUL",
        "category":"--",
        "variations":null,
        "description":"Hauling of solid waste generated from wastewater treatment."}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "TreatmentTechnologyCode" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "TreatmentTechnologyCode"
  }, null, {})
};
