module.exports = {
  up(queryInterface) {
    let records = [{"treatment_id":5,"treatment_description":"A surface impoundment is a natural or man-made topographic depression, primarily made of earthen material, used to volatilize and/or settle materials.","treatment_codes":"SI"},
      {"treatment_id":6,"treatment_description":"Chemical precipitation is a process that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. This is followed by anaerobic biological treatment in which microorganisms break down organic materials in the absence of oxygen.","treatment_codes":"ChemPre; AND"},
      {"treatment_id":7,"treatment_description":"Chemical precipitation is a process that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. This is followed by evaporation where water is vaporized and sometimes condensed for reuse. The remaining product is concentrated brine containing the dissolved solids from the original wastewater. The process may be carried out naturally in solar (shallow) evaporation ponds or through the use of commercially available evaporation equipment. The brine may be further concentrated during the crystallization process (CYS).","treatment_codes":"ChemPre; EVAP"},
      {"treatment_id":8,"treatment_description":"Aerobic suspended growth is a process where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water. This is followed by clarification that separates suspended particles from water through gravitational settling.","treatment_codes":"ASG; CLAR"},
      {"treatment_id":9,"treatment_description":"Contaminated water is distilled to form steam, leaving inorganic compounds and large, non-volatile organic molecules behind. The steam is then condensed, forming purified water. Then, distillate is treated through aerobic suspended growth, a process where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water.","treatment_codes":"DST; ASG"},
      {"treatment_id":10,"treatment_description":"Granular activated carbon removes soluble contaminants from wastewater through absorption. It is highly effective due to its large surface area and high porosity. Then, filtrate is treated through aerobic suspended growth, a process where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water.","treatment_codes":"GAC; ASG"},
      {"treatment_id":11,"treatment_description":"Powdered activated carbon removes soluble contaminants from wastewater through absorption. It can remove finer particles than GAC (less than or equal to 1.0 mm in diameter). Then, filtrate is treated through aerobic suspended growth, a process where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water.","treatment_codes":"PAC; ASG"},
      {"treatment_id":12,"treatment_description":"Stripping is the removal of substances with equilibrium vapor pressures at ambient temperatures, such as ammonia and many volatile organic compounds (VOCs). This is followed by aerobic suspended growth, a process where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water.","treatment_codes":"ST; ASG"},
      {"treatment_id":13,"treatment_description":"Aerobic suspended growth is a process where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water.","treatment_codes":"ASG"},
      {"treatment_id":14,"treatment_description":"Stripping is the removal of substances with equilibrium vapor pressures at ambient temperatures, such as ammonia and many volatile organic compounds (VOCs).","treatment_codes":"ST"},
      {"treatment_id":15,"treatment_description":"Granular activated carbon removes soluble contaminants from wastewater through absorption. It is highly effective due to its large surface area and high porosity.","treatment_codes":"GAC"},
      {"treatment_id":16,"treatment_description":"Powdered activated carbon removes soluble contaminants from wastewater through absorption. It can remove finer particles than GAC (less than or equal to 1.0 mm in diameter).","treatment_codes":"PAC"},
      {"treatment_id":17,"treatment_description":"Chemical precipitation is a process that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. This term is also used for the addition of lime, alum, ferric sulfite, or other precipitants to remove soluble metals from solution by forming insoluble compounds.","treatment_codes":"ChemPre"},
      {"treatment_id":18,"treatment_description":"Alkaline chlorination is operated in two stages, with separate tanks for each stage. Destruction of dilute cyanide solutions through chlorination can be accomplished by direct addition of sodium hypochlorite (NaOCl), or by addition of chlorine gas plus sodium hydroxide (NaOH) to the wastewater.","treatment_codes":"AC"},
      {"treatment_id":19,"treatment_description":"Stripping is the removal of substances with equilibrium vapor pressures at ambient temperatures, such as ammonia and many volatile organic compounds (VOCs). This is followed by a granular activated carbon unit that removes soluble contaminants from wastewater through absorption. It is highly effective due to its large surface area and high porosity.","treatment_codes":"ST; GAC"},
      {"treatment_id":20,"treatment_description":"Stripping is the removal of substances with equilibrium vapor pressures at ambient temperatures, such as ammonia and many volatile organic compounds (VOCs). This is followed by a powdered activated carbon unit that removes soluble contaminants from wastewater through absorption. It can remove finer particles than GAC (less than or equal to 1.0 mm in diameter).","treatment_codes":"ST; PAC"},
      {"treatment_id":21,"treatment_description":"Oil/water separation is the removal of gross quantities of oil and suspended solids by skimming and collecting oil from the surface of the wastewater. This is followed by chemical precipitation that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. Finally, clarification separates suspended particles from water by gravitational settling.","treatment_codes":"OW; ChemPre; CLAR"},
      {"treatment_id":22,"treatment_description":"Aeration is a process where wastewater is contacted by air or pure oxygen to increase dissolved oxygen (DO). This is followed by chemical precipitation that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. Finally, clarification separates suspended particles from water by gravitational settling.","treatment_codes":"AIR; ChemPre; CLAR"},
      {"treatment_id":23,"treatment_description":"Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. Then, clarification separates suspended particles from water by gravitational settling.","treatment_codes":"ChemPre; CLAR"},
      {"treatment_id":24,"treatment_description":"Clarification is the separation of suspended particles from water by gravitational settling. This is followed by aeration where wastewater is contacted by air or pure oxygen to increase dissolved oxygen (DO). This is followed by further clarification and chemical disinfection, where chemicals are used to disinfect (destroy pathogens in) wastewater.","treatment_codes":"CLAR; AIR; CLAR; CD"},
      {"treatment_id":25,"treatment_description":"The process of removing residual chlorine from disinfected wastewater prior to discharge into the environment.","treatment_codes":"DCL"},
      {"treatment_id":26,"treatment_description":"A multi-unit process that produces solid, but not liquid waste. The main technologies enabling zero liquid discharge are evaporation (EVAP) and crystallization (CYS). The facility can also choose to reuse all wastewater after a certain amount of treatment. The decision to fully reuse wastewater is not considered a treatment technology.","treatment_codes":"ZLD"},
      {"treatment_id":27,"treatment_description":"Water is vaporized and sometimes condensed for reuse. The remaining product is concentrated brine containing the dissolved solids from the original wastewater. The process may be carried out naturally in solar (shallow) evaporation ponds or through the use of commercially available evaporation equipment.","treatment_codes":"EVAP"},
      {"treatment_id":28,"treatment_description":"Other technology basis besides wastewater treatment","treatment_codes":"OTHER"},
      {"treatment_id":29,"treatment_description":"A surface impoundment is a natural or man-made topographic depression, primarily made of earthen material, used to volatilize and/or settle materials. This is followed by best management practices, which may consist of treatment requirements, operating procedures, and practices to control plant site runoff, spillage or leaks, sludge or waste disposal, or drainage from raw material storage.","treatment_codes":"SI; BMP"},
      {"treatment_id":30,"treatment_description":"A surface impoundment is a natural or man-made topographic depression, primarily made of earthen material, used to volatilize and/or settle materials. This is followed by best management practices, which may consist of treatment requirements, operating procedures, and practices to control plant site runoff, spillage or leaks, sludge or waste disposal, or drainage from raw material storage. Finally, an unspecified technology basis treats or prevents discharge of wastewater pollutants.","treatment_codes":"SI; BMP; UNSPEC"},
      {"treatment_id":31,"treatment_description":"A best management practice consists of treatment requirements, operating procedures, and practices to control plant site runoff, spillage or leaks, sludge or waste disposal, or drainage from raw material storage.","treatment_codes":"BMP"},
      {"treatment_id":32,"treatment_description":"See Technology Basis Notes","treatment_codes":"See Note"},
      {"treatment_id":33,"treatment_description":"Chemical precipitation is a process that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. This is followed by anoxic/anaerobic fixed-film biological treatment in which microorganisms attach to inert media and break down organic materials in the absence of oxygen.","treatment_codes":"ChemPre; AAFF"},
      {"treatment_id":34,"treatment_description":"A best management practice consists of treatment requirements, operating procedures, and practices to control plant site runoff, spillage or leaks, sludge or waste disposal, or drainage from raw material storage. This may be followed by dechlorination, which is the process of removing residual chlorine from disinfected wastewater prior to discharge into the environment.","treatment_codes":"BMP; DCL"},
      {"treatment_id":35,"treatment_description":"A best management practice consists of treatment requirements, operating procedures, and practices to control plant site runoff, spillage or leaks, sludge or waste disposal, or drainage from raw material storage. This may be followed by chemical precipitation, which is a process that removes suspended solids from water. Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater.","treatment_codes":"BMP; ChemPre"},
      {"treatment_id":36,"treatment_description":"Oil/water separation is the removal of gross quantities of of oil and suspended solids by skimming and collecting oil from the surface of the wastewater.","treatment_codes":"OW"},
      {"treatment_id":37,"treatment_description":"Biodegradable organic compounds in wastewater are consumed by microorganisms.","treatment_codes":"BIO"},
      {"treatment_id":38,"treatment_description":"Aerobic fixed film biological treatment is an aerated process where microorganisms attach to inert media.","treatment_codes":"AFF"},
      {"treatment_id":39,"treatment_description":"Chemical addition first neutralizes charged particles (coagulation) and promotes particle adhesion to form large, visible clumps (flocculation) that can then settle out of the wastewater. Then, clarification separates suspended particles from water by gravitational settling. Finally, granular-media filtration removes suspended solids by passing wastewater through a filter bed of granular media. Media may include sand, walnut shells and steel slag.","treatment_codes":"ChemPre; CLAR; FI"},
      {"treatment_id":40,"treatment_description":"Oil/water separation is the removal of gross quantities of oil and suspended solids by skimming and collecting oil from the surface of the wastewater. This is followed by dissolved air flotation where air is dissolved under pressure and then released at atmospheric pressure in a tank. The released air creates bubbles which adhere to suspended solids, causing the solids to float to the surface where they can be removed by skimming.","treatment_codes":"OW; DAF"},
      {"treatment_id":41,"treatment_description":"Flow equalization takes place in a basin, lagoon, tank or reactor that serves to control a variable flow of wastewater to achieve a near constant flow into the treatment system or between units. This is followed by aerobic suspended growth where biodegradable organic compounds in wastewater are consumed by microorganisms in the presence of oxygen. The microorganisms are suspended within the wastewater, creating a sludge that is separated from the water.","treatment_codes":"EQ; ASG"},
      {"treatment_id":42,"treatment_description":null,"treatment_codes":"ST; EQ; ASG; CLAR"},
      {"treatment_id":43,"treatment_description":null,"treatment_codes":"OW; EQ; ST; EQ; BIO; CLAR"},
      {"treatment_id":44,"treatment_description":null,"treatment_codes":"ChemPre; OW"},
      {"treatment_id":45,"treatment_description":null,"treatment_codes":"ChemPre; OW; FI"},
      {"treatment_id":46,"treatment_description":null,"treatment_codes":"ChemPre; AC; DCL"},
      {"treatment_id":87,"treatment_description":null,"treatment_codes":"REDX; OW; ChemPre; CLAR"},
      {"treatment_id":88,"treatment_description":null,"treatment_codes":"REDX; EQ; OW; ChemPre"},
      {"treatment_id":89,"treatment_description":null,"treatment_codes":"EQ; OW; EMUL; ChemPre; DAF"},
      {"treatment_id":90,"treatment_description":null,"treatment_codes":"EMUL; EQ; OW; ChemPre"},
      {"treatment_id":91,"treatment_description":null,"treatment_codes":"REDX; ST; EQ; OW; ChemPre"},
      {"treatment_id":92,"treatment_description":null,"treatment_codes":"REDX; EQ; OW; ChemPre; CLAR"},
      {"treatment_id":93,"treatment_description":null,"treatment_codes":"EMUL; EQ; OW; ChemPre; FI"},
      {"treatment_id":94,"treatment_description":null,"treatment_codes":"EQ; OW; ChemPre; FI"},
      {"treatment_id":95,"treatment_description":null,"treatment_codes":"REDX; ST; EQ; OW; ChemPre; FI"},
      {"treatment_id":96,"treatment_description":null,"treatment_codes":"REDX; EQ; OW; ChemPre; FI"},
      {"treatment_id":97,"treatment_description":null,"treatment_codes":"ChemPre; EQ; OW; ChemPre"},
      {"treatment_id":98,"treatment_description":null,"treatment_codes":"ChemPre; EQ; OW; ChemPre; CLAR; FI"},
      {"treatment_id":99,"treatment_description":null,"treatment_codes":"ChemPre; ST; EQ; OW; ChemPre"},
      {"treatment_id":100,"treatment_description":null,"treatment_codes":"BIO; ST"},
      {"treatment_id":101,"treatment_description":null,"treatment_codes":"BIO; CLAR"},
      {"treatment_id":102,"treatment_description":null,"treatment_codes":"BIO; ChemPre"},
      {"treatment_id":103,"treatment_description":null,"treatment_codes":"BIO; GAC"},
      {"treatment_id":104,"treatment_description":null,"treatment_codes":"BIO; ST; GAC"},
      {"treatment_id":105,"treatment_description":null,"treatment_codes":"CLAR; EQ; ZLD"},
      {"treatment_id":106,"treatment_description":null,"treatment_codes":"BMP; OW; ChemPre; CLAR"},
      {"treatment_id":107,"treatment_description":null,"treatment_codes":"BMP; OW; ChemPre; CLAR; FI"},
      {"treatment_id":108,"treatment_description":null,"treatment_codes":"BMP; ChemPre; CLAR"},
      {"treatment_id":109,"treatment_description":null,"treatment_codes":"BMP; ChemPre; CLAR; FI"},
      {"treatment_id":110,"treatment_description":null,"treatment_codes":"BMP; CO; ChemPre; CLAR"},
      {"treatment_id":111,"treatment_description":null,"treatment_codes":"BMP; CO; ChemPre; CLAR; FI"},
      {"treatment_id":112,"treatment_description":null,"treatment_codes":"ChemPre; CLAR; FI; ZLD"},
      {"treatment_id":47,"treatment_description":null,"treatment_codes":"ChemPre; AC; FI; DCL"},
      {"treatment_id":48,"treatment_description":null,"treatment_codes":"ChemPre; ZLD"},
      {"treatment_id":49,"treatment_description":null,"treatment_codes":"ChemPre; FI"},
      {"treatment_id":50,"treatment_description":null,"treatment_codes":"CLAR; ChemPre; CLAR"},
      {"treatment_id":51,"treatment_description":null,"treatment_codes":"FI; ChemPre; CLAR"},
      {"treatment_id":52,"treatment_description":null,"treatment_codes":"DST"},
      {"treatment_id":53,"treatment_description":null,"treatment_codes":"CLAR; OW; CLAR; FI"},
      {"treatment_id":54,"treatment_description":null,"treatment_codes":"CO; ChemPre; CLAR"},
      {"treatment_id":55,"treatment_description":null,"treatment_codes":"EQ; ChemPre; AIR; CLAR"},
      {"treatment_id":56,"treatment_description":null,"treatment_codes":"EQ; OW; ChemPre; AIR; CLAR"},
      {"treatment_id":57,"treatment_description":null,"treatment_codes":"OW; EQ; ChemPre; DAF"},
      {"treatment_id":58,"treatment_description":null,"treatment_codes":"CLAR; OW"},
      {"treatment_id":59,"treatment_description":null,"treatment_codes":"CLAR; OW; ZLD"},
      {"treatment_id":60,"treatment_description":null,"treatment_codes":"EQ; OW; ChemPre"},
      {"treatment_id":61,"treatment_description":null,"treatment_codes":"EQ; ChemPre; OW; CLAR"},
      {"treatment_id":62,"treatment_description":null,"treatment_codes":"CLAR; FI"},
      {"treatment_id":63,"treatment_description":null,"treatment_codes":"OW; FI"},
      {"treatment_id":64,"treatment_description":null,"treatment_codes":"BIO; AFF; ASG"},
      {"treatment_id":65,"treatment_description":null,"treatment_codes":"BIO; AFF; ASG; AC"},
      {"treatment_id":66,"treatment_description":null,"treatment_codes":"BIO; AC"},
      {"treatment_id":67,"treatment_description":null,"treatment_codes":"AIR; CLAR"},
      {"treatment_id":68,"treatment_description":null,"treatment_codes":"CLAR"},
      {"treatment_id":69,"treatment_description":null,"treatment_codes":"OW; EQ; ST"},
      {"treatment_id":70,"treatment_description":null,"treatment_codes":"ChemPre; AC"},
      {"treatment_id":71,"treatment_description":null,"treatment_codes":"OW; EQ; ST; EQ"},
      {"treatment_id":72,"treatment_description":null,"treatment_codes":"ChemPre; AC; DCL; FI"},
      {"treatment_id":73,"treatment_description":null,"treatment_codes":"OW; FI"},
      {"treatment_id":74,"treatment_description":null,"treatment_codes":"OW; FI; ChemPre"},
      {"treatment_id":75,"treatment_description":null,"treatment_codes":"OW; FI; DST; ZLD"},
      {"treatment_id":76,"treatment_description":null,"treatment_codes":"CLAR; OW; ZLD"},
      {"treatment_id":77,"treatment_description":null,"treatment_codes":"EQ; OW; ChemPre; CLAR"},
      {"treatment_id":78,"treatment_description":null,"treatment_codes":"EQ; ChemPre; CLAR"},
      {"treatment_id":79,"treatment_description":null,"treatment_codes":"DGF; CS; FI"},
      {"treatment_id":80,"treatment_description":null,"treatment_codes":"FI; DGF; SI"},
      {"treatment_id":81,"treatment_description":null,"treatment_codes":"CS"},
      {"treatment_id":82,"treatment_description":null,"treatment_codes":"DGF"},
      {"treatment_id":83,"treatment_description":null,"treatment_codes":"FI"},
      {"treatment_id":84,"treatment_description":null,"treatment_codes":"AIR; BCLAR; CD"},
      {"treatment_id":85,"treatment_description":null,"treatment_codes":"MPT"},
      {"treatment_id":86,"treatment_description":null,"treatment_codes":"EQ; OW"},
      {"treatment_id":113,"treatment_description":null,"treatment_codes":"CLAR; ZLD"},
      {"treatment_id":114,"treatment_description":null,"treatment_codes":"CLAR; REUSE; OW; ChemPre"},
      {"treatment_id":115,"treatment_description":null,"treatment_codes":"CLAR; FI; REUSE; OW; ChemPre"},
      {"treatment_id":116,"treatment_description":null,"treatment_codes":"CLAR; REUSE; OW; CO; ChemPre"},
      {"treatment_id":117,"treatment_description":null,"treatment_codes":"CLAR; FI; REUSE; OW; CO; ChemPre"},
      {"treatment_id":118,"treatment_description":null,"treatment_codes":"CLAR; REUSE; CO; OW; ChemPre"},
      {"treatment_id":119,"treatment_description":null,"treatment_codes":"CLAR; FI; REUSE; CO; OW; ChemPre"},
      {"treatment_id":120,"treatment_description":null,"treatment_codes":"CLAR; ZLD"},
      {"treatment_id":121,"treatment_description":null,"treatment_codes":"OW; CO; ChemPre; CLAR; BMP"},
      {"treatment_id":122,"treatment_description":null,"treatment_codes":"EMUL; OW; CO; ChemPre; REUSE"},
      {"treatment_id":123,"treatment_description":null,"treatment_codes":"EMUL; OW; CO; ChemPre; FI; REUSE"},
      {"treatment_id":124,"treatment_description":null,"treatment_codes":"AC; ASG; CLAR"},
      {"treatment_id":125,"treatment_description":null,"treatment_codes":"BIO; ASG; CLAR"},
      {"treatment_id":126,"treatment_description":null,"treatment_codes":"ChemPre; ASG; CLAR"},
      {"treatment_id":127,"treatment_description":null,"treatment_codes":"ST; ASG; CLAR"},
      {"treatment_id":128,"treatment_description":null,"treatment_codes":"ST; GAC; ASG; CLAR"},
      {"treatment_id":129,"treatment_description":null,"treatment_codes":"GAC; ASG; CLAR"},
      {"treatment_id":130,"treatment_description":null,"treatment_codes":"REDX; OW; ChemPre; FI"},
      {"treatment_id":131,"treatment_description":null,"treatment_codes":"REDX; EQ; EMUL; DAF; OW; ChemPre"},
      {"treatment_id":132,"treatment_description":null,"treatment_codes":"BMP; ChemPre; REDX; EQ; ChemPre; FI"},
      {"treatment_id":133,"treatment_description":null,"treatment_codes":"BMP; ChemPre; REDX; EQ; ChemPre"},
      {"treatment_id":134,"treatment_description":null,"treatment_codes":"EQ; ChemPre"},
      {"treatment_id":135,"treatment_description":null,"treatment_codes":"REDX; ChemPre"},
      {"treatment_id":141,"treatment_description":null,"treatment_codes":"EQ; ST; EQ"},
      {"treatment_id":142,"treatment_description":null,"treatment_codes":"EQ; BIO; CLAR"},
      {"treatment_id":143,"treatment_description":null,"treatment_codes":"EMUL; OW; REDX; ChemPre; OW; ChemPre"},
      {"treatment_id":144,"treatment_description":null,"treatment_codes":"ChemPre; OW; ChemPre"},
      {"treatment_id":145,"treatment_description":null,"treatment_codes":"EMUL; OW; REDX; ChemPre; OW; ChemPre FI"},
      {"treatment_id":146,"treatment_description":null,"treatment_codes":"ChemPre; OW; ChemPre; FI"},
      {"treatment_id":147,"treatment_description":null,"treatment_codes":"REDX; ChemPre; OW; ChemPre"},
      {"treatment_id":148,"treatment_description":null,"treatment_codes":"REDX; ChemPre; OW; ChemPre; FI"},
      {"treatment_id":149,"treatment_description":null,"treatment_codes":"CLAR; BIO"},
      {"treatment_id":150,"treatment_description":null,"treatment_codes":"BMP; CLAR; ZLD"},
      {"treatment_id":151,"treatment_description":null,"treatment_codes":"BMP; EVAP; ZLD"},
      {"treatment_id":152,"treatment_description":null,"treatment_codes":"BMP; ZLD"},
      {"treatment_id":153,"treatment_description":null,"treatment_codes":"CLAR; BIO; CLAR"},
      {"treatment_id":154,"treatment_description":null,"treatment_codes":"BMP; OW; BIO; ZLD"},
      {"treatment_id":155,"treatment_description":null,"treatment_codes":"BMP; OW; BIO"},
      {"treatment_id":156,"treatment_description":null,"treatment_codes":"BIO; NIT; CD"},
      {"treatment_id":157,"treatment_description":null,"treatment_codes":"BIO; NIT; DENIT; CD"},
      {"treatment_id":158,"treatment_description":null,"treatment_codes":"MPT; CLAR; BIO"},
      {"treatment_id":159,"treatment_description":null,"treatment_codes":"BMP; OW; BIO; CD"},
      {"treatment_id":160,"treatment_description":null,"treatment_codes":"BMP; OW; BIO; FI"},
      {"treatment_id":161,"treatment_description":null,"treatment_codes":"BMP; DAF; BIO; FI"},
      {"treatment_id":162,"treatment_description":null,"treatment_codes":"BMP; DAF; BIO; NIT; DENIT; FI"},
      {"treatment_id":163,"treatment_description":null,"treatment_codes":"MPT; OW; DAF; EQ; BIO; NIT; CD"},
      {"treatment_id":164,"treatment_description":null,"treatment_codes":"MPT; OW; DAF; EQ; BIO; NIT; DENIT; CD"},
      {"treatment_id":165,"treatment_description":null,"treatment_codes":"BMP; MPT; OW; DAF; EQ; BIO; FI"},
      {"treatment_id":166,"treatment_description":null,"treatment_codes":"BMP; MPT; OW; DAF; EQ; BIO; CD"},
      {"treatment_id":167,"treatment_description":null,"treatment_codes":"BMP; OW; ChemPre"},
      {"treatment_id":168,"treatment_description":null,"treatment_codes":"BMP; OW; ChemPre; FI"},
      {"treatment_id":169,"treatment_description":null,"treatment_codes":"ChemPre; FI; ZLD"},
      {"treatment_id":170,"treatment_description":null,"treatment_codes":"BMP; ChemPre; FI"},
      {"treatment_id":171,"treatment_description":null,"treatment_codes":"BMP; AIR; ChemPre"},
      {"treatment_id":172,"treatment_description":null,"treatment_codes":"BMP; CO; ChemPre; FI"},
      {"treatment_id":173,"treatment_description":null,"treatment_codes":"BMP; CO; ChemPre"},
      {"treatment_id":174,"treatment_description":null,"treatment_codes":"BMP; OW; ADSM"},
      {"treatment_id":175,"treatment_description":null,"treatment_codes":"OW; EQ"},
      {"treatment_id":176,"treatment_description":null,"treatment_codes":"MPT; EQ; ChemPre; CLAR; ASG"},
      {"treatment_id":177,"treatment_description":null,"treatment_codes":"MPT; EQ; ChemPre; CLAR; ASG; FI; GAC"},
      {"treatment_id":178,"treatment_description":null,"treatment_codes":"MPT; EQ; ASG"},
      {"treatment_id":179,"treatment_description":null,"treatment_codes":"MPT; EQ; ASG; FI; GAC"},
      {"treatment_id":180,"treatment_description":null,"treatment_codes":"EQ; ChemPre; CLAR; ASG"},
      {"treatment_id":181,"treatment_description":null,"treatment_codes":"EQ; ChemPre; CLAR; ASG; FI; GAC"},
      {"treatment_id":182,"treatment_description":null,"treatment_codes":"ChemPre; EQ"},
      {"treatment_id":183,"treatment_description":null,"treatment_codes":"FILT; CLAR"},
      {"treatment_id":184,"treatment_description":null,"treatment_codes":"OW; BCF"},
      {"treatment_id":185,"treatment_description":null,"treatment_codes":"OW; BCF; BMP; CLAR"},
      {"treatment_id":186,"treatment_description":null,"treatment_codes":"ChemPre; CLAR; ASG; GRAVS"},
      {"treatment_id":187,"treatment_description":null,"treatment_codes":"REDX; ChemPre; ChemPre; CLAR; ASG; GRAVS"},
      {"treatment_id":188,"treatment_description":null,"treatment_codes":"ChemPre; CLAR; ASG; GRAVS"},
      {"treatment_id":189,"treatment_description":null,"treatment_codes":"COAGFL; CLAR"},
      {"treatment_id":136,"treatment_description":null,"treatment_codes":"EMUL; OW; ChemPre"},
      {"treatment_id":137,"treatment_description":null,"treatment_codes":"EVAP; ZLD"},
      {"treatment_id":138,"treatment_description":null,"treatment_codes":"ION; ZLD"},
      {"treatment_id":139,"treatment_description":null,"treatment_codes":"EQ; ChemPre; ASG"},
      {"treatment_id":140,"treatment_description":null,"treatment_codes":"EQ; ChemPre; AOP"},
      {"treatment_id":190,"treatment_description":null,"treatment_codes":"ChemPre; COAGFL; CLAR"},
      {"treatment_id":191,"treatment_description":null,"treatment_codes":"ChemPre; EQ; ASG; CLAR"},
      {"treatment_id":192,"treatment_description":null,"treatment_codes":"ChemPre; CLAR; EQ; ASG; CLAR"},
      {"treatment_id":193,"treatment_description":null,"treatment_codes":"MPT; BIO"},
      {"treatment_id":194,"treatment_description":null,"treatment_codes":"MPT; BIO; CD"},
      {"treatment_id":195,"treatment_description":null,"treatment_codes":"MPT; CLAR; BIO; CD"},
      {"treatment_id":196,"treatment_description":null,"treatment_codes":"DAF; BIO"},
      {"treatment_id":197,"treatment_description":null,"treatment_codes":"AC; ChemPre; CLAR"},
      {"treatment_id":198,"treatment_description":null,"treatment_codes":"ChemPre; CLAR; ION"},
      {"treatment_id":199,"treatment_description":null,"treatment_codes":"ION"},
      {"treatment_id":200,"treatment_description":null,"treatment_codes":"BMP; DAF; BIO"},
      {"treatment_id":201,"treatment_description":null,"treatment_codes":"BMP; DAF; BIO; CD"},
      {"treatment_id":202,"treatment_description":null,"treatment_codes":"BMP; DAF; BIO; FI"},
      {"treatment_id":203,"treatment_description":null,"treatment_codes":"BMP; DAF; BIO; NIT; DENIT; FI"},
      {"treatment_id":204,"treatment_description":null,"treatment_codes":"MPT; DAF; BIO; NIT; CD"},
      {"treatment_id":205,"treatment_description":null,"treatment_codes":"MPT; DAF; BIO; NIT; DENIT; CD"},
      {"treatment_id":206,"treatment_description":null,"treatment_codes":"MPT; OW"},
      {"treatment_id":207,"treatment_description":null,"treatment_codes":"MPT; OW; ASG"},
      {"treatment_id":208,"treatment_description":null,"treatment_codes":"MPT; DAF"},
      {"treatment_id":209,"treatment_description":null,"treatment_codes":"BMP; MPT; ASG"},
      {"treatment_id":210,"treatment_description":null,"treatment_codes":"BMP; MPT; OW"},
      {"treatment_id":211,"treatment_description":null,"treatment_codes":"MPT; OW; DAF"},
      {"treatment_id":212,"treatment_description":null,"treatment_codes":"MPT; EQ; DAF"},
      {"treatment_id":213,"treatment_description":null,"treatment_codes":"BMP; BIO"},
      {"treatment_id":214,"treatment_description":null,"treatment_codes":"BMP; CLAR"},
      {"treatment_id":215,"treatment_description":null,"treatment_codes":"SI; ChemPre; BMP"},
      {"treatment_id":216,"treatment_description":null,"treatment_codes":"SI; ChemPre"},
      {"treatment_id":217,"treatment_description":null,"treatment_codes":"CLAR; BMP"},
      {"treatment_id":218,"treatment_description":null,"treatment_codes":"CLAR; BMP; BIO"},
      {"treatment_id":219,"treatment_description":null,"treatment_codes":"CLAR; ChemPre; BMP"},
      {"treatment_id":220,"treatment_description":null,"treatment_codes":"BMP; MPT"},
      {"treatment_id":221,"treatment_description":null,"treatment_codes":"BMP; MPT; DAF"},
      {"treatment_id":222,"treatment_description":null,"treatment_codes":"ChemPre; SI"},
      {"treatment_id":223,"treatment_description":null,"treatment_codes":"SLUDGE; SI"},
      {"treatment_id":224,"treatment_description":null,"treatment_codes":"SI; ZLD"},
      {"treatment_id":225,"treatment_description":null,"treatment_codes":"BMP; EMUL; OW; ChemPre"},
      {"treatment_id":226,"treatment_description":null,"treatment_codes":"BMP; REDX; ChemPre"},
      {"treatment_id":227,"treatment_description":null,"treatment_codes":"BMP; EMUL; OW; ChemPre; FI"},
      {"treatment_id":228,"treatment_description":null,"treatment_codes":"BMP; REDX; ChemPre; FI"},
      {"treatment_id":229,"treatment_description":null,"treatment_codes":"BMP; MPT; CLAR; REUSE"},
      {"treatment_id":230,"treatment_description":null,"treatment_codes":"BMP; BIO; REUSE"},
      {"treatment_id":231,"treatment_description":null,"treatment_codes":"BMP; BIO; FI; REUSE"},
      {"treatment_id":232,"treatment_description":null,"treatment_codes":"BMP; CLAR; BIO"},
      {"treatment_id":233,"treatment_description":null,"treatment_codes":"BMP; COAGFL"},
      {"treatment_id":234,"treatment_description":null,"treatment_codes":"BMP; MPT; CLAR"},
      {"treatment_id":235,"treatment_description":null,"treatment_codes":"COAGFL; BMP"},
      {"treatment_id":236,"treatment_description":null,"treatment_codes":"REUSE"},
      {"treatment_id":237,"treatment_description":null,"treatment_codes":"ChemPre; MF"},
      {"treatment_id":238,"treatment_description":null,"treatment_codes":"ChemPre; MF; MF; DCL"},
      {"treatment_id":239,"treatment_description":null,"treatment_codes":"ChemPre; FI; SLUDGE"},
      {"treatment_id":240,"treatment_description":null,"treatment_codes":"ChemPre; SLUDGE"},
      {"treatment_id":241,"treatment_description":null,"treatment_codes":"ChemPre; AIR; CLAR; EQ; ChemPre; FI"},
      {"treatment_id":242,"treatment_description":null,"treatment_codes":"EQ; ChemPre; FI"},
      {"treatment_id":243,"treatment_description":null,"treatment_codes":"EQ; AIR; ChemPre"},
      {"treatment_id":244,"treatment_description":null,"treatment_codes":"EQ"},
      {"treatment_id":245,"treatment_description":null,"treatment_codes":"EQ; AIR; ChemPre"},
      {"treatment_id":246,"treatment_description":null,"treatment_codes":"EQ; ChemPre; FI"},
      {"treatment_id":247,"treatment_description":null,"treatment_codes":"EQ; REDX; ChemPre; MF"},
      {"treatment_id":248,"treatment_description":null,"treatment_codes":"REDX; ChemPre; MF"},
      {"treatment_id":249,"treatment_description":null,"treatment_codes":"REDX; REDX; ChemPre; SLUDGE"},
      {"treatment_id":250,"treatment_description":null,"treatment_codes":"FI; SLUDGE"},
      {"treatment_id":251,"treatment_description":null,"treatment_codes":"BMP; MPT; CLAR; REUSE; BIO; EQ; ZLD"},
      {"treatment_id":252,"treatment_description":null,"treatment_codes":"BMP; REUSE; BIO"},
      {"treatment_id":253,"treatment_description":null,"treatment_codes":"BMP; REUSE; BIO; FI"},
      {"treatment_id":254,"treatment_description":null,"treatment_codes":"BMP; SI; BIO"},
      {"treatment_id":255,"treatment_description":null,"treatment_codes":"BMP; ST; ChemPre; FI"},
      {"treatment_id":256,"treatment_description":null,"treatment_codes":"BMP; ST; ChemPre; FI; REUSE"},
      {"treatment_id":257,"treatment_description":null,"treatment_codes":"BMP; OW; ST; ChemPre; FI"},
      {"treatment_id":258,"treatment_description":null,"treatment_codes":"ChemPre; ChemPre"},
      {"treatment_id":259,"treatment_description":null,"treatment_codes":"ChemPre; ChemPre; FI"},
      {"treatment_id":260,"treatment_description":null,"treatment_codes":"ChemPre; REUSE"},
      {"treatment_id":261,"treatment_description":null,"treatment_codes":"ChemPre; BMP; FI"},
      {"treatment_id":262,"treatment_description":null,"treatment_codes":"ChemPre; BMP; FI; GAC"},
      {"treatment_id":263,"treatment_description":null,"treatment_codes":"ChemPre; FI; REUSE"},
      {"treatment_id":264,"treatment_description":null,"treatment_codes":"ChemPre; ST; FI"},
      {"treatment_id":265,"treatment_description":null,"treatment_codes":"ChemPre; ST; ChemPre; ION"},
      {"treatment_id":266,"treatment_description":null,"treatment_codes":"ChemPre; OW; ST"},
      {"treatment_id":267,"treatment_description":null,"treatment_codes":"ChemPre; OW; ChemPre; BMP; SORP; FI"},
      {"treatment_id":268,"treatment_description":null,"treatment_codes":"ChemPre; OW; ST; GAC; ChemPre; FI"},
      {"treatment_id":269,"treatment_description":null,"treatment_codes":"OW; ChemPre"},
      {"treatment_id":270,"treatment_description":null,"treatment_codes":"OW; ChemPre; REUSE"},
      {"treatment_id":271,"treatment_description":null,"treatment_codes":"OW; ChemPre; ION"},
      {"treatment_id":272,"treatment_description":null,"treatment_codes":"OW; ChemPre; ION; BMP"},
      {"treatment_id":273,"treatment_description":null,"treatment_codes":"OW; ChemPre; BMP; FI"},
      {"treatment_id":274,"treatment_description":null,"treatment_codes":"OW; ST; ChemPre"},
      {"treatment_id":275,"treatment_description":null,"treatment_codes":"OW; ST; ChemPre; FI"},
      {"treatment_id":276,"treatment_description":null,"treatment_codes":"ST; ChemPre"},
      {"treatment_id":277,"treatment_description":null,"treatment_codes":"ST; ChemPre; REUSE"},
      {"treatment_id":278,"treatment_description":null,"treatment_codes":"ST; ChemPre; FI"},
      {"treatment_id":279,"treatment_description":null,"treatment_codes":"ST; ChemPre; FI; REUSE"},
      {"treatment_id":280,"treatment_description":null,"treatment_codes":"ST; ChemPre; ChemPre"},
      {"treatment_id":281,"treatment_description":null,"treatment_codes":"ST; ChemPre; ChemPre; FI"},
      {"treatment_id":282,"treatment_description":null,"treatment_codes":"ST; ChemPre; BMP; ChemPre; FI; ION"},
      {"treatment_id":283,"treatment_description":null,"treatment_codes":"ST; ChemPre; BMP; FI"},
      {"treatment_id":284,"treatment_description":null,"treatment_codes":"ST; BMP; ChemPre; ChemPre; FI"},
      {"treatment_id":285,"treatment_description":null,"treatment_codes":"MPT; COAGFL; BIO"},
      {"treatment_id":286,"treatment_description":null,"treatment_codes":"BMP; OW; ST; GAC; ChemPre; FI"},
      {"treatment_id":287,"treatment_description":null,"treatment_codes":"CLAR; REUSE"},
      {"treatment_id":288,"treatment_description":null,"treatment_codes":"ChemPre; ST; ChemPre; FI"},
      {"treatment_id":289,"treatment_description":null,"treatment_codes":"CLAR; REUSE; CD"},
      {"treatment_id":290,"treatment_description":null,"treatment_codes":"CLAR; COAGFL; CD"},
      {"treatment_id":291,"treatment_description":null,"treatment_codes":"CLAR; COAGFL; CD; REUSE"},
      {"treatment_id":292,"treatment_description":null,"treatment_codes":"BMP; CLAR; COAGFL; CD"},
      {"treatment_id":293,"treatment_description":null,"treatment_codes":"ChemPre; COAGFL"},
      {"treatment_id":294,"treatment_description":null,"treatment_codes":"ChemPre; COAGFL; REUSE"},
      {"treatment_id":295,"treatment_description":null,"treatment_codes":"ChemPre; COAGFL; FI; REUSE"},
      {"treatment_id":296,"treatment_description":null,"treatment_codes":"COAGFL"},
      {"treatment_id":297,"treatment_description":null,"treatment_codes":"COAGFL; CD"},
      {"treatment_id":298,"treatment_description":null,"treatment_codes":"COAGFL; BMP"},
      {"treatment_id":299,"treatment_description":null,"treatment_codes":"CO; CLAR"},
      {"treatment_id":300,"treatment_description":null,"treatment_codes":"CD; CLAR; FILT"},
      {"treatment_id":301,"treatment_description":null,"treatment_codes":"CD; CLAR; FILT; REUSE"},
      {"treatment_id":302,"treatment_description":null,"treatment_codes":"SI; REUSE"},
      {"treatment_id":303,"treatment_description":null,"treatment_codes":"BMP; GravS; CLAR; SI; REUSE"},
      {"treatment_id":304,"treatment_description":null,"treatment_codes":"SI; GravS"},
      {"treatment_id":305,"treatment_description":null,"treatment_codes":"CLAR; EQ; REUSE"},
      {"treatment_id":306,"treatment_description":null,"treatment_codes":"BMP; CLAR; REUSE"},
      {"treatment_id":307,"treatment_description":null,"treatment_codes":"BMP; REUSE"},
      {"treatment_id":308,"treatment_description":null,"treatment_codes":"BMP; ASG"},
      {"treatment_id":309,"treatment_description":null,"treatment_codes":"CLAR; OTHER"},
      {"treatment_id":310,"treatment_description":null,"treatment_codes":"BMP; EQ; BIO; GravS"},
      {"treatment_id":311,"treatment_description":null,"treatment_codes":"BMP; ASG; FI"},
      {"treatment_id":312,"treatment_description":null,"treatment_codes":"GravS; ASG; GravS"},
      {"treatment_id":313,"treatment_description":null,"treatment_codes":"ASG; FI"},
      {"treatment_id":314,"treatment_description":null,"treatment_codes":"ASG; GravS"},
      {"treatment_id":315,"treatment_description":null,"treatment_codes":"EQ; GravS; ASG; GravS; BIO"},
      {"treatment_id":316,"treatment_description":null,"treatment_codes":"EQ; ASG; FI"},
      {"treatment_id":317,"treatment_description":null,"treatment_codes":"EQ; GravS; ASG; GravS"},
      {"treatment_id":318,"treatment_description":null,"treatment_codes":"ASG; GravS; FI"},
      {"treatment_id":319,"treatment_description":null,"treatment_codes":"BMP; BIO; FI"},
      {"treatment_id":320,"treatment_description":null,"treatment_codes":"BMP; EQ; OWS; CO; COAGFL; ASG; GAC"},
      {"treatment_id":321,"treatment_description":null,"treatment_codes":"BMP; EQ; OWS; CO; COAGFL"},
      {"treatment_id":322,"treatment_description":null,"treatment_codes":"BMP; OW; EQ; DAF; ASG"},
      {"treatment_id":323,"treatment_description":null,"treatment_codes":"BMP; OW; EQ; DAF"},
      {"treatment_id":324,"treatment_description":null,"treatment_codes":"BMP; OW; DAF; ASG"},
      {"treatment_id":325,"treatment_description":null,"treatment_codes":"BMP; OW; EQ; ASG"},
      {"treatment_id":326,"treatment_description":null,"treatment_codes":"EQ; ChemPre; ASG; FI"},
      {"treatment_id":327,"treatment_description":null,"treatment_codes":"ChemPre; ChemPre; SI; BMP"},
      {"treatment_id":328,"treatment_description":null,"treatment_codes":"AST; DENIT"},
      {"treatment_id":329,"treatment_description":null,"treatment_codes":"AKH; AST"},
      {"treatment_id":330,"treatment_description":null,"treatment_codes":"ION; FDN"},
      {"treatment_id":331,"treatment_description":null,"treatment_codes":"BMP; REUSE"},
      {"treatment_id":332,"treatment_description":null,"treatment_codes":"REDX; ChemPre"},
      {"treatment_id":333,"treatment_description":null,"treatment_codes":"AC; ChemPre"},
      {"treatment_id":334,"treatment_description":null,"treatment_codes":"ChemPre; ION"},
      {"treatment_id":335,"treatment_description":null,"treatment_codes":"COAGFL; REUSE"},
      {"treatment_id":336,"treatment_description":null,"treatment_codes":"COAGFL; REUSE; ChemPre"},
      {"treatment_id":337,"treatment_description":null,"treatment_codes":"ChemPre; COAGFL; FI"},
      {"treatment_id":338,"treatment_description":null,"treatment_codes":"ChemPre; COAGFL; FI; ST"},
      {"treatment_id":339,"treatment_description":null,"treatment_codes":"COAGFL; FILT"},
      {"treatment_id":340,"treatment_description":null,"treatment_codes":"EQ; OWS; DAF; FILT"},
      {"treatment_id":341,"treatment_description":null,"treatment_codes":"FILT"},
      {"treatment_id":342,"treatment_description":null,"treatment_codes":"MPT; FI"},
      {"treatment_id":343,"treatment_description":null,"treatment_codes":"OW; BMP"},
      {"treatment_id":344,"treatment_description":null,"treatment_codes":"REUSE; FILT"},
      {"treatment_id":345,"treatment_description":null,"treatment_codes":"REUSE; GravS; FILT; BMP"},
      {"treatment_id":346,"treatment_description":null,"treatment_codes":"REUSE; OWS; REUSE; OWS"},
      {"treatment_id":347,"treatment_description":null,"treatment_codes":"CLAR; REUSE; ChemPre"},
      {"treatment_id":348,"treatment_description":null,"treatment_codes":"OW; FI; REUSE"},
      {"treatment_id":349,"treatment_description":null,"treatment_codes":"CLAR; REUSE; ChemPre"},
      {"treatment_id":350,"treatment_description":null,"treatment_codes":"OW; FILT; ChemPre"},
      {"treatment_id":351,"treatment_description":null,"treatment_codes":"OW; FI; REUSE; ChemPre"},
      {"treatment_id":352,"treatment_description":null,"treatment_codes":"REDX; ChemPre; ChemPre; FI"},
      {"treatment_id":353,"treatment_description":null,"treatment_codes":"OW; GravS"},
      {"treatment_id":354,"treatment_description":null,"treatment_codes":"BMP; SI"},
      {"treatment_id":355,"treatment_description":null,"treatment_codes":"BMP; GravS"},
      {"treatment_id":356,"treatment_description":null,"treatment_codes":"DST; REUSE"},
      {"treatment_id":357,"treatment_description":null,"treatment_codes":"BMP; EC; CO"},
      {"treatment_id":358,"treatment_description":null,"treatment_codes":"REDX; ChemPre; REUSE"},
      {"treatment_id":359,"treatment_description":null,"treatment_codes":"REDX; BMP; OW; ChemPre; EQ; REUSE; FI"},
      {"treatment_id":360,"treatment_description":null,"treatment_codes":"REDX; OW; ChemPre; EQ; REUSE; FI"},
      {"treatment_id":361,"treatment_description":null,"treatment_codes":"REDX; ChemPre; EQ; REUSE"},
      {"treatment_id":362,"treatment_description":null,"treatment_codes":"ChemPre; EQ; REUSE"},
      {"treatment_id":363,"treatment_description":null,"treatment_codes":"ChemPre; EQ; FI; REUSE"},
      {"treatment_id":364,"treatment_description":null,"treatment_codes":"REDX; OW; ChemPre"},
      {"treatment_id":365,"treatment_description":null,"treatment_codes":"GravS; FI; REUSE"},
      {"treatment_id":366,"treatment_description":null,"treatment_codes":"COAGFL; FI"},
      {"treatment_id":367,"treatment_description":null,"treatment_codes":"EQ; CLAR; ASG"},
      {"treatment_id":368,"treatment_description":null,"treatment_codes":"MPT; BIO; OW; CD"},
      {"treatment_id":369,"treatment_description":null,"treatment_codes":"COAGFL; ChemPre"},
      {"treatment_id":370,"treatment_description":null,"treatment_codes":"EQ; OW; COAGFL"},
      {"treatment_id":371,"treatment_description":null,"treatment_codes":"ASG; COAGFL; CD"},
      {"treatment_id":372,"treatment_description":null,"treatment_codes":"BMP; GravS; SI"},
      {"treatment_id":373,"treatment_description":null,"treatment_codes":"BMP; SI; REUSE"},
      {"treatment_id":374,"treatment_description":null,"treatment_codes":"BMP; OW; BIO; CO; REUSE; THERMAL"},
      {"treatment_id":375,"treatment_description":null,"treatment_codes":"BMP; OW; REUSE"},
      {"treatment_id":376,"treatment_description":null,"treatment_codes":"REUSE; BMP; SI"},
      {"treatment_id":377,"treatment_description":null,"treatment_codes":"BMP; EQ; OW; OW; BIO; FI"},
      {"treatment_id":378,"treatment_description":null,"treatment_codes":"OW; ST"},
      {"treatment_id":379,"treatment_description":null,"treatment_codes":"REDX"},
      {"treatment_id":380,"treatment_description":null,"treatment_codes":"BMP; ANSG"},
      {"treatment_id":381,"treatment_description":null,"treatment_codes":"OW; EQ; ASG; AIR"},
      {"treatment_id":382,"treatment_description":null,"treatment_codes":"OW; EQ; DAF; ASG; AIR"},
      {"treatment_id":383,"treatment_description":null,"treatment_codes":"REUSE; OW; EQ; ASG; AIR"},
      {"treatment_id":384,"treatment_description":null,"treatment_codes":"REUSE; OW; EQ; DAF; ASG; AIR"},
      {"treatment_id":385,"treatment_description":null,"treatment_codes":"MPT; GravS; BIO"},
      {"treatment_id":386,"treatment_description":null,"treatment_codes":"GravS; BIO; GravS"},
      {"treatment_id":387,"treatment_description":null,"treatment_codes":"CO"},
      {"treatment_id":388,"treatment_description":null,"treatment_codes":"THERMAL"},
      {"treatment_id":389,"treatment_description":null,"treatment_codes":"ADSM"},
      {"treatment_id":390,"treatment_description":null,"treatment_codes":"LE"},
      {"treatment_id":391,"treatment_description":null,"treatment_codes":"GAC; REUSE"},
      {"treatment_id":392,"treatment_description":null,"treatment_codes":"BIO; REUSE"},
      {"treatment_id":393,"treatment_description":null,"treatment_codes":"CO; REUSE"},
      {"treatment_id":394,"treatment_description":null,"treatment_codes":"THERMAL; REUSE"},
      {"treatment_id":395,"treatment_description":null,"treatment_codes":"ADSM; REUSE"},
      {"treatment_id":396,"treatment_description":null,"treatment_codes":"LE; REUSE"},
      {"treatment_id":397,"treatment_description":null,"treatment_codes":"OST; BIO; GAC"},
      {"treatment_id":398,"treatment_description":null,"treatment_codes":"AKH"},
      {"treatment_id":399,"treatment_description":null,"treatment_codes":"AKH; REUSE"},
      {"treatment_id":400,"treatment_description":null,"treatment_codes":"OST; BIO; GAC; BIO"},
      {"treatment_id":401,"treatment_description":null,"treatment_codes":"OST; BIO; GAC; REUSE; BIO"},
      {"treatment_id":402,"treatment_description":null,"treatment_codes":"OST; BIO; GAC; REUSE"},
      {"treatment_id":403,"treatment_description":null,"treatment_codes":"AST"},
      {"treatment_id":404,"treatment_description":null,"treatment_codes":"REUSE; BMP; REDX; OW; ChemPre"},
      {"treatment_id":405,"treatment_description":null,"treatment_codes":"REUSE; BMP; REDX; OW; ChemPre; FI"},
      {"treatment_id":406,"treatment_description":null,"treatment_codes":"BMP; REDX; EQ; EMUL; DAF; OW; ChemPre"},
      {"treatment_id":407,"treatment_description":null,"treatment_codes":"BMP; MPT; OW; DAF"},
      {"treatment_id":408,"treatment_description":null,"treatment_codes":"BMP; MPT; EQ; DAF"},
      {"treatment_id":409,"treatment_description":null,"treatment_codes":"BMP; REUSE; DAF"},
      {"treatment_id":410,"treatment_description":null,"treatment_codes":"REUSE; MPT"},
      {"treatment_id":411,"treatment_description":null,"treatment_codes":"REUSE; BMP; MPT"},
      {"treatment_id":412,"treatment_description":null,"treatment_codes":"REUSE; BMP; MPT; DAF"},
      {"treatment_id":413,"treatment_description":null,"treatment_codes":"DRY"},
      {"treatment_id":414,"treatment_description":null,"treatment_codes":"OW; EQ; AST; EQ; BIO; NIT; CLAR"},
      {"treatment_id":415,"treatment_description":null,"treatment_codes":"OW; GravS; COAGFL"},
      {"treatment_id":416,"treatment_description":null,"treatment_codes":"GravS"},
      {"treatment_id":417,"treatment_description":null,"treatment_codes":"MPT; CD"},
      {"treatment_id":418,"treatment_description":null,"treatment_codes":"OW; GravS; COAGFL; DGF"},
      {"treatment_id":419,"treatment_description":null,"treatment_codes":"BIO; GravS; CD"},
      {"treatment_id":420,"treatment_description":null,"treatment_codes":"MPT; BMP"},
      {"treatment_id":421,"treatment_description":null,"treatment_codes":"EMUL; ChemPre; EQ; OW; ChemPre"},
      {"treatment_id":422,"treatment_description":null,"treatment_codes":"EMUL; ChemPre; EQ; OW; ChemPre; FI"},
      {"treatment_id":423,"treatment_description":null,"treatment_codes":"ChemPre; SI; REUSE"},
      {"treatment_id":424,"treatment_description":null,"treatment_codes":"REUSE; EVAP"},
      {"treatment_id":425,"treatment_description":null,"treatment_codes":"REUSE; SI; ChemPre; COAGFL"},
      {"treatment_id":426,"treatment_description":null,"treatment_codes":"SI; COAGFL"},
      {"treatment_id":427,"treatment_description":null,"treatment_codes":"SI; REUSE; AC"},
      {"treatment_id":428,"treatment_description":null,"treatment_codes":"SI; SI; ChemPre"},
      {"treatment_id":429,"treatment_description":null,"treatment_codes":"SI; ChemPre; COAGFL"},
      {"treatment_id":430,"treatment_description":null,"treatment_codes":"SI; ChemPre; ION; ChemPre; CLAR"},
      {"treatment_id":431,"treatment_description":null,"treatment_codes":"S\tI; REUSE; EVAP; ChemPre; CLAR; AIR"},
      {"treatment_id":432,"treatment_description":null,"treatment_codes":"SI; ChemPre; ChemPre; ION; ChemPre; SI; AIR"},
      {"treatment_id":433,"treatment_description":null,"treatment_codes":"OW; ChemPre; FI"},
      {"treatment_id":434,"treatment_description":null,"treatment_codes":"HAUL"}];

    return queryInterface.bulkInsert({ schema: "elg_search", tableName: "TreatmentTechnology" }, records);
  },
  down: (queryInterface) => queryInterface.bulkDelete({
    schema: "elg_search",
    tableName: "TreatmentTechnology"
  }, null, {})
};
